Repository gchq/sleeper, pull requests merged in 2022-11, with the labels that each got.

#297 Issue 295 - Create unit tests from IngestRecordsIT
  java/ingest/pom.xml
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsIT.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsITBase.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsTest.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsTestBase.java
  java/ingest/src/test/java/sleeper/ingest/testutils/AssertQuantiles.java
  java/ingest/src/test/java/sleeper/ingest/testutils/ExpectedQuantile.java
  java/ingest/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java
Labels: pr-base-for-stacking

#302 Issue 296 - Create unit tests from IngestRecordsFromIteratorIT
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsFromIteratorTest.java
  java/ingest/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java
Labels: pr-logically-coupled

#304 Issue 303 - Make IngestJobQueueConsumer use IngestRecordsFromIterator
  java/athena/src/test/java/sleeper/athena/TestUtils.java
  java/ingest/src/main/java/sleeper/ingest/IngestRecords.java
  java/ingest/src/main/java/sleeper/ingest/IngestRecordsFromIterator.java
  java/ingest/src/main/java/sleeper/ingest/IngestRecordsUsingPropertiesSpecifiedMethod.java
  java/ingest/src/main/java/sleeper/ingest/IngestResult.java
  java/ingest/src/main/java/sleeper/ingest/impl/StandardIngestCoordinator.java
  java/ingest/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsFromIteratorTest.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsIT.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsTest.java
  java/ingest/src/test/java/sleeper/ingest/IngestResultTest.java
  java/ingest/src/test/java/sleeper/ingest/job/IngestJobQueueConsumerIT.java
  java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/UploadMultipleShardedSortedParquetFiles.java
Labels: pr-base-for-stacking

#362 Issue 361 - Read Maven dependencies for GitHub Actions build
  java/build/src/main/java/sleeper/build/github/GitHubRunToHead.java
  java/build/src/main/java/sleeper/build/maven/DependencyReference.java
  java/build/src/main/java/sleeper/build/maven/InternalDependencyIndex.java
  java/build/src/main/java/sleeper/build/maven/MavenModuleAndPath.java
  java/build/src/main/java/sleeper/build/maven/MavenModuleStructure.java
  java/build/src/main/java/sleeper/build/maven/MavenPom.java
  java/build/src/main/java/sleeper/build/status/GitHubStatusProvider.java
  java/build/src/test/java/sleeper/build/maven/InternalDependencyIndexTest.java
  java/build/src/test/java/sleeper/build/maven/MavenPomTest.java
  java/build/src/test/java/sleeper/build/maven/TestMavenModuleStructure.java
  java/build/src/test/resources/maven-example/bulk-import/bulk-import-common/pom.xml
  java/build/src/test/resources/maven-example/bulk-import/bulk-import-runner/pom.xml
  java/build/src/test/resources/maven-example/bulk-import/bulk-import-starter/pom.xml
  java/build/src/test/resources/maven-example/configuration/pom.xml
  java/build/src/test/resources/maven-example/ingest/pom.xml
Labels: pr-base-for-stacking

#364 Issue 363 - Refactor GitHub Actions code to query runs instead of chunks
  .github/workflows/maven-full.yaml
  java/build/src/main/java/sleeper/build/chunks/ProjectConfiguration.java
  java/build/src/main/java/sleeper/build/chunks/ProjectStructure.java
  java/build/src/main/java/sleeper/build/github/GitHubHead.java
  java/build/src/main/java/sleeper/build/github/GitHubWorkflowRun.java
  java/build/src/main/java/sleeper/build/github/GitHubWorkflowRuns.java
  java/build/src/main/java/sleeper/build/github/GitHubWorkflowRunsImpl.java
  java/build/src/main/java/sleeper/build/status/CheckGitHubStatus.java
  java/build/src/main/java/sleeper/build/status/CheckGitHubStatusMain.java
  java/build/src/main/java/sleeper/build/status/ChunkStatus.java
  java/build/src/main/java/sleeper/build/status/ChunkStatuses.java
  java/build/src/main/java/sleeper/build/status/WorkflowStatus.java
  java/build/src/main/java/sleeper/build/util/PrintUtils.java
  java/build/src/test/java/sleeper/build/chunks/GetChunkConfigTest.java
  java/build/src/test/java/sleeper/build/chunks/ProjectConfigurationTest.java
  java/build/src/test/java/sleeper/build/github/InMemoryGitHubWorkflowRuns.java
  java/build/src/test/java/sleeper/build/github/InMemoryGitHubWorkflowRunsTest.java
  java/build/src/test/java/sleeper/build/status/CheckGitHubStatusSingleWorkflowTest.java
  java/build/src/test/java/sleeper/build/status/CheckGitHubStatusSplitWorkflowTest.java
  java/build/src/test/java/sleeper/build/status/CheckGitHubStatusTest.java
  java/build/src/test/java/sleeper/build/status/ChunkStatusesTest.java
  java/build/src/test/resources/example-chunks.yaml
Labels: pr-base-for-stacking

#367 Issue 366 - Create IngestJob builder
  java/ingest/src/main/java/sleeper/ingest/job/IngestJob.java
  java/ingest/src/test/java/sleeper/ingest/job/IngestJobQueueConsumerFullIT.java
  java/ingest/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/ingest/src/test/java/sleeper/ingest/job/IngestJobSerDeTest.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/WriteRandomDataViaQueueJob.java
Labels: pr-logically-isolated

#349 Issue 345 - Remove IngestProperties
  java/ingest/src/main/java/sleeper/ingest/IngestProperties.java
  java/ingest/src/main/java/sleeper/ingest/impl/IngestFactory.java
  java/ingest/src/main/java/sleeper/ingest/impl/StandardIngestCoordinator.java
  java/ingest/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
Labels: pr-logically-coupled

#379 Issue 369 - Move TTL setup into dynamodb-tools module
  java/compaction-status-store/src/main/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusStoreCreator.java
  java/compaction-status-store/src/main/java/sleeper/compaction/status/task/DynamoDBCompactionTaskStatusStoreCreator.java
  java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java
Labels: pr-base-for-stacking

#389 Issue 388 - Remove IngestRecordsUsingPropertiesSpecifiedMethod
  java/athena/src/test/java/sleeper/athena/TestUtils.java
  java/ingest/src/main/java/sleeper/ingest/IngestFactory.java
  java/ingest/src/main/java/sleeper/ingest/IngestProperties.java
  java/ingest/src/main/java/sleeper/ingest/IngestRecordsUsingPropertiesSpecifiedMethod.java
  java/ingest/src/main/java/sleeper/ingest/impl/StandardIngestCoordinator.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsTest.java
  java/ingest/src/test/java/sleeper/ingest/impl/IngestCoordinatorBespokeUsingDirectWriteBackedByArrowIT.java
  java/ingest/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
  java/ingest/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java
  java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java
  java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/splitter/src/test/java/sleeper/splitter/FindPartitionsToSplitIT.java
Labels: pr-base-for-stacking

#390 Issue 336 - Create IngestRecords and IngestRecordsFromIterator with instance and table properties, remove IngestProperties
  java/athena/src/test/java/sleeper/athena/TestUtils.java
  java/ingest/src/main/java/sleeper/ingest/IngestFactory.java
  java/ingest/src/main/java/sleeper/ingest/IngestProperties.java
  java/ingest/src/main/java/sleeper/ingest/IngestRecords.java
  java/ingest/src/main/java/sleeper/ingest/IngestRecordsFromIterator.java
  java/ingest/src/main/java/sleeper/ingest/impl/IngestCoordinator.java
  java/ingest/src/main/java/sleeper/ingest/impl/ParquetConfiguration.java
  java/ingest/src/main/java/sleeper/ingest/impl/StandardIngestCoordinator.java
  java/ingest/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriterFactory.java
  java/ingest/src/main/java/sleeper/ingest/impl/partitionfilewriter/DirectPartitionFileWriterFactory.java
  java/ingest/src/main/java/sleeper/ingest/impl/recordbatch/arraylist/ArrayListRecordBatchFactory.java
  java/ingest/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordBatchFactory.java
  java/ingest/src/main/java/sleeper/ingest/job/IngestJobRunner.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsFromIteratorTest.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsIT.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsITBase.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsTest.java
  java/ingest/src/test/java/sleeper/ingest/IngestRecordsTestBase.java
  java/ingest/src/test/java/sleeper/ingest/IngestResultTest.java
  java/ingest/src/test/java/sleeper/ingest/impl/IngestCoordinatorBespokeUsingDirectWriteBackedByArrayListIT.java
  java/ingest/src/test/java/sleeper/ingest/impl/IngestCoordinatorBespokeUsingDirectWriteBackedByArrowIT.java
  java/ingest/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
  java/ingest/src/test/java/sleeper/ingest/testutils/IngestCoordinatorTestHelper.java
  java/ingest/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java
  java/query/pom.xml
  java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java
  java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/splitter/pom.xml
  java/splitter/src/test/java/sleeper/splitter/FindPartitionsToSplitIT.java
  java/splitter/src/test/java/sleeper/splitter/SplitPartitionIT.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/UploadMultipleShardedSortedParquetFiles.java
Labels: pr-logically-coupled

#397 Issue 394 - Split compaction TTL into job and task TTL
  example/full/instance.properties
  java/compaction-status-store/src/main/java/sleeper/compaction/status/task/DynamoDBCompactionTaskStatusStore.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  scripts/templates/instanceproperties.template
  scripts/test/system-test-instance.properties
Labels: compactions-module

#404 Issue 399 - Randomly generate an ID for IngestJob if no ID is set
  java/ingest/src/main/java/sleeper/ingest/job/IngestJob.java
  java/ingest/src/test/java/sleeper/ingest/job/IngestJobTest.java
Labels: pr-base-for-stacking
