Repository gchq/sleeper, pull requests merged in 2022-09, with the labels that each got.

#112 Issue 6 - Check that field names are unique in a schema
  java/athena/src/main/java/sleeper/athena/record/SimpleRecordHandler.java
  java/core/src/main/java/sleeper/core/schema/Schema.java
  java/core/src/test/java/sleeper/core/schema/SchemaDuplicateFieldsTest.java
  java/core/src/test/java/sleeper/core/schema/SchemaTest.java
  java/query/src/main/java/sleeper/query/recordretrieval/LeafPartitionQueryExecutor.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java
Labels: pr-base-for-stacking

#119 Issue 7 - Tools for working with partitions in tests
  java/core/src/main/java/sleeper/core/partition/PartitionTree.java
  java/core/src/main/java/sleeper/core/partition/PartitionsFromSplitPoints.java
  java/core/src/test/java/sleeper/core/partition/PartitionFactory.java
  java/core/src/test/java/sleeper/core/partition/PartitionFactoryTest.java
  java/core/src/test/java/sleeper/core/partition/PartitionTreeNearestCommonAncestorTest.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilderTest.java
Labels: pr-base-for-stacking

#109 Issue 98 - Increase default value of Arrow ingest working buffer size
  example/full/instance.properties
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  scripts/templates/instanceproperties.template
  scripts/test/system-test-instance.properties
Labels: pr-logically-isolated

#116 Issue 115 - Script to regenerate deployment output from previous deployment
  scripts/deploy/connectToTable.sh
Labels: pr-logically-isolated

#113 Issue 100 - Fix scripts for bash version pre-installed on Mac
  docs/01-getting-started.md
  scripts/deploy/pre-deployment.sh
  scripts/deploy/tearDown.sh
  scripts/dev/updateVersionNumber.sh
  scripts/test/tearDown.sh
  scripts/utility/sedInPlace.sh
Labels: pr-logically-coupled

#111 Issue 97 - Add an instance property to tag CDK resources with the stack ID
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ConfigurationStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PropertiesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TopicStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/VpcStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
Labels: pr-logically-isolated

#148 Fix issue with shouldNotBringBackValueIfItWasNotAskedFor test in Simp…
  java/athena/src/test/java/sleeper/athena/record/SimpleRecordHandlerIT.java
Labels: pr-logically-isolated

#146 Issue 137 - Split GitHub Actions build per-module
  .github/workflows/check-status.yaml
  .github/workflows/chunk-athena.yaml
  .github/workflows/chunk-bulk-import.yaml
  .github/workflows/chunk-cdk.yaml
  .github/workflows/chunk-clients.yaml
  .github/workflows/chunk-common.yaml
  .github/workflows/chunk-compaction.yaml
  .github/workflows/chunk-data.yaml
  .github/workflows/chunk-ingest.yaml
  .github/workflows/chunk-query.yaml
  .github/workflows/chunk-statestore.yaml
  .github/workflows/chunk.yaml
  .github/workflows/maven-full.yaml
  NOTICES
  java/build/pom.xml
  java/build/src/main/java/sleeper/build/status/CheckGitHubStatus.java
  java/build/src/main/java/sleeper/build/status/ChunkStatus.java
  java/build/src/main/java/sleeper/build/status/ChunksStatus.java
  java/build/src/test/java/sleeper/build/status/ChunksStatusTest.java
  java/build/src/test/resources/one-chunk-successful-one-cancelled.properties
  java/build/src/test/resources/one-chunk-successful-one-failed.properties
  java/build/src/test/resources/one-chunk-successful-one-in-progress.properties
  java/build/src/test/resources/two-chunks-successful.properties
  java/pom.xml
Labels: pr-logically-coupled

#156 Issue 153 - Enforce AssertJ usage in tests
  code-style/checkstyle.xml
  java/athena/src/test/java/sleeper/athena/metadata/IteratorApplyingMetadataHandlerIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/ExecutorFactoryIT.java
  java/clients/src/test/java/sleeper/status/update/ReinitialiseTableIT.java
  java/tables/src/test/java/sleeper/table/job/TableInitialiserIT.java
Labels: pr-logically-isolated

#142 Issue 128 - Refactor CompactionStrategy
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/LeafPartitionCompactionStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/ShouldCreateJobsStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/AbstractCompactionStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/BasicCompactionStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/BasicLeafStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/CompactionFactory.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/CompactionUtils.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/SizeRatioCompactionStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/SizeRatioLeafStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/SizeRatioShouldCreateJobsStrategy.java
Labels: pr-logically-coupled

#157 Issue 145 - Enforce Checkstyle limit on method length
  code-style/checkstyle.xml
  java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java
Labels: pr-logically-isolated

#178 Issue 164 - Add builder to FileInfo class
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobRunner.java
  java/clients/src/test/java/sleeper/status/update/ReinitialiseTableIT.java
  java/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java
  java/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/SizeRatioCompactionStrategyTest.java
  java/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
  java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerIT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/ingest/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriter.java
  java/ingest/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriterUtils.java
  java/splitter/src/test/java/sleeper/splitter/SplitPartitionJobDefinitionSerDeTest.java
  java/statestore/src/main/java/sleeper/statestore/FileInfo.java
  java/statestore/src/main/java/sleeper/statestore/FileInfoSerDe.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormat.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
  java/statestore/src/test/java/sleeper/statestore/FileInfoFactory.java
  java/statestore/src/test/java/sleeper/statestore/FileInfoSerDeTest.java
  java/statestore/src/test/java/sleeper/statestore/FileInfoTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
Labels: pr-logically-isolated

#179 Issue 177 - Wait for old build to finish before reporting chunk status
  .github/workflows/check-status.yaml
  NOTICES
  java/build/pom.xml
  java/build/src/main/java/sleeper/build/status/CheckGitHubStatus.java
  java/build/src/main/java/sleeper/build/status/CheckGitHubStatusMain.java
  java/build/src/main/java/sleeper/build/status/ChunkStatus.java
  java/build/src/main/java/sleeper/build/status/ChunksStatus.java
  java/build/src/main/java/sleeper/build/status/GitHubHead.java
  java/build/src/main/java/sleeper/build/status/ProjectChunk.java
  java/build/src/main/java/sleeper/build/status/ProjectConfiguration.java
  java/build/src/main/java/sleeper/build/status/ValidationUtils.java
  java/build/src/main/java/sleeper/build/status/github/GitHubException.java
  java/build/src/main/java/sleeper/build/status/github/GitHubProvider.java
  java/build/src/main/java/sleeper/build/status/github/GitHubRunToHead.java
  java/build/src/main/resources/log4j.properties
  java/build/src/test/java/sleeper/build/status/CheckGitHubStatusTest.java
  java/build/src/test/java/sleeper/build/status/ChunksStatusTest.java
  java/build/src/test/java/sleeper/build/status/ProjectConfigurationTest.java
  java/build/src/test/java/sleeper/build/status/TestProperties.java
  java/build/src/test/resources/github-example.properties
  java/build/src/test/resources/one-chunk-successful-one-cancelled.properties
  java/build/src/test/resources/two-chunks-missing.properties
  java/build/src/test/resources/two-chunks-successful.properties
  java/pom.xml
Labels: pr-logically-isolated

#180 Issue 160 - Record compaction job created in DynamoDB
  java/compaction-core/pom.xml
  java/compaction-core/src/main/java/sleeper/compaction/job/CompactionFactory.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/LeafPartitionCompactionStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/BasicLeafStrategy.java
  java/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/SizeRatioLeafStrategy.java
  java/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsIT.java
  java/compaction-status-store/pom.xml
  java/compaction-status-store/src/main/java/sleeper/compaction/status/CompactionStatusStoreException.java
  java/compaction-status-store/src/main/java/sleeper/compaction/status/DynamoDBAttributes.java
  java/compaction-status-store/src/main/java/sleeper/compaction/status/DynamoDBUtils.java
  java/compaction-status-store/src/main/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction-status-store/src/main/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusStore.java
  java/compaction-status-store/src/main/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusStoreCreator.java
  java/compaction-status-store/src/test/java/sleeper/compaction/status/job/CompactionStatusStoreTestUtils.java
  java/compaction-status-store/src/test/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusStoreCreatorIT.java
  java/compaction-status-store/src/test/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/FileInfoFactory.java
Labels: pr-logically-coupled

#114 Issue 95 - Fix log message in DeleteMessageAction for ingest jobs
  java/common-job/src/main/java/sleeper/job/common/action/ChangeMessageVisibilityTimeoutAction.java
  java/common-job/src/main/java/sleeper/job/common/action/DeleteMessageAction.java
  java/common-job/src/main/java/sleeper/job/common/action/MessageReference.java
  java/common-job/src/test/java/sleeper/job/common/action/ChangeMessageVisibilityTimeoutActionIT.java
  java/common-job/src/test/java/sleeper/job/common/action/DeleteMessageActionIT.java
  java/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
  java/ingest/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java
Labels: pr-logically-isolated

#108 Issue 99 - Instance property for SqsQueryProcessorLambda thread pool size
  example/full/instance.properties
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/query/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
  java/query/src/main/java/sleeper/query/lambda/SqsQueryProcessorLambda.java
Labels: pr-logically-isolated
