Repository gchq/sleeper, pull requests merged in 2023-09, with the labels that each got.

#1200 Issue 1201 - Java logic to match upload Docker images script
  java/clients/src/main/java/sleeper/clients/admin/UpdatePropertiesWithNano.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/DockerImageConfiguration.java
  java/clients/src/main/java/sleeper/clients/deploy/StackDockerImage.java
  java/clients/src/main/java/sleeper/clients/deploy/UploadDockerImages.java
  java/clients/src/main/java/sleeper/clients/deploy/UploadDockerImagesNew.java
  java/clients/src/main/java/sleeper/clients/util/Command.java
  java/clients/src/main/java/sleeper/clients/util/CommandFailedException.java
  java/clients/src/main/java/sleeper/clients/util/CommandPipeline.java
  java/clients/src/main/java/sleeper/clients/util/CommandPipelineRunner.java
  java/clients/src/main/java/sleeper/clients/util/CommandRunner.java
  java/clients/src/main/java/sleeper/clients/util/EcrRepositoryCreator.java
  java/clients/src/main/java/sleeper/clients/util/cdk/InvokeCdkForInstance.java
  java/clients/src/test/java/sleeper/clients/admin/UpdatePropertiesWithNanoTestHelper.java
  java/clients/src/test/java/sleeper/clients/deploy/UploadDockerImagesNewTest.java
  java/clients/src/test/java/sleeper/clients/testutil/RunCommandTestHelper.java
  java/clients/src/test/java/sleeper/clients/util/EcrRepositoriesInMemory.java
  java/clients/src/test/java/sleeper/clients/util/cdk/InvokeCdkForInstanceTest.java
Labels: pr-base-for-stacking, one-review-required

#1203 Issue 1199 - Share jars and images between instances
  example/full/instance.properties
  example/full/table.properties
  java/clients/src/main/java/sleeper/clients/deploy/DeployExistingInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/PopulateInstanceProperties.java
  java/clients/src/main/java/sleeper/clients/deploy/UploadDockerImages.java
  java/clients/src/main/java/sleeper/clients/deploy/UploadDockerImagesNew.java
  java/clients/src/main/java/sleeper/clients/util/ClientUtils.java
  java/clients/src/main/java/sleeper/clients/util/Command.java
  java/clients/src/main/java/sleeper/clients/util/CommandPipeline.java
  java/clients/src/main/java/sleeper/clients/util/CommandPipelineResult.java
  java/clients/src/main/java/sleeper/clients/util/CommandPipelineRunner.java
  java/clients/src/main/java/sleeper/clients/util/EcrRepositoryCreator.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesTest.java
  java/clients/src/test/java/sleeper/clients/deploy/UploadDockerImagesNewTest.java
  java/clients/src/test/java/sleeper/clients/deploy/UploadDockerImagesTest.java
  java/clients/src/test/java/sleeper/clients/testutil/RunCommandTestHelper.java
  java/clients/src/test/java/sleeper/clients/util/ClientUtilsTest.java
  java/clients/src/test/java/sleeper/clients/util/EcrRepositoriesInMemory.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestInstanceContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestParameters.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestClients.java
  scripts/deploy/uploadDockerImages.sh
  scripts/templates/instanceproperties.template
Labels: one-review-required, pr-stacked-middle

#1168 1086 - Remove/move partition mapping logic
  java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/SleeperTableLambdaIT.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriter.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriterFactory.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/DirectPartitionFileWriter.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/DirectPartitionFileWriterFactory.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriterUtils.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/AwsExternalResource.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorFactory.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorTestHelper.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorTestParameters.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/ResultVerifier.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/TestIngestType.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStoreCreator.java
Labels: pr-base-for-stacking

#1217 Issue 1215 - Improve ingest batcher logging
  java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
  java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambda.java
Labels: pr-logically-isolated

#1219 Issue 1214 - Create properties for queue ARNs
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/SystemDefinedInstanceProperty.java
Labels: pr-logically-isolated

#1223 Issue 1184 - Move ResultVerifier.verify into IngestTestHelper
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrayListIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/ECSIngestTaskIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobQueueConsumerTestBase.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestTestHelper.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/ResultVerifier.java
Labels: one-review-required

#1233 Issue 1232 - Create generated directory when deploying SystemTestDeploymentContext
  java/clients/src/main/java/sleeper/clients/util/cdk/InvokeCdkForInstance.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestDeploymentContext.java
Labels: one-review-required

#1225 Issue 954 - System test for direct & SQS queries
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateNumberedRecords.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateNumberedValue.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateNumberedValueOverrides.java
  java/system-test/system-test-data-generation/src/test/java/sleeper/systemtest/datageneration/GenerateNumberedRecordsTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/python/PythonQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/DirectQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/QueryCreator.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/QueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/QueryRange.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SQSQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/ReadRecordsFromS3.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestLocalFiles.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestDirectIngest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/query/SystemTestQuery.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/sourcedata/SystemTestSourceFiles.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestSchema.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonApiIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/QueryIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java
Labels: one-review-required

#1230 docs(config, docs): normalise CPU architecture names
  docs/01-getting-started.md
  docs/02-deployment-guide.md
  example/full/instance.properties
  example/full/table.properties
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/EMRServerlessProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#1243 Issue 1239 - Include nested test class name in report filename
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/TestContext.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/TestContextTest.java
Labels: one-review-required

#1244 Issue 1240 - Tidy system test reports output
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/ReportingContext.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/reports/SystemTestReporting.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/reports/SystemTestReports.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonApiIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/ReportingExtension.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/ReportingExtensionTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/TestContextFactory.java
Labels: pr-base-for-stacking, one-review-required

#1260 Issue 1247 - Assert on partitions created in PartitionSplittingIT
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/PartitionsTestHelper.java
Labels: one-review-required

#1262 Issue 1261 - Check compaction task types in driver
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/CompactionDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/WaitForJobsDriver.java
Labels: one-review-required

#1264 Issue 1263 - Add logging to NightlyTestOutput.uploadToS3
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestOutput.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestSummaryTable.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestUploader.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputFileSystemIT.java
Labels: one-review-required

#1273 Issue 1270 - Run `docker system prune` in crontab.example
  scripts/test/nightly/crontab.example
Labels: one-review-required

#1274 Issue 1271 - Fix nightly test script
  scripts/cli/runInDocker.sh
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#1269 Issue 1267 - Update links to docs from readme
  README.md
  docs/14-deploy-to-localstack.md
  docs/15-roadmap.md
Labels: one-review-required

#1279 Issue 1278 - Allow loading invalid properties in admin client
  java/clients/src/main/java/sleeper/clients/admin/AdminClientPropertiesStore.java
  java/clients/src/test/java/sleeper/clients/admin/AdminClientPropertiesStoreIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/PropertiesUtils.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/InstanceProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java
Labels: one-review-required

#1280 Issue 1277 - Pass query type from query selected in prompt to job status reports
  java/clients/src/main/java/sleeper/clients/status/report/CompactionJobStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/IngestJobStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/AllJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/DetailedJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/JobQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/RangeJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/RejectedJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/UnfinishedJobsQuery.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/CompactionReportsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestReportsDriver.java
Labels: one-review-required

#1276 Issue 1272 - Update performance tests to run every other day
  scripts/test/nightly/crontab.example
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#1275 Issue 1091 - System test for persistent EMR bulk import
  java/clients/src/main/java/sleeper/clients/deploy/DeployExistingInstance.java
  java/clients/src/main/java/sleeper/clients/util/cdk/CdkCommand.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/RedeployInstanceDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportIT.java
Labels: one-review-required

#1294 Issue 1291 - Remove `m4.large` from EMR instance types in system tests
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
Labels: one-review-required

#1296 Issue 955 - Update system tests documentation
  CHANGELOG.md
  README.md
  docs/09-dev-guide.md
  docs/12-performance-test.md
  docs/12-system-tests.md
Labels: pr-base-for-stacking

#1285 Issue 1179 - Update release process guide
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/02-deployment-guide.md
  docs/09-trino.md
  docs/10-deploy-to-localstack.md
  docs/11-dev-guide.md
  docs/12-design.md
  docs/13-system-tests.md
  docs/14-release-process.md
  docs/15-common-problems-and-their-solutions.md
  docs/16-roadmap.md
Labels: pr-base-for-stacking

#1301 Issue 1295 - Set nightly test name based on test type
  scripts/test/nightly/crontab.example
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#1299 Issue 1298 - Deploy data generation cluster if missing
  docs/13-system-tests.md
  java/clients/src/main/java/sleeper/clients/deploy/DeployExistingInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/pom.xml
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestStandaloneApp.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/OptionalStacksDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestDeploymentContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestParameters.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/sourcedata/SystemTestCluster.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestClients.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java
Labels: one-review-required

#1346 Issue 1345 - Make Docker containers use default `bridged` network mode
  docs/10-deploy-to-localstack.md
  scripts/cli/runInDocker.sh
  scripts/deploy/localstack/startContainer.sh
Labels: one-review-required

#1372 Issue 1371 - Upgrade snappy-java
  NOTICES
  java/pom.xml
Labels: one-review-required

#1362 Issue 1357 - Bulk import with S3 state store
  java/athena/src/main/java/sleeper/athena/metadata/SleeperMetadataHandler.java
  java/athena/src/test/java/sleeper/athena/TestUtils.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportSparkSessionRunner.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/SparkFileInfoRow.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
  java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/SleeperTableLambdaIT.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableStack.java
  java/clients/src/main/java/sleeper/clients/QueryClient.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceTestBase.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobsLambda.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/core/src/main/java/sleeper/core/key/KeySerDe.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileInfoStore.java
  java/core/src/test/java/sleeper/core/key/KeySerDeTest.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStore.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/parquet/src/main/java/sleeper/utils/HadoopConfigurationProvider.java
  java/pom.xml
  java/query/src/main/java/sleeper/query/executor/QueryExecutor.java
  java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java
  java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreProvider.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionUtils.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStoreCreator.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestParameters.java
  java/trino/src/test/java/sleeper/trino/testutils/PopulatedSleeperExternalResource.java
  scripts/test/nightly/runTests.sh
Labels: pr-base-for-stacking
