Repository gchq/sleeper, pull requests merged in 2023-04, with the labels that each got.

#740 Issue 718 - Avoid reloading properties in admin client
  java/clients/src/main/java/sleeper/clients/admin/AdminClientPropertiesStore.java
  java/clients/src/main/java/sleeper/clients/admin/AdminCommonPrompts.java
  java/clients/src/main/java/sleeper/clients/admin/CompactionStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/FilesStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/IngestStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/InstanceConfigurationScreen.java
  java/clients/src/main/java/sleeper/clients/admin/PartitionsStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/TableSelectHelper.java
  java/clients/src/test/java/sleeper/clients/admin/AdminClientPropertiesStoreIT.java
  java/clients/src/test/java/sleeper/clients/admin/AdminCommonPromptsTest.java
  java/clients/src/test/java/sleeper/clients/admin/FilesStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
  java/clients/src/test/java/sleeper/clients/admin/PartitionsStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/TableSelectHelperIT.java
  java/clients/src/test/java/sleeper/clients/admin/TableSelectHelperTest.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientMockStoreBase.java
Labels: one-review-required

#767 Issue 754 - Pre-authenticate build EC2
  java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/BuildEC2Stack.java
  scripts/utility/downloadConfig.sh
Labels: one-review-required

#768 Issue 752 - Clean up old log groups
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/status/update/CleanUpLogGroups.java
  java/clients/src/test/java/sleeper/ClientWiremockTestHelper.java
  java/clients/src/test/java/sleeper/status/update/CleanUpLogGroupsIT.java
  java/core/src/main/java/sleeper/core/util/RateLimitUtils.java
Labels: one-review-required

#766 Issue 765 - Add splitPointsFile parameter to deploy scripts
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/GenerateTableProperties.java
  java/system-test/src/main/java/sleeper/systemtest/cdk/DeployNewTestInstance.java
  scripts/deploy/deployNew.sh
  scripts/test/deploy.sh
  scripts/test/deployAll/deployTest.sh
Labels: pr-stacked-middle

#776 Issue 770 - Simplify compaction performance test by removing splitting compactions
  scripts/test/compactionPerformance/resumeTestAll.sh
  scripts/test/compactionPerformance/system-test-instance.properties
  scripts/test/compactionPerformance/testAll.sh
  scripts/test/compactionPerformance/testSplittingCompaction.sh
  scripts/test/compactionPerformance/waitForCurrentSplitAddingMissingJobs.sh
Labels: pr-base-for-stacking

#774 Issue 772 - Terminate EMR clusters before cdk teardown
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
  java/clients/src/main/java/sleeper/clients/teardown/TerminateEMRClusters.java
  java/clients/src/main/java/sleeper/util/PollWithRetries.java
  java/clients/src/test/java/sleeper/ClientWiremockTestHelper.java
  java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java
  java/clients/src/test/java/sleeper/utils/PollWithRetriesTest.java
  java/core/src/main/java/sleeper/core/util/RateLimitUtils.java
  java/system-test/src/main/java/sleeper/systemtest/compaction/WaitForCompactionJobs.java
  java/system-test/src/main/java/sleeper/systemtest/compaction/WaitForPartitionSplitting.java
  java/system-test/src/main/java/sleeper/systemtest/compaction/WaitForPartitionSplittingQueue.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/WaitForGenerateData.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/WaitForIngestTasks.java
  java/system-test/src/main/java/sleeper/systemtest/util/WaitForQueueEstimate.java
Labels: pr-logically-isolated

#773 Issue 771 - Use deployed queues in ingest reports
  java/clients/src/main/java/sleeper/status/report/IngestJobStatusReport.java
  java/clients/src/main/java/sleeper/status/report/ingest/job/IngestJobStatusReporter.java
  java/clients/src/main/java/sleeper/status/report/ingest/job/IngestQueueMessages.java
  java/clients/src/main/java/sleeper/status/report/ingest/job/JsonIngestJobStatusReporter.java
  java/clients/src/main/java/sleeper/status/report/ingest/job/StandardIngestJobStatusReporter.java
  java/clients/src/test/java/sleeper/clients/admin/IngestStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/status/report/ingest/job/IngestJobStatusReporterTestData.java
  java/clients/src/test/java/sleeper/status/report/ingest/job/IngestJobStatusReporterTestHelper.java
  java/clients/src/test/java/sleeper/status/report/ingest/job/IngestQueueMessagesTest.java
  java/clients/src/test/resources/reports/ingest/job/json/jobWithMultipleRuns.json
  java/clients/src/test/resources/reports/ingest/job/json/jobsWithLargeAndDecimalStatistics.json
  java/clients/src/test/resources/reports/ingest/job/json/mixedJobs.json
  java/clients/src/test/resources/reports/ingest/job/json/noJobs.json
  java/clients/src/test/resources/reports/ingest/job/standard/all/jobWithMultipleRuns.txt
  java/clients/src/test/resources/reports/ingest/job/standard/all/jobsWithLargeAndDecimalStatistics.txt
  java/clients/src/test/resources/reports/ingest/job/standard/all/mixedJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/all/noJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/range/mixedJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/range/noJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/range/unfinishedJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/unfinished/mixedUnfinishedJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/unfinished/noJobs.txt
  java/common-job/src/main/java/sleeper/job/common/QueueMessageCount.java
Labels: pr-base-for-stacking

#785 Issue 784 - Fix WaitForGenerateData excluding one task from checks
  java/system-test/src/main/java/sleeper/systemtest/ingest/WaitForGenerateData.java
Labels: one-review-required
