Repository gchq/sleeper, pull requests merged in 2023-10, with the labels that each got.

#1379 Issue 1352 - One S3 state store for all tables
  example/full/instance.properties
  example/full/table.properties
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBStateStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/S3StateStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/SystemDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTestHelper.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionUtils.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStoreCreator.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreMultipleTablesIT.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestApp.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#1380 Issue 1353 - Table metrics for all tables
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableStack.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/StateStoreTestBuilder.java
  java/metrics/pom.xml
  java/metrics/src/main/java/sleeper/metrics/TableMetrics.java
  java/metrics/src/main/java/sleeper/metrics/TableMetricsLambda.java
  java/metrics/src/test/java/sleeper/metrics/TableMetricsTest.java
  java/statestore/src/test/java/sleeper/statestore/FixedStateStoreProvider.java
Labels: pr-base-for-stacking

#1411 Issue 1409 - Create maven site zip for multiple tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestOutput.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/TestResult.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputFileSystemIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputS3IT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputTestHelper.java
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#1405 Issue 1373 - Purge SQS queues before ingest by queue system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/PurgeQueueDriver.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrServerlessBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonApiIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/PurgeQueueExtension.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/PurgeQueueExtensionTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/ReportingExtension.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/ReportingExtensionTest.java
Labels: one-review-required

#1429 Issue 1374 - Speed up assertions in ingest runner tests
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowRecordWriterAcceptingRecordListIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/TestFilesAndRecords.java
Labels: one-review-required

#1428 Issue 1426 - Validate instance ID is at most 20 characters
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/dataframe/WriteParquetFilesIT.java
  java/cdk/src/test/java/sleeper/cdk/UtilsTestHelper.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/CompactionStatusStoreTestUtils.java
  java/configuration/src/main/java/sleeper/configuration/Utils.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/configuration/src/test/java/sleeper/configuration/UtilsTest.java
  java/configuration/src/test/java/sleeper/configuration/jars/ObjectFactoryIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/IngestStatusStoreTestUtils.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestParameters.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/fixtures/SystemTestInstanceTest.java
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#1439 Issue 1433 - Add validation for ingest job having non-null files
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJob.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobValidationUtils.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerTest.java
Labels: pr-base-for-stacking

#1444 Issue 1443 - Handle reporting ingest job validation in one place
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/CheckLeafPartitionCount.java
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/job/BulkImportJob.java
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/job/BulkImportJobSerDe.java
  java/bulk-import/bulk-import-common/src/test/java/sleeper/bulkimport/job/BulkImportJobSerDeTest.java
  java/bulk-import/bulk-import-common/src/test/java/sleeper/bulkimport/job/BulkImportJobTest.java
  java/bulk-import/bulk-import-starter/pom.xml
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/BulkImportExecutor.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutorTest.java
  java/garbage-collector/pom.xml
  java/ingest/ingest-batcher-core/pom.xml
  java/ingest/ingest-batcher-job-creator/pom.xml
  java/ingest/ingest-batcher-submitter/pom.xml
  java/ingest/ingest-core/pom.xml
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJob.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobMessageHandler.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobValidationUtils.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/IngestJobTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobMessageHandler.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerTest.java
  java/ingest/ingest-status-store/pom.xml
  java/query/pom.xml
  java/splitter/pom.xml
  java/statestore/pom.xml
  java/tables/pom.xml
Labels: pr-base-for-stacking

#1447 Issue 1446 - Clean up deleted sleeper instances
  java/clients/src/main/java/sleeper/clients/deploy/DockerImageConfiguration.java
  java/clients/src/main/java/sleeper/clients/status/update/PauseSystem.java
  java/clients/src/main/java/sleeper/clients/teardown/CleanUpLogGroups.java
  java/clients/src/main/java/sleeper/clients/teardown/CloudFormationStacks.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownClients.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
  java/clients/src/test/java/sleeper/clients/teardown/CleanUpLogGroupsIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/CleanUpDeletedSleeperInstances.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/cdk/CleanUpDeletedSleeperInstancesTest.java
  scripts/dev/cleanupLogGroups.sh
Labels: pr-stacked-top

#1458 Issue 1445 - Validate queries in query executor
  java/clients/src/main/java/sleeper/clients/status/report/query/JsonQueryTrackerReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/query/StandardQueryTrackerReporter.java
  java/clients/src/test/java/sleeper/clients/status/report/query/QueryTrackerReporterTestHelper.java
  java/clients/src/test/java/sleeper/clients/status/report/query/StandardQueryTrackerReporterTest.java
  java/clients/src/test/resources/reports/query/json/mixedQueries.json
  java/clients/src/test/resources/reports/query/standard/all/mixedQueries.txt
  java/clients/src/test/resources/reports/query/standard/state/failedQueries.txt
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderTest.java
  java/core/src/main/java/sleeper/core/range/RegionSerDe.java
  java/query/src/main/java/sleeper/query/lambda/QueryMessageHandler.java
  java/query/src/main/java/sleeper/query/lambda/SqsQueryProcessorLambda.java
  java/query/src/main/java/sleeper/query/model/QueryJson.java
  java/query/src/main/java/sleeper/query/model/QuerySerDe.java
  java/query/src/main/java/sleeper/query/model/QueryValidationException.java
  java/query/src/main/java/sleeper/query/tracker/DynamoDBQueryTracker.java
  java/query/src/main/java/sleeper/query/tracker/DynamoDBQueryTrackerCreator.java
  java/query/src/main/java/sleeper/query/tracker/QueryStatusReportListeners.java
  java/query/src/main/java/sleeper/query/tracker/TrackedQuery.java
  java/query/src/test/java/sleeper/query/lambda/QueryMessageHandlerIT.java
  java/query/src/test/java/sleeper/query/model/QuerySerDeTest.java
  java/query/src/test/java/sleeper/query/tracker/DynamoDBQueryTrackerIT.java
  java/query/src/test/java/sleeper/query/tracker/TrackedQueryTestHelper.java
Labels: pr-base-for-stacking

#1464 Issue 1456 - Reference table by ID in state stores
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBStateStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/S3StateStoreStack.java
  java/clients/src/main/java/sleeper/clients/docker/DeployDockerInstance.java
  java/clients/src/main/java/sleeper/clients/docker/TearDownDockerInstance.java
  java/clients/src/main/java/sleeper/clients/docker/stack/TableDockerStack.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormat.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionFormat.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStoreCreator.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionUtils.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStoreCreator.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormatTest.java
Labels: pr-base-for-stacking

#1466 Issue 1457 - Use table ID in compaction jobs
  java/clients/src/main/java/sleeper/clients/admin/CompactionStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/IngestStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/status/report/CompactionJobStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/IngestJobStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/StatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/AllJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/JobQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/JobQueryPrompt.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/RangeJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/UnfinishedJobsQuery.java
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/status/report/job/query/JobQueryPromptTest.java
  java/clients/src/test/java/sleeper/clients/status/report/job/query/JobQueryTest.java
  java/clients/src/test/java/sleeper/clients/status/report/job/query/JobQueryTestBase.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJob.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobFactory.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobSerDe.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobTestDataHelper.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionJobStatusStoreInMemory.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionJobStatusStoreInMemoryTest.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/CompactionJobSerDeTest.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/CompactionJobTest.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/SizeRatioCompactionStrategyTest.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestBase.java
  java/compaction/compaction-status-store/pom.xml
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStoreCreatorIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryAllCompactionJobsIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByPeriodIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByTaskIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusUnfinishedIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusStoreCreatorIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/CompactionStatusStoreTestUtils.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionTaskStatusStoreTestBase.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/CompactionDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/CompactionReportsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestReportsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/util/WaitForJobsStatusTest.java
Labels: pr-stacked-middle

#1469 Issue 1461 - Use table ID in partition splitting
  java/splitter/src/main/java/sleeper/splitter/FindPartitionsToSplit.java
  java/splitter/src/main/java/sleeper/splitter/SplitPartitionJobCreator.java
  java/splitter/src/main/java/sleeper/splitter/SplitPartitionJobDefinition.java
  java/splitter/src/main/java/sleeper/splitter/SplitPartitionJobDefinitionSerDe.java
  java/splitter/src/main/java/sleeper/splitter/SplitPartitionLambda.java
  java/splitter/src/test/java/sleeper/splitter/FindPartitionsToSplitIT.java
  java/splitter/src/test/java/sleeper/splitter/SplitPartitionJobDefinitionSerDeTest.java
Labels: pr-base-for-stacking

#1472 Issue 1465 - Use table ID in ingest status store
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/job/BulkImportJob.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverTest.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/BulkImportExecutor.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrServerlessPlatformExecutor.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/BulkImportExecutorIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutorTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutorTest.java
  java/clients/src/main/java/sleeper/clients/docker/SendFilesToIngest.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/AllJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/RangeJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/UnfinishedJobsQuery.java
  java/clients/src/test/java/sleeper/clients/admin/IngestStatusReportScreenTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJob.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobMessageHandler.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobFinishedEvent.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStartedEvent.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusStore.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobValidatedEvent.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/IngestJobTestData.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/WriteToMemoryIngestJobStatusStore.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/WriteToMemoryIngestJobStatusStoreTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTask.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/ECSIngestTaskIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerIT.java
  java/ingest/ingest-status-store/pom.xml
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryAllIngestJobsIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryIngestJobStatusByPeriodIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryIngestJobStatusByTaskIdIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryIngestJobStatusUnfinishedIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobRunIdIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobValidatedIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/DynamoDBIngestJobStatusStoreTestBase.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/IngestStatusStoreTestUtils.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/util/WaitForJobsStatusTest.java
Labels: pr-base-for-stacking
