Repository gchq/sleeper, pull requests merged in 2023-03, with the labels that each got.

#641 Issue 290 - Use correct scope when performing Vpc lookup
  java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/BuildEC2Stack.java
Labels: one-review-required

#646 Issue 645 - Handle script changes in CLI upgrade
  scripts/cli/install.sh
  scripts/cli/runInDocker.sh
Labels: one-review-required

#654 Issue 651 - Stop download script clearing directory
  scripts/utility/downloadConfig.sh
Labels: one-review-required

#677 Issue 676 - Reorganise environment CLI scripts
  scripts/cli/environment/bin/environment
  scripts/cli/environment/scripts/subcommands/connect.sh
  scripts/cli/environment/scripts/subcommands/deploy.sh
  scripts/cli/environment/scripts/subcommands/destroy.sh
  scripts/cli/environment/scripts/subcommands/list.sh
  scripts/cli/environment/scripts/subcommands/scan-ssh.sh
  scripts/cli/environment/scripts/subcommands/set.sh
Labels: one-review-required

#679 Issue 665 - Log failures deleting image versions
  java/build/src/main/java/sleeper/build/github/api/containers/DeleteGHCRVersions.java
  java/build/src/test/java/sleeper/build/github/api/containers/DeleteGHCRVersionsTest.java
Labels: one-review-required

#683 Issue 681 - Handle multiple validation failures
  java/configuration/src/main/java/sleeper/configuration/properties/InstanceProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertiesInvalidException.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertiesValidationReporter.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/local/LoadLocalProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesValidationTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesSchemaTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java
  java/system-test/pom.xml
  java/system-test/src/main/java/sleeper/systemtest/SystemTestProperties.java
  java/system-test/src/main/java/sleeper/systemtest/SystemTestProperty.java
  java/system-test/src/main/java/sleeper/systemtest/SystemTestPropertyImpl.java
  java/system-test/src/test/java/sleeper/systemtest/SystemTestPropertiesTest.java
  java/system-test/src/test/java/sleeper/systemtest/SystemTestPropertyTest.java
Labels: one-review-required

#690 Issue 689 - Display notes for which properties are system-defined
  java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinter.java
  java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java
Labels: one-review-required

#678 Issue 674 - Build CLI images for ARM processors
  .github/scripts/planCliBuild.sh
  .github/workflows/docker-cli.yaml
  scripts/Dockerfile
  scripts/cli/builder/Dockerfile
  scripts/cli/environment/Dockerfile
Labels: one-review-required

#695 Issue 688 - Filter by property group in properties pretty printer
  java/configuration/src/main/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinter.java
  java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java
Labels: one-review-required

#696 Issue 581 - Refuse editing uneditable properties
  java/clients/src/main/java/sleeper/clients/admin/PropertiesDiff.java
  java/clients/src/main/java/sleeper/clients/admin/PropertyDiff.java
  java/clients/src/main/java/sleeper/clients/admin/UpdatePropertiesRequest.java
  java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
  java/clients/src/test/java/sleeper/clients/admin/AdminMainScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/FilesStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
  java/clients/src/test/java/sleeper/clients/admin/PartitionsStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/TableNamesReportTest.java
  java/clients/src/test/java/sleeper/clients/admin/TableSelectHelperIT.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientMockStoreBase.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientTestBase.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/RunAdminClient.java
  java/clients/src/test/java/sleeper/console/TestConsoleInput.java
  java/clients/src/test/java/sleeper/console/menu/ChooseOneTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstancePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
Labels: one-review-required, pr-stacked-top

#701 Issue 621 - View/edit properties by group in admin client
  java/clients/src/main/java/sleeper/clients/admin/AdminMainScreen.java
  java/clients/src/main/java/sleeper/clients/admin/InstanceConfigurationScreen.java
  java/clients/src/main/java/sleeper/clients/admin/PropertyGroupSelectHelper.java
  java/clients/src/main/java/sleeper/clients/admin/PropertyGroupWithCategory.java
  java/clients/src/main/java/sleeper/clients/admin/UpdatePropertiesWithNano.java
  java/clients/src/main/java/sleeper/console/menu/ChooseOne.java
  java/clients/src/main/java/sleeper/console/menu/Chosen.java
  java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
  java/clients/src/test/java/sleeper/clients/admin/UpdatePropertiesWithNanoTest.java
  java/clients/src/test/java/sleeper/clients/admin/UpdatePropertiesWithNanoTestHelper.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientMockStoreBase.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientTestBase.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminConfigStoreTestHarness.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/ExpectedAdminConsoleValues.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/RunAdminClient.java
  java/clients/src/test/java/sleeper/console/menu/ChooseOneTest.java
  java/clients/src/test/java/sleeper/console/menu/ChooseUntilChoiceFoundTest.java
  java/clients/src/test/java/sleeper/console/menu/ChooseUntilSomethingEnteredTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertyIndex.java
Labels: one-review-required

#724 Issue 721 - Refactor Arrow ingest test helpers
  java/core/src/main/java/sleeper/core/partition/PartitionTree.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilderTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordBatchFactory.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowRecordWriterAcceptingRecordListIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestTestHelper.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/ResultVerifier.java
Labels: pr-logically-isolated, one-review-required

#725 Issue 713 - Pass JobQuery into job status reports
  java/clients/src/main/java/sleeper/clients/admin/CompactionStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/IngestStatusReportScreen.java
  java/clients/src/main/java/sleeper/status/report/CompactionJobStatusReport.java
  java/clients/src/main/java/sleeper/status/report/IngestJobStatusReport.java
  java/clients/src/main/java/sleeper/status/report/StatusReport.java
  java/clients/src/main/java/sleeper/status/report/compaction/job/CompactionJobStatusReportArguments.java
  java/clients/src/main/java/sleeper/status/report/ingest/job/IngestJobStatusReportArguments.java
  java/clients/src/main/java/sleeper/status/report/job/query/JobQuery.java
  java/clients/src/test/java/sleeper/status/report/compaction/job/CompactionJobStatusReportArgumentsTest.java
  java/clients/src/test/java/sleeper/status/report/ingest/job/IngestJobStatusReportArgumentsTest.java
  java/clients/src/test/java/sleeper/status/report/query/JobQueryTestBase.java
Labels: pr-base-for-stacking, one-review-required

#726 Issue 716 - Add CDK flag to pause system at deploy time
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableStack.java
  java/clients/src/main/java/sleeper/clients/cdk/CdkCommand.java
  java/clients/src/main/java/sleeper/clients/cdk/CdkDeploy.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/clients/src/test/java/sleeper/clients/cdk/InvokeCdkForInstanceTest.java
  java/system-test/src/main/java/sleeper/systemtest/cdk/DeployNewTestInstance.java
  scripts/deploy/deployNew.sh
  scripts/test/compactionPerformance/deployTest.sh
  scripts/test/deploy.sh
  scripts/test/deployAll/deployTest.sh
Labels: pr-logically-isolated, one-review-required

#730 Issue 711 - Test fake for compaction job status store
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientStatusStoreHolderTest.java
  java/compaction/compaction-core/pom.xml
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTestData.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobTestDataHelper.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobTestUtils.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionJobStatusStoreInMemory.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionJobStatusStoreInMemoryTest.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/core/src/test/java/sleeper/core/schema/SchemaTestHelper.java
Labels: pr-stacked-middle

#735 Issue 734 - Wait for compaction jobs queue to update after creating jobs
  java/system-test/src/main/java/sleeper/systemtest/compaction/InvokeCompactionJobCreation.java
  java/system-test/src/main/java/sleeper/systemtest/compaction/WaitForCurrentSplitAddingMissingJobs.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/WaitForIngestTasks.java
  java/system-test/src/main/java/sleeper/systemtest/util/WaitForQueueEstimate.java
  java/system-test/src/main/java/sleeper/systemtest/util/WaitForQueueEstimateNotEmpty.java
Labels: one-review-required
