Repository gchq/sleeper, pull requests merged in 2023-06, with the labels that each got.

#878 Issue 851 - System test for ingest batcher
  .github/workflows/chunk-cdk.yaml
  java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
  java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambda.java
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/FileIngestRequestSerDe.java
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambda.java
  java/system-test/pom.xml
  java/system-test/src/main/java/sleeper/systemtest/ingest/WaitForIngestTasks.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/InvokeIngestBatcher.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/SendFilesToIngestBatcher.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/SystemTestForIngestBatcher.java
  scripts/test/ingestBatcher/buildDeployTest.sh
  scripts/test/ingestBatcher/deployTest.sh
  scripts/test/ingestBatcher/system-test-instance.properties
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#875 Issue 873 - Automate properties templates
  example/full/instance.properties
  example/full/table.properties
  java/clients/src/main/java/sleeper/clients/util/ComparePropertiesTemplates.java
  java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
  java/clients/src/test/java/sleeper/clients/status/partitions/ExportSplitPointsIT.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/configuration/pom.xml
  java/configuration/src/main/java/sleeper/configuration/Utils.java
  java/configuration/src/main/java/sleeper/configuration/properties/InstancePropertyGroup.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstancePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/format/GeneratePropertiesTemplates.java
  java/configuration/src/main/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinter.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyGroup.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
  java/configuration/src/test/java/sleeper/configuration/properties/format/GeneratePropertiesTemplatesTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStoreCreator.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  scripts/dev/generatePropertiesTemplates.sh
Labels: pr-base-for-stacking, one-review-required

#881 Issue 837 - OWASP dependency checks
  .github/workflows/dependency-check-changes.yaml
  .github/workflows/dependency-check-nightly.yaml
  .github/workflows/dependency-check.yaml
  code-style/dependency-check-suppressions.xml
  java/pom.xml
Labels: one-review-required

#879 Issue 853 - Use `RunECSTasks` in `RunWriteRandomDataTaskOnECS`
  java/common-job/src/main/java/sleeper/job/common/ECSFailureException.java
  java/common-job/src/main/java/sleeper/job/common/RunECSTasks.java
  java/common-job/src/test/java/sleeper/job/common/RunECSTasksIT.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/RunWriteRandomDataTaskOnECS.java
Labels: one-review-required

#880 Issue 874 - Set default value from default property in TableProperty
  java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java
Labels: one-review-required

#902 Issue 901 - Delete source bucket after ingest batcher system test
  java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/SystemTestForIngestBatcher.java
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#921 Issue 805 - Instance fleets for non-persistent EMR bulk import
  docs/05-ingest.md
  example/full/instance.properties
  example/full/table.properties
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/BulkImportPlatformSpec.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrExecutor.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceConfiguration.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceGroups.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrExecutorTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  scripts/templates/instanceproperties.template
Labels: pr-stacked-middle

#923 Issue 920 - Instance fleets for persistent EMR bulk import
  example/full/instance.properties
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/BulkImportPlatformSpec.java
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/EmrInstanceTypeConfig.java
  java/bulk-import/bulk-import-common/src/test/java/sleeper/bulkimport/configuration/EmrInstanceTypeConfigTest.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrExecutor.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceConfiguration.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceGroups.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrExecutorTest.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  scripts/templates/instanceproperties.template
Labels: pr-stacked-middle

#926 Issue 925 - Increase Lambda timeout for system tests
  java/system-test/src/main/java/sleeper/systemtest/compaction/SplitPartitionsUntilNoMoreSplits.java
  java/system-test/src/main/java/sleeper/systemtest/compaction/WaitForCurrentSplitAddingMissingJobs.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/SystemTestForIngestBatcher.java
  java/system-test/src/main/java/sleeper/systemtest/util/InvokeSystemTestLambda.java
Labels: pr-stacked-top

#919 Issue 918 - Split properties templating from deployment
  java/clients/src/main/java/sleeper/clients/deploy/DeployInstanceConfiguration.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/GenerateTableProperties.java
  java/clients/src/main/java/sleeper/clients/deploy/PopulateInstanceProperties.java
  java/clients/src/main/java/sleeper/clients/deploy/PopulateTableProperties.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
  java/clients/src/test/java/sleeper/clients/admin/PropertiesDiffTest.java
  java/clients/src/test/java/sleeper/clients/admin/UpdatePropertiesWithNanoTest.java
  java/clients/src/test/java/sleeper/clients/deploy/DeployInstanceConfigurationIT.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesIT.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesTest.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesTestHelper.java
  java/clients/src/test/java/sleeper/clients/deploy/SystemTestInstance.java
  java/system-test/src/main/java/sleeper/systemtest/cdk/DeployNewTestInstance.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/SystemTestForIngestBatcher.java
  scripts/deploy/deployNew.sh
Labels: pr-base-for-stacking

#914 Issue 850 - Tag system tests for cost explorer
  scripts/test/bulkImportPerformance/tags.properties
  scripts/test/compactionPerformance/tags.properties
  scripts/test/ingestBatcher/tags.properties
  scripts/test/partitionSplitting/tags.properties
Labels: pr-stacked-top

#680 Issue 620 - Make Bulk Import work with schema returning immutable lists
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportSparkSessionRunner.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/JdkImmutableListRegistrator.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/KryoSerializerTest.java
  java/core/src/main/java/sleeper/core/schema/Schema.java
Labels: pr-logically-isolated

#909 Issue 908 - Model for job run IDs
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTestData.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionJobStatusStoreInMemory.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionJobStatusStoreInMemoryTest.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobExpiryIT.java
  java/core/src/main/java/sleeper/core/record/process/status/ProcessRun.java
  java/core/src/main/java/sleeper/core/record/process/status/ProcessRuns.java
  java/core/src/main/java/sleeper/core/record/process/status/ProcessRunsBuilder.java
  java/core/src/main/java/sleeper/core/record/process/status/ProcessStatusUpdateRecord.java
  java/core/src/test/java/sleeper/core/record/process/status/ProcessRunsTest.java
  java/core/src/test/java/sleeper/core/record/process/status/ProcessStartedStatusWithStartOfRunFlag.java
  java/core/src/test/java/sleeper/core/record/process/status/TestProcessStatusUpdateRecords.java
  java/core/src/test/java/sleeper/core/record/process/status/TestRunStatusUpdates.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTestData.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/WriteToMemoryIngestJobStatusStore.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobExpiryIT.java
Labels: pr-base-for-stacking

#934 Issue 891 - Count files inside directories in bulk import jobs
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/job/BulkImportJob.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportSparkSessionRunner.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverTest.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarter.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/Executor.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/ExecutorFactory.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaIT.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/FileIngestRequestSerDe.java
  java/parquet/src/main/java/sleeper/utils/HadoopPathUtils.java
Labels: pr-base-for-stacking

#942 Issue 940 - Create and use ingest source bucket in relevant system tests
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/system-test/src/main/java/sleeper/systemtest/bulkimport/SendBulkImportJobs.java
  java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestApp.java
  java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestIngestBucketStack.java
  java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestStack.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/WriteRandomDataFiles.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/WriteRandomDataGenerateOnlyJob.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/WriteRandomDataViaQueueJob.java
Labels: pr-base-for-stacking

#945 Issue 944 - Raise socket read timeout for Lambda API HTTP client
  java/system-test/pom.xml
  java/system-test/src/main/java/sleeper/systemtest/util/InvokeSystemTestLambda.java
Labels: one-review-required
