Repository gchq/sleeper, pull requests merged in 2023-11, with the labels that each got.

#1490 Issue 1460 - Reference table by ID in subqueries
  java/clients/src/main/java/sleeper/clients/QueryCommandLineClient.java
  java/clients/src/main/java/sleeper/clients/QueryLambdaClient.java
  java/clients/src/main/java/sleeper/clients/status/report/DeadLettersStatusReport.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceTestBase.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderTest.java
  java/query/src/main/java/sleeper/query/executor/QueryExecutor.java
  java/query/src/main/java/sleeper/query/lambda/QueryMessageHandler.java
  java/query/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
  java/query/src/main/java/sleeper/query/lambda/WebSocketQueryProcessorLambda.java
  java/query/src/main/java/sleeper/query/model/LeafPartitionQuery.java
  java/query/src/main/java/sleeper/query/model/Query.java
  java/query/src/main/java/sleeper/query/model/QueryJson.java
  java/query/src/main/java/sleeper/query/model/QueryOrLeafPartitionQuery.java
  java/query/src/main/java/sleeper/query/model/QueryProcessingConfig.java
  java/query/src/main/java/sleeper/query/model/QuerySerDe.java
  java/query/src/main/java/sleeper/query/model/QueryValidationException.java
  java/query/src/main/java/sleeper/query/model/output/ResultsOutput.java
  java/query/src/main/java/sleeper/query/model/output/S3ResultsOutput.java
  java/query/src/main/java/sleeper/query/model/output/SQSResultsOutput.java
  java/query/src/main/java/sleeper/query/model/output/WebSocketOutput.java
  java/query/src/main/java/sleeper/query/model/output/WebSocketResultsOutput.java
  java/query/src/main/java/sleeper/query/recordretrieval/LeafPartitionQueryExecutor.java
  java/query/src/main/java/sleeper/query/tracker/DynamoDBQueryTracker.java
  java/query/src/main/java/sleeper/query/tracker/DynamoDBQueryTrackerCreator.java
  java/query/src/main/java/sleeper/query/tracker/DynamoDBQueryTrackerEntry.java
  java/query/src/main/java/sleeper/query/tracker/QueryStatusReportListener.java
  java/query/src/main/java/sleeper/query/tracker/QueryStatusReportListeners.java
  java/query/src/main/java/sleeper/query/tracker/TrackedQuery.java
  java/query/src/main/java/sleeper/query/tracker/WebSocketQueryStatusReportDestination.java
  java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java
  java/query/src/test/java/sleeper/query/lambda/QueryMessageHandlerIT.java
  java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/query/src/test/java/sleeper/query/model/LeafPartitionQueryTest.java
  java/query/src/test/java/sleeper/query/model/QuerySerDeTest.java
  java/query/src/test/java/sleeper/query/model/QueryTest.java
  java/query/src/test/java/sleeper/query/model/output/S3ResultsOutputIT.java
  java/query/src/test/java/sleeper/query/model/output/WebSocketResultsOutputIT.java
  java/query/src/test/java/sleeper/query/tracker/DynamoDBQueryTrackerIT.java
  java/query/src/test/java/sleeper/query/tracker/WebSocketQueryStatusReportDestinationIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/MultipleQueries.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/QueryCreator.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SQSQueryDriver.java
  java/trino/src/main/java/sleeper/trino/handle/SleeperSplit.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/SleeperConnectionAsTrino.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/SleeperRawAwsConnection.java
Labels: pr-stacked-top

#1497 Issue 1496 - Add IntelliJ inspection profile settings
  code-style/intellij-inspection-profile.xml
  docs/11-dev-guide.md
Labels: one-review-required

#1495 Issue 1468 - Index compaction job reporting status store by table
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBCompactionStatusStoreResources.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStoreCreator.java
  java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBRecordBuilder.java
  java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java
Labels: pr-base-for-stacking

#1502 Issue 1500 - Index ingest status stores by table
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBIngestStatusStoreResources.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusStore.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStoreCreator.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryInvalidIngestJobsIT.java
Labels: pr-base-for-stacking

#1503 Issue 1501 - Remove table name from ingest status store
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobMessageHandler.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobFinishedEvent.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStartedEvent.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobValidatedEvent.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
Labels: pr-stacked-top

#1507 Issue 1506 - Stop ingest job status store returning duplicate records
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/BulkImportExecutorIT.java
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBCompactionStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBIngestStatusStoreResources.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStoreCreator.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStoreCreatorIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
  java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBAttributes.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStoreCreator.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStoreCreatorIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryIngestJobStatusByIdIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryInvalidIngestJobsIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/DynamoDBIngestJobStatusStoreTestBase.java
Labels: pr-base-for-stacking

#1551 Issue 1546 - Clear system test instance when only config file is present
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriver.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriverIT.java
Labels: one-review-required

#1552 Issue 1547 - Wait for table index to empty in SleeperInstanceTablesDriver.deleteAll
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriver.java
Labels: one-review-required

#1564 Issue 1563 - Copy files in splitting compactions for tests
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJob.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobFactory.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/CompactionJobTest.java
  java/compaction/compaction-job-execution/pom.xml
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestBase.java
  java/configuration/src/main/java/sleeper/configuration/TableUtils.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileInfoStore.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
  java/core/src/test/java/sleeper/core/statestore/FileInfoFactory.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStore.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/AssertQuantiles.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
Labels: pr-base-for-stacking

#1572 Issue 1571 - Move RangeQueryUtils to parquet module, refactor for use in compaction
  java/athena/src/main/java/sleeper/athena/record/SleeperRecordHandler.java
  java/athena/src/test/java/sleeper/athena/metadata/AbstractMetadataHandlerIT.java
  java/athena/src/test/java/sleeper/athena/record/AbstractRecordHandlerIT.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaIT.java
  java/clients/src/main/java/sleeper/clients/QueryClient.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusReportIT.java
  java/clients/src/test/java/sleeper/clients/status/update/AddTableIT.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobsLambda.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsIT.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesDynamoDBIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorLambda.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/FileIngestRequestSerDe.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTask.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsLocalStackITBase.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrayListIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobQueueConsumerTestBase.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/parquet/src/main/java/sleeper/io/parquet/utils/HadoopConfigurationProvider.java
  java/parquet/src/main/java/sleeper/io/parquet/utils/HadoopPathUtils.java
  java/parquet/src/main/java/sleeper/io/parquet/utils/RangeQueryUtils.java
  java/parquet/src/test/java/sleeper/io/parquet/record/ParquetReaderIteratorIT.java
  java/parquet/src/test/java/sleeper/io/parquet/record/ParquetRecordReaderIT.java
  java/parquet/src/test/java/sleeper/io/parquet/record/ParquetRecordWriterFactoryIT.java
  java/parquet/src/test/java/sleeper/io/parquet/utils/HadoopConfigurationLocalStackUtils.java
  java/parquet/src/test/java/sleeper/io/parquet/utils/HadoopPathUtilsIT.java
  java/parquet/src/test/java/sleeper/io/parquet/utils/RangeQueryUtilsTest.java
  java/query/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
  java/query/src/main/java/sleeper/query/recordretrieval/LeafPartitionRecordRetrieverImpl.java
  java/query/src/main/java/sleeper/query/utils/RangeQueryUtils.java
  java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/splitter/src/main/java/sleeper/splitter/FindPartitionsToSplitLambda.java
  java/splitter/src/main/java/sleeper/splitter/SplitPartitionLambda.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriverIT.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/HadoopConfigurationProviderForDeployedS3Instance.java
Labels: pr-base-for-stacking

#1568 Issue 1567 - Improve logging and table properties loading for queries over many tables
  java/query/src/main/java/sleeper/query/model/QuerySerDe.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SQSQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SchemaLoaderFromInstanceContext.java
Labels: one-review-required

#1578 Issue 1577 - Only create managed policy if an ingest source bucket is set
  java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
Labels: one-review-required

#1584 Issue 1582 - Simplify FileInfoFactory by removing least used methods
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/StandardFileStatusReporterRecordCountTest.java
  java/clients/src/test/resources/reports/filestatus/json/leafAndMiddleFile.json
  java/clients/src/test/resources/reports/filestatus/standard/leafAndMiddleFile.txt
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobTestDataHelper.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsIT.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesDynamoDBIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesEmptyOutputIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesReportingIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestDataHelper.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryAllCompactionJobsIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByPeriodIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByTaskIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusUnfinishedIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobCreatedIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobExpiryIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/FileInfoFactory.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStoreTest.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrayListIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/ECSIngestTaskIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreMultipleTablesIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreMultipleTablesIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/FileInfoSystemTestHelper.java
Labels: one-review-required
