Repository gchq/sleeper, pull requests merged in 2023-05, with the labels that each got.

#839 Issue 825 - Ingest batcher logic
  java/configuration/src/main/java/sleeper/configuration/Utils.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/test/java/sleeper/configuration/UtilsTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/FixedTablePropertiesProvider.java
  java/ingest/ingest-batch-core/pom.xml
  java/ingest/ingest-batch-core/src/main/java/sleeper/ingest/batcher/FileIngestRequest.java
  java/ingest/ingest-batch-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
  java/ingest/ingest-batch-core/src/main/java/sleeper/ingest/batcher/IngestBatcherQueueClient.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherMaxBatchSizeTest.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherMinBatchSizeTest.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherTestBase.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherUpdateStoreTest.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/testutil/FileIngestRequestTestHelper.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/testutil/FileIngestRequestTestHelperTest.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherQueuesInMemory.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherQueuesInMemoryTest.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherStateStoreInMemory.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherStateStoreInMemoryTest.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherStateStoreKeyFields.java
Labels: pr-base-for-stacking

#842 Issue 841 - Ingest batcher maximum file age
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/ingest/ingest-batch-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherMinBatchSizeTest.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherTestBase.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/testutil/FileIngestRequestTestHelper.java
Labels: pr-stacked-middle

#843 Issue 840 - Batcher ingest modes
  java/ingest/ingest-batch-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
  java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherIngestModesTest.java
Labels: pr-stacked-top

#858 Issue 857 - Extract git update script from nightly test script
  scripts/test/nightly/runTests.sh
  scripts/test/nightly/updateAndRunTests.sh
Labels: one-review-required

#865 Issue 828 - Ingest batcher job creator Lambda
  .github/config/chunks.yaml
  .github/workflows/chunk-ingest-common.yaml
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/distribution/src/main/assembly/zip.xml
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/IngestBatcherMinBatchSizeTest.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/IngestBatcherTestBase.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherTestHelper.java
  java/ingest/ingest-batcher-job-creator/pom.xml
  java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambda.java
  java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/SQSIngestBatcherQueueClient.java
  java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaIT.java
  java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreCreator.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreTestBase.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobSerDe.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/IngestJobSerDeTest.java
  java/ingest/pom.xml
Labels: pr-stacked-middle

#866 Issue 848 - Ingest batcher CDK deployment
  .github/workflows/chunk-cdk.yaml
  java/cdk/pom.xml
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/jars/BuiltJar.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/clients/src/main/java/sleeper/clients/status/update/PauseSystem.java
  java/clients/src/main/java/sleeper/clients/status/update/RestartSystem.java
  java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/distribution/src/main/assembly/zip.xml
  java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestApp.java
  scripts/test/deployAll/system-test-instance.properties
Labels: pr-stacked-top
