Repository gchq/sleeper, pull requests merged in 2023-01, with the labels that each got.

#470 Issue 438 - Build on JDK 17 targeting Java 11
  .github/workflows/check-status.yaml
  .github/workflows/chunk.yaml
  .github/workflows/maven-full.yaml
  java/bulk-import/bulk-import-runner/docker/Dockerfile
  java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PropertiesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/VpcStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/AbstractEmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/clients/src/main/java/sleeper/status/report/StatusReport.java
  java/clients/src/main/java/sleeper/status/report/job/StandardProcessRunReporter.java
  java/clients/src/main/java/sleeper/status/report/partitions/PartitionsStatusReportArguments.java
  java/clients/src/test/java/sleeper/status/report/job/FormatDurationStringTest.java
  java/compaction/compaction-job-execution/docker/Dockerfile
  java/ingest/ingest-runner/docker/Dockerfile
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryIngestJobStatusByPeriodIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryIngestJobStatusByTaskIdIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobStartedIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/DynamoDBIngestJobStatusStoreTestBase.java
  java/pom.xml
  java/query/src/main/java/sleeper/query/model/output/WebSocketResultsOutput.java
  java/system-test/docker/Dockerfile
  java/system-test/src/main/java/sleeper/systemtest/ingest/TaskStatusJson.java
Labels: pr-base-for-stacking

#475 Issue 472 - Upgrade AWS EMR, Spark and Hadoop
  .github/workflows/docker-bulk-import.yaml
  docs/05-ingest.md
  docs/08-python-api.md
  example/full/instance.properties
  example/full/table.properties
  java/bulk-import/bulk-import-runner/docker/Dockerfile
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/pom.xml
Labels: pr-base-for-stacking

#484 Issue 467 - Upgrade Maven dependencies
  java/build/pom.xml
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/ExecutorFactory.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/ExecutorFactoryIT.java
  java/pom.xml
Labels: pr-base-for-stacking

#511 Issue 496 - Update Maven version numbers in NOTICES
  NOTICES
Labels: one-review-required

#517 Issue 516 - Fix reference to CDK jar in deploy/tearDown.sh
  scripts/deploy/tearDown.sh
Labels: pr-logically-isolated, one-review-required

#519 Issue 518 - Fix script reference in scripts/test/deployAll/buildDeployTest.sh
  scripts/test/deployAll/buildDeployTest.sh
Labels: one-review-required

#515 Issue #514 - Update IllegalImports to use JUnit5 imports
  code-style/checkstyle-idea/checkstyle.xml
  code-style/checkstyle.xml
Labels: pr-logically-isolated, one-review-required

#497 Issue 440 - Local Docker image to deploy & connect to cdk-environment
  .gitignore
  docs/01-getting-started.md
  docs/02-deployment-guide.md
  java/cdk-environment/pom.xml
  java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/BuildEC2Stack.java
  java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/KeyPairUtil.java
  java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/LoadUserDataUtil.java
  java/cdk-environment/src/main/java/sleeper/environment/cdk/networking/NetworkingStack.java
  java/cdk-environment/src/main/resources/cloud-init.sh
  java/cdk-environment/src/main/resources/user_data
  scripts/.dockerignore
  scripts/local/.dockerignore
  scripts/local/Dockerfile
  scripts/local/bin/environment
  scripts/local/build.sh
  scripts/local/buildDocker.sh
  scripts/local/cdk.json
  scripts/local/runInDocker.sh
  scripts/local/scripts/environment/connect.sh
  scripts/local/scripts/environment/deploy.sh
  scripts/local/scripts/environment/destroy.sh
  scripts/local/scripts/environment/scan-ssh.sh
  scripts/local/scripts/environment/set.sh
  scripts/local/scripts/util/configure-aws.sh
Labels: pr-base-for-stacking, one-review-required

#510 Issue 508 - Store deployment Docker image in GitHub Container Registry
  .github/workflows/docker-deployment.yaml
  scripts/Dockerfile
  scripts/build/build.sh
  scripts/build/buildForTest.sh
Labels: one-review-required, pr-stacked-top

#526 442 run tasks should include pending
  java/common-job/src/main/java/sleeper/job/common/CommonJobUtils.java
  java/common-job/src/main/java/sleeper/job/common/DescribeClusterException.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/RunTasks.java
  java/ingest/ingest-starter/src/main/java/sleeper/ingest/starter/RunTasks.java
Labels: one-review-required

#554 Issue 553 - Add toString to Sleeper property implementations
  java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstancePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstancePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
  java/system-test/src/main/java/sleeper/systemtest/SystemTestPropertyImpl.java
Labels: one-review-required

#557 534 release 0.14
  CHANGELOG.md
  docs/09-dev-guide.md
  docs/12-performance-test.md
  example/basic/instance.properties
  example/full/instance.properties
  java/athena/pom.xml
  java/build/pom.xml
  java/bulk-import/bulk-import-common/pom.xml
  java/bulk-import/bulk-import-runner/pom.xml
  java/bulk-import/bulk-import-starter/pom.xml
  java/bulk-import/pom.xml
  java/cdk-custom-resources/pom.xml
  java/cdk-environment/pom.xml
  java/cdk/pom.xml
  java/clients/pom.xml
  java/common-job/pom.xml
  java/compaction/compaction-core/pom.xml
  java/compaction/compaction-job-creation/pom.xml
  java/compaction/compaction-job-execution/pom.xml
  java/compaction/compaction-status-store/pom.xml
  java/compaction/pom.xml
  java/configuration/pom.xml
  java/core/pom.xml
  java/distribution/pom.xml
  java/dynamodb-tools/pom.xml
  java/garbage-collector/pom.xml
  java/ingest/ingest-core/pom.xml
  java/ingest/ingest-runner/pom.xml
  java/ingest/ingest-starter/pom.xml
  java/ingest/ingest-status-store/pom.xml
  java/ingest/pom.xml
  java/metrics/pom.xml
  java/parquet/pom.xml
  java/pom.xml
  java/query/pom.xml
  java/sketches/pom.xml
  java/splitter/pom.xml
  java/statestore/pom.xml
  java/system-test/pom.xml
  java/tables/pom.xml
  python/setup.py
Labels: one-review-required

#540 Issue 332 - Display property descriptions in admin client
  java/clients/src/main/java/sleeper/clients/admin/InstancePropertyReport.java
  java/clients/src/main/java/sleeper/clients/admin/TablePropertyReport.java
  java/clients/src/main/java/sleeper/util/ClientUtils.java
  java/clients/src/test/java/sleeper/clients/admin/InstancePropertyReportTest.java
  java/clients/src/test/java/sleeper/clients/admin/TablePropertyReportTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstancePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstancePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java
  java/system-test/src/main/java/sleeper/systemtest/SystemTestProperty.java
  java/system-test/src/main/java/sleeper/systemtest/SystemTestPropertyImpl.java
Labels: one-review-required

#556 Issue 548 - Paginate DynamoDB Scan results in Compaction and Ingest stores
  java/clients/src/main/java/sleeper/status/update/ReinitialiseTable.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusStore.java
  java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java
  java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBRecordBuilderTest.java
  java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBTableTestBase.java
  java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsPagingIT.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/task/DynamoDBIngestTaskStatusFormat.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/task/DynamoDBIngestTaskStatusStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java
Labels: one-review-required
