Repository gchq/sleeper, pull requests merged in 2023-02, with the labels that each got.

#566 Issue 512 - Wait for jars bucket to exist after creating it
  scripts/deploy/uploadJars.sh
Labels: one-review-required

#559 Issue 558 - Update system test documentation
  docs/01-getting-started.md
  docs/02-deployment-guide.md
  docs/09-dev-guide.md
  docs/10-design.md
  docs/12-performance-test.md
Labels: one-review-required

#570 Issue 267 - Remove properties that set absolute local paths
  docs/02-deployment-guide.md
  example/basic/instance.properties
  example/basic/table.properties
  example/full/instance.properties
  example/full/table.properties
  java/athena/src/test/java/sleeper/athena/TestUtils.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobRunnerIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/dataframe/WriteParquetFilesTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/ExecutorFactoryIT.java
  java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/PropertiesWriterLambdaIT.java
  java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/SleeperTableLambdaIT.java
  java/cdk/pom.xml
  java/cdk/src/main/java/sleeper/cdk/ConfigValidator.java
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableStack.java
  java/cdk/src/test/java/sleeper/cdk/ConfigValidatorIT.java
  java/cdk/src/test/java/sleeper/cdk/UtilsInstancePropertiesTest.java
  java/cdk/src/test/java/sleeper/cdk/UtilsTablePropertiesTest.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientTestBase.java
  java/clients/src/test/java/sleeper/status/update/ReinitialiseTableIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/InstanceProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesSchemaTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTestHelper.java
  java/core/src/main/java/sleeper/core/schema/Schema.java
  java/core/src/main/java/sleeper/core/schema/SchemaSerDe.java
  java/core/src/test/java/sleeper/core/schema/SchemaSerDeTest.java
  java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestApp.java
  scripts/deploy/connectToTable.sh
  scripts/deploy/pre-deployment.sh
  scripts/templates/instanceproperties.template
  scripts/templates/tableproperties.template
  scripts/test/compactionPerformance/system-test-instance.properties
  scripts/test/deploy.sh
  scripts/test/deployAll/system-test-instance.properties
  scripts/test/tearDown.sh
Labels: pr-base-for-stacking

#574 Issue 289 - Split validation for new instance and configuration in CDK
  docs/02-deployment-guide.md
  java/cdk/src/main/java/sleeper/cdk/ConfigValidator.java
  java/cdk/src/main/java/sleeper/cdk/NewInstanceValidator.java
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/test/java/sleeper/cdk/ConfigValidatorTest.java
  java/cdk/src/test/java/sleeper/cdk/NewInstanceValidatorIT.java
  java/cdk/src/test/java/sleeper/cdk/ValidatorTestHelper.java
  scripts/deploy/deploy.sh
  scripts/deploy/tearDown.sh
  scripts/test/deploy.sh
  scripts/test/tearDown.sh
Labels: pr-stacked-top

#569 Issue 564 - Automatically line wrap property descriptions in admin client reports
  java/clients/src/main/java/sleeper/util/ClientUtils.java
  java/clients/src/test/java/sleeper/clients/admin/InstancePropertyReportTest.java
  java/clients/src/test/java/sleeper/clients/admin/TablePropertyReportTest.java
  java/clients/src/test/java/sleeper/utils/ClientUtilsTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/system-test/src/main/java/sleeper/systemtest/SystemTestProperty.java
Labels: one-review-required

#316 Issue 132 - Infrastructure to run compactions on EC2
  code-style/checkstyle.xml
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/cdk/src/test/java/sleeper/cdk/UtilsNormaliseSizeTest.java
  java/common-job/pom.xml
  java/common-job/src/main/java/sleeper/job/common/CommonJobUtils.java
  java/compaction/compaction-job-execution/pom.xml
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/InstanceDetails.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/RunTasks.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/RunTasksLambda.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/SafeTerminationLambda.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/Scaler.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/SafeTerminationTest.java
  java/configuration/src/main/java/sleeper/configuration/Requirements.java
  java/configuration/src/main/java/sleeper/configuration/Utils.java
  java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTest.java
  java/core/src/main/java/sleeper/core/partition/PartitionSerDe.java
  java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestStack.java
  scripts/build/build.sh
  scripts/templates/instanceproperties.template
  scripts/test/deployAll/system-test-instance.properties
Labels: compactions-module, cdk-module

#579 Issue 3 - Stop ECS clusters during tear down scripts
  java/clients/src/main/java/sleeper/status/update/CleanUpBeforeDestroy.java
  java/clients/src/main/java/sleeper/status/update/PauseSystem.java
  java/clients/src/main/java/sleeper/util/RateLimitUtils.java
  java/clients/src/test/java/sleeper/utils/RateLimitUtilsTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/local/LoadLocalProperties.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/RunWriteRandomDataTaskOnECS.java
  java/system-test/src/main/java/sleeper/systemtest/util/CleanUpTestBeforeDestroy.java
  scripts/deploy/tearDown.sh
  scripts/test/tearDown.sh
Labels: one-review-required, pr-stacked-top

#587 Issue 521 - Model which properties should trigger a CDK deploy
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableStack.java
  java/clients/src/test/java/sleeper/clients/admin/InstancePropertyReportTest.java
  java/clients/src/test/java/sleeper/clients/admin/TablePropertyReportTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstancePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstancePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyInvalidException.java
  java/configuration/src/test/java/sleeper/configuration/properties/DummySleeperProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertyGroupingTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/DummyTableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java
  java/system-test/src/main/java/sleeper/systemtest/SystemTestProperties.java
  java/system-test/src/main/java/sleeper/systemtest/SystemTestProperty.java
  java/system-test/src/main/java/sleeper/systemtest/SystemTestPropertyImpl.java
  java/system-test/src/test/java/sleeper/systemtest/SystemTestPropertyTest.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#591 Issue 590 - Fix split field display on partitions report
  java/clients/src/main/java/sleeper/status/report/partitions/PartitionStatus.java
  java/clients/src/test/java/sleeper/status/report/partitions/PartitionStatusReportTestHelper.java
  java/clients/src/test/java/sleeper/status/report/partitions/PartitionsStatusReportIT.java
  java/clients/src/test/java/sleeper/status/report/partitions/PartitionsStatusReportTest.java
  java/clients/src/test/java/sleeper/status/report/partitions/PartitionsStatusTest.java
  java/clients/src/test/resources/reports/partitions/rootWithNestedChildrenSplitOnDifferentFields.txt
  java/core/src/main/java/sleeper/core/partition/PartitionsFromSplitPoints.java
  java/core/src/main/java/sleeper/core/range/Region.java
  java/core/src/test/java/sleeper/core/partition/PartitionFactory.java
  java/core/src/test/java/sleeper/core/partition/PartitionFactoryTest.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilderTest.java
Labels: one-review-required

#598 Issue 597 - Run CDK deploy from Java
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/admin/deploy/CdkDeployInstance.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/GenerateInstanceProperties.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/GenerateTableProperties.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/JarsDiff.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/PreDeployInstance.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/SyncJars.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/UploadDockerImages.java
  java/clients/src/main/java/sleeper/util/ClientUtils.java
  java/clients/src/test/java/sleeper/clients/admin/deploy/GeneratePropertiesIT.java
  java/clients/src/test/java/sleeper/clients/admin/deploy/SyncJarsIT.java
  java/clients/src/test/java/sleeper/clients/admin/deploy/SystemTestInstance.java
  java/clients/src/test/java/sleeper/clients/admin/deploy/SystemTestInstanceIT.java
  java/clients/src/test/java/sleeper/utils/ClientUtilsTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/local/SaveLocalProperties.java
  java/configuration/src/test/java/sleeper/configuration/jars/ObjectFactoryIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/local/SaveLocalPropertiesTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTestHelper.java
  java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBRecordBuilderIT.java
  java/pom.xml
Labels: one-review-required

#601 Issue 292 - Deploy with CDK when properties change
  code-style/checkstyle.xml
  java/cdk/src/test/java/sleeper/cdk/UtilsNormaliseSizeTest.java
  java/clients/src/main/java/sleeper/clients/AdminClient.java
  java/clients/src/main/java/sleeper/clients/admin/AdminConfigStore.java
  java/clients/src/main/java/sleeper/status/update/DownloadConfig.java
  java/clients/src/main/java/sleeper/util/ClientUtils.java
  java/clients/src/main/resources/log4j.properties
  java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
  java/clients/src/test/java/sleeper/clients/admin/AdminConfigStoreIT.java
  java/clients/src/test/java/sleeper/clients/admin/deploy/GeneratePropertiesIT.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
  java/clients/src/test/java/sleeper/utils/ClientUtilsTest.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/InstanceDetails.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/SafeTerminationLambda.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/Scaler.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/SafeTerminationTest.java
  java/configuration/src/main/java/sleeper/configuration/Requirements.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/local/SaveLocalProperties.java
  java/configuration/src/test/java/sleeper/configuration/properties/local/SaveLocalPropertiesIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/local/SaveLocalPropertiesTest.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/AwsExternalResource.java
  java/system-test/src/main/java/sleeper/systemtest/compaction/InvokeCompactionJobCreation.java
  java/system-test/src/main/java/sleeper/systemtest/compaction/InvokeCompactionTaskCreation.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/InvokeIngestTaskCreation.java
  java/system-test/src/main/resources/log4j.properties
  scripts/utility/adminClient.sh
Labels: one-review-required

#600 Issue 599 - Replace deploy scripts code with Java
  java/clients/src/main/java/sleeper/clients/admin/deploy/DeployNewInstance.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/GenerateInstanceProperties.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/PreDeployInstance.java
  java/system-test/src/main/java/sleeper/systemtest/cdk/DeployNewTestInstance.java
  scripts/deploy/deploy.sh
  scripts/deploy/pre-deployment.sh
  scripts/deploy/uploadJars.sh
  scripts/test/deploy.sh
Labels: one-review-required

#589 Issue 577 - Display table property groupings in admin client
  java/clients/src/main/java/sleeper/clients/admin/InstancePropertyReport.java
  java/clients/src/main/java/sleeper/clients/admin/TablePropertyReport.java
  java/clients/src/main/java/sleeper/util/ClientUtils.java
  java/clients/src/test/java/sleeper/clients/admin/TablePropertyReportTest.java
  java/clients/src/test/java/sleeper/utils/ClientUtilsTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/InstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/InstancePropertyGroup.java
  java/configuration/src/main/java/sleeper/configuration/properties/PropertyGroup.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyGroup.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
  java/configuration/src/test/java/sleeper/configuration/properties/DummySleeperProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/DummyTableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertyGroupingTest.java
Labels: one-review-required

#595 Issue 594 - Suppress exceptions thrown by property validationPredicates
  java/clients/src/test/java/sleeper/clients/admin/UpdatePropertyTest.java
  java/configuration/src/main/java/sleeper/configuration/Utils.java
  java/configuration/src/test/java/sleeper/configuration/UtilsTest.java
Labels: one-review-required

#615 Issue 613 - Add flag for CDK update, validate version matches on CDK update
  java/cdk/src/main/java/sleeper/cdk/MismatchedVersionException.java
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/test/java/sleeper/cdk/UtilsPropertiesTest.java
  java/cdk/src/test/java/sleeper/cdk/UtilsTestHelper.java
  java/cdk/src/test/java/sleeper/cdk/UtilsVersionTest.java
Labels: pr-stacked-top

#633 Issue 632 - Fix Sleeper version used to upload Docker images
  java/cdk/pom.xml
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/test/java/sleeper/cdk/UtilsPropertiesTest.java
  java/cdk/src/test/java/sleeper/cdk/UtilsVersionTest.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/DeployNewInstance.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/PreDeployInstance.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/SyncJars.java
  java/clients/src/main/java/sleeper/clients/admin/deploy/UploadDockerImages.java
  java/clients/src/test/java/sleeper/clients/admin/deploy/SystemTestInstance.java
  java/core/pom.xml
  java/core/src/main/java/sleeper/core/SleeperVersion.java
  java/core/src/main/resources/version.txt
  java/core/src/test/java/sleeper/core/SleeperVersionTest.java
Labels: one-review-required
