Repository gchq/sleeper, pull requests merged in 2023-07, with the labels that each got.

#948 Issue 804 - Add support for Graviton instance types in bulk import EMR
  docs/05-ingest.md
  docs/08-python-api.md
  example/full/instance.properties
  example/full/table.properties
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/ConfigurationUtils.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrExecutor.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceGroups.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrExecutorTest.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#969 Issue 960 - Set number of bulk import jobs to be started at once
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
Labels: one-review-required

#973 Issue 965 - Connect to deployed environment without redeploy
  docs/01-getting-started.md
  java/cdk-environment/pom.xml
  java/cdk-environment/src/main/java/sleeper/environment/cdk/GetStackOutputs.java
  java/cdk-environment/src/main/java/sleeper/environment/cdk/outputs/StackOutputs.java
  java/cdk-environment/src/main/java/sleeper/environment/cdk/util/CdkFailedException.java
  java/cdk-environment/src/main/java/sleeper/environment/cdk/util/ListEnvironmentStacks.java
  java/cdk-environment/src/test/java/sleeper/environment/cdk/outputs/StackOutputsIT.java
  java/cdk-environment/src/test/java/sleeper/environment/cdk/outputs/StackOutputsTest.java
  java/cdk-environment/src/test/java/sleeper/environment/cdk/testutil/EnvironmentWiremockTestHelper.java
  java/cdk-environment/src/test/java/sleeper/environment/cdk/util/ListEnvironmentStacksIT.java
  scripts/cli/environment/scripts/subcommands/add.sh
Labels: one-review-required

#957 Issue 820 - Report invalid JSON and invalid models to ingest job status store
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaTestHelper.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJob.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobValidationUtils.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobRejectedStatus.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusStore.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobValidatedEvent.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTestData.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/WriteToMemoryIngestJobStatusStore.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/WriteToMemoryIngestJobStatusStoreTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTask.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobMessageHandler.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerTest.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryInvalidIngestJobsIT.java
Labels: pr-base-for-stacking, one-review-required

#976 Issue 975 - Raise queue visibility timeout for bulk import starter Lambda
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
Labels: one-review-required

#980 Always use IngestJobStatusStoreFactory to build DynamoDBIngestJobStatusStore
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/BulkImportExecutorIT.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/IngestJobStatusStoreFactory.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/DynamoDBIngestJobStatusStoreTestBase.java
  java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/InvokeIngestBatcher.java
Labels: one-review-required

#991 Issue 977 - Don't wait for system test cluster when configuration is deleted
  java/system-test/src/main/java/sleeper/systemtest/cdk/TearDownTestInstance.java
Labels: one-review-required

#1001 Issue 1000 - Use "Resolves" in PR description to link to relevant issue
  .github/pull_request_template.md
Labels: one-review-required

#997 Issue 995 - Only push images to base repository
  .github/workflows/docker-cli-main.yaml
Labels: one-review-required

#1005 Issue 1004 - Fix minimum arguments in DeployNewInstance
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
Labels: one-review-required

#1010 Issue 970 - Escape non-readable characters in PS1 variable
  scripts/Dockerfile
  scripts/cli/builder/Dockerfile
  scripts/cli/environment/Dockerfile
Labels: one-review-required

#1016 Issue 1011 - Split CLI build workflow
  .github/scripts/planCliBuild.sh
  .github/workflows/docker-cli-branch.yaml
  .github/workflows/docker-cli-image.yaml
  .github/workflows/docker-cli.yaml
Labels: one-review-required

#1022 Issue 1013 - Resolve deprecation warnings for containers in tests
  java/athena/src/test/java/sleeper/athena/metadata/AbstractMetadataHandlerIT.java
  java/athena/src/test/java/sleeper/athena/record/AbstractRecordHandlerIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/BulkImportExecutorIT.java
  java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/PropertiesWriterLambdaIT.java
  java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/SleeperTableLambdaIT.java
  java/cdk/src/test/java/sleeper/cdk/NewInstanceValidatorIT.java
  java/cdk/src/test/java/sleeper/cdk/jars/BuiltJarsIT.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesIT.java
  java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusReportIT.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/common-job/src/test/java/sleeper/job/common/QueueMessageCountIT.java
  java/common-job/src/test/java/sleeper/job/common/action/ChangeMessageVisibilityTimeoutActionIT.java
  java/common-job/src/test/java/sleeper/job/common/action/DeleteMessageActionIT.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/CompactionJobSerDeIT.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesDynamoDBIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/configuration/src/test/java/sleeper/configuration/jars/ObjectFactoryIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/local/SaveLocalPropertiesIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesS3TestBase.java
  java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBTestBase.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaIT.java
  java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsDynamoDBITBase.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/AwsExternalResource.java
  java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java
  java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/query/src/test/java/sleeper/query/tracker/DynamoDBQueryTrackerIT.java
  java/splitter/src/test/java/sleeper/splitter/FindPartitionsToSplitIT.java
  java/splitter/src/test/java/sleeper/splitter/SplitPartitionIT.java
  java/statestore/src/test/java/sleeper/statestore/InitialiseStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  java/system-test/src/test/java/sleeper/systemtest/nightly/NightlyTestOutputS3IT.java
  java/tables/src/test/java/sleeper/table/job/TableCreatorIT.java
  java/tables/src/test/java/sleeper/table/job/TableInitialiserIT.java
  java/trino/src/test/java/sleeper/trino/testutils/HadoopConfigurationProviderForLocalStack.java
  java/trino/src/test/java/sleeper/trino/testutils/PopulatedSleeperExternalResource.java
Labels: one-review-required

#1023 Issue 1020 - Stop Docker CLI build running out of disk space
  .github/workflows/docker-cli-image.yaml
Labels: one-review-required

#1025 Issue 1024 - Extract helpers to initialise AWS clients
  java/athena/pom.xml
  java/athena/src/test/java/sleeper/athena/metadata/AbstractMetadataHandlerIT.java
  java/athena/src/test/java/sleeper/athena/record/AbstractRecordHandlerIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/BulkImportExecutorIT.java
  java/cdk-custom-resources/pom.xml
  java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/PropertiesWriterLambdaIT.java
  java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/SleeperTableLambdaIT.java
  java/cdk/src/test/java/sleeper/cdk/NewInstanceValidatorIT.java
  java/cdk/src/test/java/sleeper/cdk/jars/BuiltJarsIT.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
  java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusReportIT.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/common-job/pom.xml
  java/common-job/src/test/java/sleeper/job/common/QueueMessageCountIT.java
  java/common-job/src/test/java/sleeper/job/common/action/ChangeMessageVisibilityTimeoutActionIT.java
  java/common-job/src/test/java/sleeper/job/common/action/DeleteMessageActionIT.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/CompactionJobSerDeIT.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsIT.java
  java/compaction/compaction-job-execution/pom.xml
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesDynamoDBIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/configuration/src/test/java/sleeper/configuration/jars/ObjectFactoryIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/local/SaveLocalPropertiesIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesS3TestBase.java
  java/configuration/src/test/java/sleeper/configuration/testutils/LocalStackAwsV1ClientHelper.java
  java/dynamodb-tools/pom.xml
  java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBTestBase.java
  java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/GenericContainerAwsV1ClientHelper.java
  java/garbage-collector/pom.xml
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaIT.java
  java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaIT.java
  java/ingest/ingest-runner/pom.xml
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsDynamoDBITBase.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/AwsExternalResource.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/LocalStackAwsV2ClientHelper.java
  java/query/pom.xml
  java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java
  java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/query/src/test/java/sleeper/query/tracker/DynamoDBQueryTrackerIT.java
  java/splitter/pom.xml
  java/splitter/src/test/java/sleeper/splitter/FindPartitionsToSplitIT.java
  java/splitter/src/test/java/sleeper/splitter/SplitPartitionIT.java
  java/statestore/pom.xml
  java/statestore/src/test/java/sleeper/statestore/InitialiseStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  java/system-test/src/test/java/sleeper/systemtest/nightly/NightlyTestOutputS3IT.java
  java/tables/pom.xml
  java/tables/src/test/java/sleeper/table/job/TableCreatorIT.java
  java/tables/src/test/java/sleeper/table/job/TableInitialiserIT.java
  java/trino/pom.xml
  java/trino/src/test/java/sleeper/trino/testutils/PopulatedSleeperExternalResource.java
Labels: one-review-required

#1027 Issue 1021 - Manage version of Okio
  java/pom.xml
Labels: one-review-required

#1029 Issue 1028 - Use CDK parameters when only one is given
  scripts/cli/environment/scripts/subcommands/deploy.sh
Labels: one-review-required

#1041 Issue 1040 - Use CDK parameters when only one is given for destroy
  scripts/cli/environment/scripts/subcommands/destroy.sh
Labels: one-review-required

#1048 Issue 1047 - Use on.pull_request instead of on.push
  .github/workflows/check-status.yaml
  .github/workflows/chunk-athena.yaml
  .github/workflows/chunk-bulk-import.yaml
  .github/workflows/chunk-cdk.yaml
  .github/workflows/chunk-clients.yaml
  .github/workflows/chunk-common.yaml
  .github/workflows/chunk-compaction.yaml
  .github/workflows/chunk-data.yaml
  .github/workflows/chunk-ingest-common.yaml
  .github/workflows/chunk-ingest-runner.yaml
  .github/workflows/chunk-query.yaml
  .github/workflows/chunk-statestore.yaml
  .github/workflows/chunk-trino.yaml
  .github/workflows/dependency-check-changes.yaml
  .github/workflows/docker-bulk-import.yaml
  .github/workflows/docker-cli-branch.yaml
  .github/workflows/maven-full.yaml
  .github/workflows/scripts.yaml
  java/build/src/main/java/sleeper/build/chunks/ProjectChunks.java
  java/build/src/main/java/sleeper/build/github/actions/ExpectedWorkflowTriggerPaths.java
  java/build/src/main/java/sleeper/build/github/actions/GitHubActionsChunkWorkflow.java
  java/build/src/main/java/sleeper/build/github/actions/GitHubActionsChunkWorkflowYaml.java
  java/build/src/main/java/sleeper/build/github/actions/WorkflowTriggerPathsDiff.java
  java/build/src/test/java/sleeper/build/github/actions/GitHubActionsChunkWorkflowValidatePathsTest.java
  java/build/src/test/java/sleeper/build/github/actions/OnPushPathsDiffTestHelper.java
  java/build/src/test/java/sleeper/build/github/actions/TestGitHubActionsChunkWorkflows.java
  java/build/src/test/java/sleeper/build/github/actions/WorkflowTriggerPathsDiffExtraEntriesTest.java
  java/build/src/test/java/sleeper/build/github/actions/WorkflowTriggerPathsDiffTest.java
  java/build/src/test/resources/examples/github-actions/chunk-bulk-import.yaml
  java/build/src/test/resources/examples/github-actions/chunk-common.yaml
  java/build/src/test/resources/examples/github-actions/chunk-ingest.yaml
  java/build/src/test/resources/examples/github-actions/corner-cases/chunk-extra-input.yaml
  java/build/src/test/resources/examples/github-actions/corner-cases/chunk-extra-job-first.yaml
  java/build/src/test/resources/examples/github-actions/corner-cases/chunk-extra-job.yaml
Labels: one-review-required

#1064 Issue 1063 - Property to force reload lambdas
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobsLambda.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/PropertiesReloader.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
  java/configuration/src/test/java/sleeper/configuration/properties/PropertiesReloaderIT.java
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambda.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTask.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/query/src/main/java/sleeper/query/lambda/SqsQueryProcessorLambda.java
  java/splitter/src/main/java/sleeper/splitter/SplitPartitionLambda.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
Labels: pr-base-for-stacking

#978 971 add vscode configuration file
  .gitignore
  .vscode/README.md
  .vscode/settings.json
Labels: one-review-required

#1094 Issue 1093 - Resolve vulnerabilities in Avro & OkHttp
  code-style/dependency-check-suppressions.xml
  java/pom.xml
Labels: one-review-required
