Repository gchq/sleeper, pull requests merged in 2023-08, with the labels that each got.

#1095 Issue 1082 - vscode settings file causes issues if not using Corretto or if Java 11 is not installed
  .vscode/README.md
  .vscode/settings.json
Labels: bug

#1112 Issue 1111 - Report Maven test exit code
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/TestResult.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputFileSystemIT.java
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#1100 Issue 1099 - Aggregate maven HTML reports in GitHub actions
  .github/config/chunks.yaml
  .github/workflows/chunk.yaml
  java/build/src/main/java/sleeper/build/github/actions/ExpectedWorkflowTriggerPaths.java
  java/build/src/main/java/sleeper/build/maven/MavenModuleStructure.java
  java/pom.xml
Labels: one-review-required

#1123 Revert "Issue 929 - Force consistent reads in IngestBatcher integration tests"
  java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaIT.java
  java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStore.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreTestBase.java
Labels: one-review-required

#958 92 investigate running bulk import jobs using emr serverless
  .github/workflows/chunk-cdk.yaml
  .github/workflows/docker-bulk-import.yaml
  example/basic/instance.properties
  example/full/instance.properties
  java/bulk-import/bulk-import-runner/docker/eks/Dockerfile
  java/bulk-import/bulk-import-runner/docker/eks/build/build-hadoop.sh
  java/bulk-import/bulk-import-runner/docker/eks/build/extract-native-libs.sh
  java/bulk-import/bulk-import-runner/docker/emr-serverless/Dockerfile
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/dataframelocalsort/BulkImportDataframeLocalSortDriver.java
  java/bulk-import/bulk-import-starter/pom.xml
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrServerlessPlatformExecutor.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PlatformExecutor.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrServerlessPlatformExecutorIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/testutil/TestResources.java
  java/bulk-import/bulk-import-starter/src/test/resources/example/emr-serverless/jobrun-request.json
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
  java/clients/src/main/java/sleeper/clients/deploy/PopulateInstanceProperties.java
  java/clients/src/main/java/sleeper/clients/teardown/RemoveECRRepositories.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesIT.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/format/GeneratePropertiesTemplates.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/EMRServerlessProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/SystemDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/UserDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/distribution/src/main/assembly/zip.xml
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/FileIngestRequestSerDe.java
  java/system-test/system-test-drivers/pom.xml
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/DirectEmrServerlessDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestByQueueDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestSourceFilesContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/WaitForIngestJobsDriver.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestClients.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestDirectEmrServerless.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestIngest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestIngestBatcher.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestIngestByQueue.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestSourceFiles.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/BulkImportIT.java
  scripts/deploy/uploadDockerImages.sh
  scripts/templates/instanceproperties.template
  scripts/test/maven/buildDeployTest.sh
Labels: enhancement

#1128 Issue 1127 - Allow same weight for multiple instance types
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/configuration/src/main/java/sleeper/configuration/Utils.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/NonPersistentEMRProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/PersistentEMRProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/validation/EmrInstanceTypeConfig.java
  java/configuration/src/test/java/sleeper/configuration/UtilsTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/validation/EmrInstanceTypeConfigTest.java
Labels: one-review-required

#1132 Issue 983 - Release 0.18.0
  docs/12-performance-test.md
  java/athena/pom.xml
  java/build/pom.xml
  java/bulk-import/bulk-import-common/pom.xml
  java/bulk-import/bulk-import-runner/pom.xml
  java/bulk-import/bulk-import-starter/pom.xml
  java/bulk-import/pom.xml
  java/cdk-custom-resources/pom.xml
  java/cdk-environment/pom.xml
  java/cdk/pom.xml
  java/clients/pom.xml
  java/common-job/pom.xml
  java/compaction/compaction-core/pom.xml
  java/compaction/compaction-job-creation/pom.xml
  java/compaction/compaction-job-execution/pom.xml
  java/compaction/compaction-status-store/pom.xml
  java/compaction/pom.xml
  java/configuration/pom.xml
  java/core/pom.xml
  java/distribution/pom.xml
  java/dynamodb-tools/pom.xml
  java/garbage-collector/pom.xml
  java/ingest/ingest-batcher-core/pom.xml
  java/ingest/ingest-batcher-job-creator/pom.xml
  java/ingest/ingest-batcher-store/pom.xml
  java/ingest/ingest-batcher-submitter/pom.xml
  java/ingest/ingest-core/pom.xml
  java/ingest/ingest-runner/pom.xml
  java/ingest/ingest-starter/pom.xml
  java/ingest/ingest-status-store/pom.xml
  java/ingest/pom.xml
  java/metrics/pom.xml
  java/parquet/pom.xml
  java/pom.xml
  java/query/pom.xml
  java/sketches/pom.xml
  java/splitter/pom.xml
  java/statestore/pom.xml
  java/system-test/pom.xml
  java/system-test/system-test-cdk/pom.xml
  java/system-test/system-test-configuration/pom.xml
  java/system-test/system-test-data-generation/pom.xml
  java/system-test/system-test-drivers/pom.xml
  java/system-test/system-test-suite/pom.xml
  java/tables/pom.xml
  java/trino/pom.xml
  python/setup.py
Labels: pr-stacked-top

#1122 Issue 1120 - Handle file count exceeding transaction limit in DynamoDBIngestBatcherStoreIT
  java/dynamodb-tools/pom.xml
  java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBWiremockTestHelper.java
  java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
  java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcherStore.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/IngestBatcherUpdateStoreTest.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherStoreInMemory.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherStoreInMemoryTest.java
  java/ingest/ingest-batcher-store/pom.xml
  java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStore.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreWiremockIT.java
Labels: one-review-required

#1144 Issue 929 - Improve reliability of DynamoDB batcher store tests
  java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStore.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreTestBase.java
Labels: one-review-required

#1089 Issue 343 - Deploy on Docker and Localstack
  docs/15-deploy-to-localstack.md
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/AdminClient.java
  java/clients/src/main/java/sleeper/clients/deploy/PopulateTableProperties.java
  java/clients/src/main/java/sleeper/clients/docker/DeployDockerInstance.java
  java/clients/src/main/java/sleeper/clients/docker/TearDownDockerInstance.java
  java/clients/src/main/java/sleeper/clients/docker/Utils.java
  java/clients/src/main/java/sleeper/clients/docker/stack/ConfigurationDockerStack.java
  java/clients/src/main/java/sleeper/clients/docker/stack/DockerStack.java
  java/clients/src/main/java/sleeper/clients/docker/stack/TableDockerStack.java
  java/clients/src/main/java/sleeper/clients/status/report/FilesStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/PartitionsStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/update/DownloadConfig.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesIT.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesTest.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
  java/configuration/src/main/java/sleeper/configuration/utils/AwsV1ClientHelper.java
  scripts/deploy/localstack/deploy.sh
  scripts/deploy/localstack/docker-compose.yml
  scripts/deploy/localstack/startContainer.sh
  scripts/deploy/localstack/stopContainer.sh
  scripts/deploy/localstack/tearDown.sh
Labels: pr-base-for-stacking

#1148 Issue 1118 - Stop retrying deploying system test instance
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/InstanceDidNotDeployException.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
Labels: one-review-required

#1149 Issue 998 - Remove SystemTestInstanceIT in favour of new system test suite
  java/clients/src/test/java/sleeper/clients/deploy/SystemTestInstance.java
  java/clients/src/test/java/sleeper/clients/deploy/SystemTestInstanceIT.java
  java/pom.xml
Labels: one-review-required

#1090 Issue 1046 - Run standard ingest in Docker and Localstack
  docs/15-deploy-to-localstack.md
  java/clients/src/main/java/sleeper/clients/docker/DeployDockerInstance.java
  java/clients/src/main/java/sleeper/clients/docker/SendFilesToIngest.java
  java/clients/src/main/java/sleeper/clients/docker/TearDownDockerInstance.java
  java/clients/src/main/java/sleeper/clients/docker/stack/IngestDockerStack.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceTestBase.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/SendFilesToIngestIT.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriterFactory.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTask.java
  java/parquet/src/main/java/sleeper/utils/HadoopConfigurationProvider.java
  scripts/deploy/localstack/buildDockerImages.sh
  scripts/deploy/localstack/ingestFiles.sh
Labels: pr-base-for-stacking

#1164 Issue 1163 - Only build Maven site if tests failed
  .github/workflows/chunk.yaml
Labels: one-review-required

#1150 Issue 1076 - Upload Maven HTML reports in nightly tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestOutput.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputS3IT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputTestHelper.java
  scripts/cli/builder/Dockerfile
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#1165 Issue 1160 - Include running processes in reports by period
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskStatus.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusInPeriodTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskStatusInPeriodTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionTaskStatusStoreInMemoryTest.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByPeriodIT.java
  java/core/src/main/java/sleeper/core/record/process/status/TimeWindowQuery.java
  java/core/src/test/java/sleeper/core/record/process/status/TimeWindowQueryTest.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatus.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/task/IngestTaskStatus.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusInPeriodTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskStatusInPeriodTest.java
Labels: one-review-required

#1156 Issue 1151 - Run random data generation in Docker and LocalStack
  docs/15-deploy-to-localstack.md
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateRandomDataFiles.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
  scripts/deploy/localstack/generateRandomData.sh
  scripts/deploy/localstack/ingestRandomData.sh
Labels: pr-base-for-stacking, one-review-required

#1157 Issue 1155 - Run queries in Docker and LocalStack
  docs/15-deploy-to-localstack.md
  java/clients/src/main/java/sleeper/clients/QueryClient.java
  java/parquet/src/main/java/sleeper/utils/HadoopConfigurationProvider.java
Labels: one-review-required, pr-stacked-top

#1172 Issue 1097 - Document updating NOTICES.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/09-dev-guide.md
Labels: one-review-required

#1158 Issue 1134 - Exclude runs with rate of NaN from average rate calculation
  java/core/src/main/java/sleeper/core/record/process/AverageRecordRate.java
  java/core/src/test/java/sleeper/core/record/process/AverageRecordRateTest.java
Labels: one-review-required

#1180 Issue 992 - Improve developer guide
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/09-dev-guide.md
  shell.nix
Labels: one-review-required

#1174 Issue 999 - Partition splitting system test in JUnit
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/SplitPartitionsUntilNoMoreSplits.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/SplittingCompactionDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/partitioning/PartitionSplittingDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/partitioning/WaitForPartitionSplitting.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/partitioning/WaitForPartitionSplittingTest.java
  java/system-test/system-test-suite/pom.xml
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestCompaction.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestDirectIngest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestIngest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestPartitionSplitting.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestStateStore.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/FileInfoSystemTestHelper.java
Labels: one-review-required

#1178 1125 EMR Serverless applications fails to be destroyed via cdk if the application is started
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
  java/clients/src/main/java/sleeper/clients/teardown/TerminateEMRServerlessApplications.java
  java/clients/src/main/java/sleeper/clients/util/EmrServerlessUtils.java
  java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java
  java/clients/src/test/java/sleeper/clients/testutil/ClientWiremockTestHelper.java
  java/clients/src/test/java/sleeper/clients/testutil/WiremockEMRTestHelper.java
Labels: bug, one-review-required

#1181 Added documentation for EMR Serverless
  docs/05-ingest.md
Labels: documentation

#1182 Issue 1177 - Use Python dev version in `updateVersionNumber.sh`
  python/setup.py
  scripts/dev/updateVersionNumber.sh
Labels: one-review-required

#1189 Issue 1167 - Control job assignment batch size for tests meeting and exceeding it
  java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStore.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreTestBase.java
Labels: one-review-required

#1186 Issue 1175 - Partition splitting status report
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestReportsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/ReportingContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestReport.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/partitioning/PartitionReportDriver.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestIngest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestIngestReporting.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestReporting.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
Labels: pr-base-for-stacking, one-review-required

#1187 Issue 1176 - Remove scripts/test/partitionSplitting
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/SplitPartitionsUntilNoMoreSplits.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/WaitForCurrentSplitAddingMissingJobs.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/compaction/WaitForCurrentSplitAddingMissingJobsTest.java
  scripts/test/common/waitForCompaction.sh
  scripts/test/compactionPerformance/resumeTestAll.sh
  scripts/test/compactionPerformance/testAll.sh
  scripts/test/compactionPerformance/testCompaction.sh
  scripts/test/compactionPerformance/testIngest.sh
  scripts/test/compactionPerformance/waitForIngest.sh
  scripts/test/nightly/runTests.sh
  scripts/test/partitionSplitting/buildDeployTest.sh
  scripts/test/partitionSplitting/deployTest.sh
  scripts/test/partitionSplitting/resumeTestAll.sh
  scripts/test/partitionSplitting/system-test-instance.properties
  scripts/test/partitionSplitting/tags.properties
  scripts/test/partitionSplitting/testAll.sh
  scripts/test/partitionSplitting/testSplittingCompaction.sh
  scripts/test/partitionSplitting/waitForCurrentSplitAddingMissingJobs.sh
Labels: one-review-required, pr-stacked-middle

#1190 Issue 1077 - Remove hard coded teardown for Maven system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/OutputInstanceIds.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestParameters.java
  scripts/functions/systemTestUtils.sh
  scripts/functions/test/testSystemTestUtils.sh
  scripts/test/nightly/runTests.sh
Labels: one-review-required, pr-stacked-middle
