Repository gchq/sleeper, pull requests merged in 2024-06, with the labels that each got.

#2627 Issue 2622 - Show reasons a job run failed
  java/clients/src/main/java/sleeper/clients/status/report/job/StandardProcessRunReporter.java
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/IngestJobStatusReporterTestData.java
  java/clients/src/test/resources/reports/compaction/job/standard/detailed/mixedJobs.txt
  java/clients/src/test/resources/reports/ingest/job/json/mixedJobs.json
  java/clients/src/test/resources/reports/ingest/job/standard/detailed/mixedJobs.txt
Labels: one-review-required, pr-stacked-top

#2633 Issue 2620 - Report compaction jobs finished when any run finished
  java/clients/src/main/java/sleeper/clients/status/report/compaction/job/StandardCompactionJobStatusReporter.java
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterAllQueryTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterDetailedQueryTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterTestBase.java
  java/clients/src/test/resources/reports/compaction/job/json/jobWithMultipleRuns.json
  java/clients/src/test/resources/reports/compaction/job/json/mixedUnfinishedJobs.json
  java/clients/src/test/resources/reports/compaction/job/standard/all/jobWithMultipleRuns.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/jobsWithLargeAndDecimalStatistics.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/multipleInputFiles.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/noJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/detailed/jobWithMultipleRuns.txt
  java/clients/src/test/resources/reports/compaction/job/standard/unfinished/mixedUnfinishedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/unfinished/noJobs.txt
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobRunTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTest.java
  java/core/src/main/java/sleeper/core/record/process/status/ProcessRuns.java
  java/core/src/test/java/sleeper/core/record/process/status/ProcessRunsRecordsOutOfOrderTest.java
  java/core/src/test/java/sleeper/core/record/process/status/ProcessRunsTest.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatus.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/reporting/JobsFinishedStatistics.java
Labels: pr-base-for-stacking, one-review-required

#2635 Issue 2621 - Report ingest jobs finished when any run finished
  java/clients/src/main/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporter.java
  java/clients/src/test/java/sleeper/clients/admin/IngestStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/IngestJobStatusReporterTestData.java
  java/clients/src/test/resources/reports/ingest/job/standard/all/bulkImport/acceptedJob.txt
  java/clients/src/test/resources/reports/ingest/job/standard/all/bulkImport/rejectedJob.txt
  java/clients/src/test/resources/reports/ingest/job/standard/all/jobWithMultipleRuns.txt
  java/clients/src/test/resources/reports/ingest/job/standard/all/jobsWithLargeAndDecimalStatistics.txt
  java/clients/src/test/resources/reports/ingest/job/standard/all/mixedJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/all/noJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/all/noJobsWithEmrStepsUnfinished.txt
  java/clients/src/test/resources/reports/ingest/job/standard/range/unfinishedJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/unfinished/mixedUnfinishedJobs.txt
  java/clients/src/test/resources/reports/ingest/job/standard/unfinished/noJobs.txt
  java/core/src/main/java/sleeper/core/record/process/AverageRecordRate.java
  java/core/src/main/java/sleeper/core/record/process/status/ProcessRun.java
  java/core/src/test/java/sleeper/core/record/process/AverageRecordRateTest.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatus.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusStore.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusType.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/reporting/JobsFinishedStatistics.java
Labels: one-review-required, pr-stacked-top

#2656 Issue 2644 - Rename compaction job committer lambda
  .github/config/chunks.yaml
  .github/workflows/chunk-compaction.yaml
  java/cdk/src/main/java/sleeper/cdk/jars/BuiltJar.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/compaction/pom.xml
  java/distribution/src/main/assembly/zip.xml
  java/pom.xml
  java/statestore-commit-lambda/pom.xml
  java/statestore-commit-lambda/src/main/java/sleeper/committer/lambda/StateStoreCommitterLambda.java
Labels: pr-base-for-stacking

#2657 Issue 2643 - Split state store commit lambda out of compaction stack
  .github/config/chunks.yaml
  .github/workflows/chunk-compaction.yaml
  .github/workflows/chunk-statestore.yaml
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStatusStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreUpdateStack.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionJobCommitterOrSendToLambda.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#2665 Issue 2664 - Rename statestore-lambda module
  .github/config/chunks.yaml
  .github/workflows/chunk-statestore.yaml
  java/cdk/src/main/java/sleeper/cdk/jars/BuiltJar.java
  java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogSnapshotStack.java
  java/distribution/src/main/assembly/zip.xml
  java/pom.xml
  java/statestore-snapshot-lambda/pom.xml
  java/statestore-snapshot-lambda/src/main/java/sleeper/statestore/TransactionLogSnapshotCreationLambda.java
  java/statestore-snapshot-lambda/src/main/java/sleeper/statestore/TransactionLogSnapshotCreationTriggerLambda.java
  java/statestore-snapshot-lambda/src/main/java/sleeper/statestore/TransactionLogSnapshotDeletionLambda.java
  java/statestore-snapshot-lambda/src/main/java/sleeper/statestore/TransactionLogSnapshotDeletionTriggerLambda.java
Labels: pr-stacked-middle

#2666 Issue 2645 - Support ingest commits in state store commit request
  .github/workflows/chunk-statestore.yaml
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitRequestSerDe.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitRequestSerDeTest.java
  java/ingest/ingest-core/pom.xml
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequest.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequestSerDe.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequestSerDeTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequestSerDeTest.shouldSerialiseIngestJobCommitRequest.approved.txt
  java/statestore-commit-lambda/pom.xml
  java/statestore-commit/pom.xml
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitRequest.java
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitRequestDeserialiser.java
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitRequestJson.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitRequestDeserialiserTest.java
Labels: pr-base-for-stacking

#2697 Issue 2696 - Helper to get state store by table ID
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitter.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionJobCommitterOrSendToLambda.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTestBase.java
  java/core/src/main/java/sleeper/core/statestore/GetStateStoreByTableId.java
  java/statestore-commit-lambda/src/main/java/sleeper/committer/lambda/StateStoreCommitterLambda.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreProvider.java
Labels: one-review-required

#2712 Issue 2646 - Option to commit ingest asynchronously in standard ingest tasks
  example/full/instance.properties
  example/full/table.properties
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngestCoordinator.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/commit/AddFilesToStateStore.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  scripts/templates/instanceproperties.template
Labels: pr-stacked-top

#2719 Issue 2694 - Report bulk import failure in driver
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverTest.java
Labels: pr-stacked-top

#2722 Issue 2659 - Change message for validate chunks error
  java/build/src/main/java/sleeper/build/chunks/ProjectChunks.java
  java/build/src/main/java/sleeper/build/chunks/ProjectChunksValidationException.java
  java/build/src/main/java/sleeper/build/chunks/ValidateProjectChunks.java
  java/build/src/main/java/sleeper/build/github/actions/WorkflowTriggerPathsDiff.java
  java/build/src/test/java/sleeper/build/chunks/ProjectChunksValidateModulesInChunksTest.java
Labels: one-review-required

#2728 Issue 2727 - Handle status updates before start of run
  java/core/src/main/java/sleeper/core/record/process/status/ProcessRunsBuilder.java
  java/core/src/test/java/sleeper/core/record/process/status/ProcessRunsTest.java
Labels: pr-base-for-stacking, one-review-required

#2730 Issue 2729 - Model ingest add files status update
  java/core/src/test/java/sleeper/core/statestore/AllReferencesToAFileTestHelper.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobAddedFilesEvent.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobAddedFilesStatus.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStartedEvent.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusStore.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStore.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStoreTest.java
Labels: one-review-required, pr-stacked-middle

#2732 Issue 2731 - Model ingest status to commit when all files are added
  java/clients/src/main/java/sleeper/clients/status/report/compaction/job/JsonCompactionJobStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/ingest/job/JsonIngestJobStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/job/JsonProcessRunReporter.java
  java/clients/src/test/resources/reports/compaction/job/json/jobWithMultipleRuns.json
  java/clients/src/test/resources/reports/compaction/job/json/jobsWithLargeAndDecimalStatistics.json
  java/clients/src/test/resources/reports/compaction/job/json/mixedJobs.json
  java/clients/src/test/resources/reports/compaction/job/json/mixedUnfinishedJobs.json
  java/clients/src/test/resources/reports/ingest/job/json/bulkImport/acceptedJob.json
  java/clients/src/test/resources/reports/ingest/job/json/bulkImport/acceptedJobWhichStarted.json
  java/clients/src/test/resources/reports/ingest/job/json/bulkImport/rejectedJob.json
  java/clients/src/test/resources/reports/ingest/job/json/jobWithMultipleRuns.json
  java/clients/src/test/resources/reports/ingest/job/json/jobsWithLargeAndDecimalStatistics.json
  java/clients/src/test/resources/reports/ingest/job/json/mixedJobs.json
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobFinishedEvent.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobFinishedStatus.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatus.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusType.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobUpdateType.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStore.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStoreTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusInPeriodTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTestHelper.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/util/WaitForJobsStatusTest.java
Labels: pr-base-for-stacking, one-review-required

#2735 Issue 2723 - Store ingest add files status updates in DynamoDB
  java/common/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBAttributes.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusInPeriodTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTestHelper.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobRunIdIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobUpdatesIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/DynamoDBIngestJobStatusStoreTestBase.java
Labels: one-review-required, pr-stacked-middle

#2736 Issue 2724 - Set job run ID in IngestTask
  java/ingest/ingest-core/src/main/java/sleeper/ingest/task/IngestTask.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java
Labels: pr-base-for-stacking, one-review-required

#2737 Issue 2725 - Add files status updates in standard ingest
  .github/workflows/chunk-statestore.yaml
  java/core/src/main/java/sleeper/core/statestore/AllReferencesToAFile.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/AllReferencesToAFileTestHelper.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobHandler.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequest.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobFinishedEvent.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/task/IngestTask.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequestSerDeTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequestSerDeTest.shouldSerialiseIngestJobCommitRequest.approved.txt
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTestHelper.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/commit/AddFilesToStateStore.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/statestore-commit-lambda/pom.xml
  java/statestore-commit-lambda/src/main/java/sleeper/committer/lambda/StateStoreCommitterLambda.java
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitter.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitRequestDeserialiserTest.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java
Labels: one-review-required, pr-stacked-middle

#2754 Issue 2425 - Handle Hadoop configuration in system test clients
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/DirectQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SQSQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/sourcedata/AwsIngestSourceFilesDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/ReadRecordsFromS3.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
Labels: one-review-required

#2760 Issue 2759 - Set missing access flags in compact files scripts
  scripts/utility/compactAllFiles.sh
  scripts/utility/compactFiles.sh
Labels: one-review-required

#2753 Issue 2752 - Logic to delete old transactions
  example/full/instance.properties
  example/full/table.properties
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreSnapshotsTest.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotCreator.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotMetadataStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoSnapshots.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/LatestSnapshots.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshotMetadata.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogTransactionDeleter.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotMetadataStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/InMemoryTransactionLogSnapshotMetadataStore.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotCreatorIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotDeleterIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreOneTableTestBase.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreSnapshotsIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogTransactionDeleterTest.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#2748 Issue 2640 - Delete old transactions from DynamoDB/S3
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
Labels: pr-stacked-middle

#2756 Issue 2755 - Find latest snapshots with min age
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotMetadataStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshotDeleter.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogTransactionDeleter.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotMetadataStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogTransactionDeleterTest.java
Labels: pr-stacked-top

#2770 Issue 2769 - Fix permissions for async state store commits
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStatusStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBCompactionStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBIngestStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStatusStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreCommitterStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
Labels: pr-base-for-stacking
