Repository gchq/sleeper, pull requests merged in 2024-11, with the labels that each got.

#3593 Issue 3592 - Don't overwrite settings on build EC2 startup
  docs/02-deployment-guide.md
  java/cdk-environment/src/main/resources/cloud-init.sh
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#3588 Issue 3587 - Create package for transaction log snapshots code
  java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogStateStoreStack.java
  java/clients/src/test/java/sleeper/clients/status/update/DeleteTableIT.java
  java/statestore-lambda/src/main/java/sleeper/statestore/snapshot/TransactionLogSnapshotCreationLambda.java
  java/statestore-lambda/src/main/java/sleeper/statestore/snapshot/TransactionLogSnapshotDeletionLambda.java
  java/statestore-lambda/src/main/java/sleeper/statestore/transaction/TransactionLogTransactionDeletionLambda.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogStateStoreCreator.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogTransactionDeleter.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotCreator.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStoreCreator.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/LatestSnapshots.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/SnapshotType.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotDeleter.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotMetadata.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotSerDe.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreOneTableTestBase.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotStoreBasePathTest.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/InMemoryTransactionLogSnapshotMetadataStore.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotCreatorIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotDeleterIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotSerDeIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotTestBase.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogTransactionDeleterTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsSnapshotsDriver.java
Labels: pr-base-for-stacking, one-review-required

#3594 Issue 3550 - Allow no writers in deployAll system test
  java/common/common-task/src/main/java/sleeper/task/common/RunECSTasks.java
  java/common/common-task/src/test/java/sleeper/task/common/RunECSTasksIT.java
  java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
Labels: one-review-required

#3614 Issue 3613 - Move PopulateInstanceProperties to core module
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/PopulateInstancePropertiesAws.java
  java/clients/src/main/java/sleeper/clients/docker/DeployDockerInstance.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
  java/clients/src/test/java/sleeper/clients/admin/properties/PropertiesDiffTest.java
  java/clients/src/test/java/sleeper/clients/admin/properties/UpdatePropertiesWithTextEditorIT.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulateInstancePropertiesAwsIT.java
  java/core/src/main/java/sleeper/core/deploy/DeployInstanceConfiguration.java
  java/core/src/main/java/sleeper/core/deploy/PopulateInstanceProperties.java
  java/core/src/test/java/sleeper/core/deploy/PopulateInstancePropertiesTest.java
  java/core/src/test/java/sleeper/core/deploy/PopulatePropertiesTestHelper.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownSystemTestDeployment.java
Labels: pr-base-for-stacking, one-review-required

#3618 Update to improve error handling for docker image not present
  scripts/cli/runInDocker.sh
Labels: one-review-required

#3616 Issue 3615 - Move property population to static constructor
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/core/src/main/java/sleeper/core/deploy/DeployInstanceConfiguration.java
  java/core/src/main/java/sleeper/core/deploy/DeployInstanceConfigurationFromTemplates.java
  java/core/src/main/java/sleeper/core/deploy/PopulateInstanceProperties.java
  java/core/src/test/java/sleeper/core/deploy/DeployInstanceConfigurationIT.java
  java/core/src/test/java/sleeper/core/deploy/PopulateInstancePropertiesTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/DeployNewTestInstance.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperInstanceDriver.java
Labels: pr-base-for-stacking

#3620 Issue 3563 - Handle invalid job while waiting for file assignment
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskAssignFilesTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTerminateTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/SqsCompactionQueueHandler.java
Labels: pr-base-for-stacking, one-review-required

#3621 Issue 3619 - Stop returning compactions for non-existent table to the queue
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTest.java
Labels: one-review-required, pr-stacked-middle

#3633 Issue 3617 - Discard invalid compaction on commit
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskAssignFilesTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTest.java
Labels: one-review-required

#3603 Issue 3513 - Deploy an instance with no tables
  docs/02-deployment-guide.md
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/core/src/main/java/sleeper/core/deploy/DeployInstanceConfiguration.java
  java/core/src/main/java/sleeper/core/deploy/DeployInstanceConfigurationFromTemplates.java
  java/core/src/test/java/sleeper/core/deploy/DeployInstanceConfigurationIT.java
  java/core/src/test/java/sleeper/core/deploy/PopulateInstancePropertiesTest.java
  java/core/src/test/java/sleeper/core/deploy/PopulatePropertiesTestHelper.java
  scripts/deploy/deployNew.sh
Labels: pr-base-for-stacking

#3664 Update new dependency check suppressions
  code-style/dependency-check-suppressions.xml
Labels: one-review-required

#3668 Issue 3662 - Raise polling timeout waiting for state store committer logs
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStore.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommits.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommitsTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
Labels: one-review-required

#3666 Issue 3655 - Handle large state store commits in garbage collector
  java/core/src/main/java/sleeper/core/statestore/commit/StateStoreCommitRequestInS3Uploader.java
  java/core/src/test/java/sleeper/core/statestore/commit/StateStoreCommitRequestInS3UploaderTest.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorLambda.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/commit/AddFilesToStateStore.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/impl/commit/AddFilesToStateStoreIT.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/gc/SystemTestGarbageCollection.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/PollWithRetriesDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/gc/GarbageCollectionTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/gc/GarbageCollectionTest.shouldGarbageCollectFilesAfterCompaction.approved.txt
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/PartitionsTestHelper.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryDirectIngestDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionFileWriter.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryRecordBatch.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EksBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/GarbageCollectionST.shouldGarbageCollectFilesAfterCompaction.approved.txt
Labels: one-review-required

#3667 Issue 3661 - Move reading VPC check property out of VpcStack
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/VpcStack.java
Labels: one-review-required

#3654 Issue 3640 - Update changelog for version 0.26.0
  CHANGELOG.md
  scripts/cli/runInDocker.sh
Labels: pr-base-for-stacking

#3700 Issue 3699 - Check many job file assignments in one query
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJob.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/StateStoreWaitForFiles.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/core/src/main/java/sleeper/core/statestore/CheckFileAssignmentsRequest.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStoreQueries.java
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryFileReferenceStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStoreTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
Labels: pr-base-for-stacking

#3714 Issue 3707 - Generate system test table names from test name
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesLocalIT.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SystemTestContext.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SleeperInstanceTablesTest.java
Labels: one-review-required

#3715 Issue 3713 - Serialise compaction jobs as JSON
  java/clients/src/main/java/sleeper/clients/status/report/DeadLettersStatusReport.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJobJsonSerDe.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJobSerDe.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/commit/CompactionJobCommitRequestSerDe.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/commit/CompactionJobIdAssignmentCommitRequestSerDe.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobSerDeTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobSerDeTest.shouldConvertCompactionJobToFromJsonWithIterator.approved.json
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobSerDeTest.shouldConvertCompactionJobToFromJsonWithNoIterator.approved.json
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/commit/CompactionJobCommitRequestSerDeTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/commit/CompactionJobCommitRequestSerDeTest.shouldSerialiseCompactionJobCommitRequest.approved.json
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/commit/CompactionJobCommitRequestSerDeTest.shouldSerialiseCompactionJobCommitRequest.approved.txt
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/commit/CompactionJobIdAssignmentCommitRequestSerDeTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/commit/CompactionJobIdAssignmentCommitRequestSerDeTest.shouldSerialiseCompactionJobIdAssignmentCommitRequest.approved.json
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/SendCompactionJobToSqs.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsIT.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/SqsCompactionQueueHandler.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiser.java
Labels: pr-base-for-stacking

#3734 Issue 3705 - Take tables offline after system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriver.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriverIT.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstances.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SleeperTablesDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperTablesDriver.java
Labels: one-review-required

#3749 Issue 3689 - Lambda code for compaction job dispatch
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobBatchExpiredException.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatchRequest.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcher.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatchRequestSerDeTest.shouldConvertRequestToFromJson.approved.json
  java/compaction/compaction-job-creation-lambda/pom.xml
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambda.java
  java/compaction/compaction-job-creation-lambda/src/test/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambdaIT.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsIT.java
  java/core/src/main/java/sleeper/core/properties/instance/CdkDefinedInstanceProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
Labels: pr-base-for-stacking

#3765 Issue 3764 - Fix `sleeper environment add`
  java/cdk-environment/src/main/java/sleeper/environment/cdk/GetStackOutputs.java
  java/cdk-environment/src/main/java/sleeper/environment/cdk/SleeperEnvironmentCdkApp.java
  java/cdk-environment/src/main/java/sleeper/environment/cdk/util/ListEnvironmentStacks.java
  java/cdk-environment/src/test/java/sleeper/environment/cdk/util/ListEnvironmentStacksIT.java
Labels: one-review-required

#3766 Issue 3763 - Wait for compaction creation to commit when splitting files in system tests
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/WaitForCompactionJobCreation.java
Labels: one-review-required

#3772 Issue 3670 - Upgrade DataFusion to 43.0.0
  rust/Cargo.lock
  rust/compaction/Cargo.toml
  rust/compaction/src/datafusion/sketch.rs
  rust/compaction/src/datafusion/udf.rs
Labels: compactions-module, version-upgrades

#3651 Issue 3329 - Lookup EC2 sizes at runtime
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionStack.java
  java/common/common-task/pom.xml
  java/common/common-task/src/main/java/sleeper/task/common/EC2Scaler.java
  java/common/common-task/src/main/java/sleeper/task/common/RunCompactionTasks.java
  java/compaction/compaction-task-creation/pom.xml
  java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/task/creation/RunCompactionTasksLambda.java
  java/pom.xml
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
Labels: compactions-module, pr-base-for-stacking

#3762 Issue 3761 - Deploy an instance with status stores disabled
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionStatusStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/DynamoDBCompactionStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/DynamoDBIngestStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStatusStoreStack.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/OptionalFeaturesDisabledST.java
Labels: one-review-required

#3771 Issue 3770 - Split up compaction stack
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionOnEc2Resources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionOnFargateResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
Labels: pr-base-for-stacking, one-review-required

#3778 Issue 3777 - Add DescribeInstanceTypes permission to compaction task creation lambda
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
Labels: one-review-required, pr-stacked-middle

#3789 Issue 3784 - Run optional features disabled system test with no status stores
  java/clients/src/main/java/sleeper/clients/status/update/PauseSystem.java
  java/clients/src/main/java/sleeper/clients/status/update/RestartSystem.java
  java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java
  java/core/src/main/java/sleeper/core/deploy/PopulateInstanceProperties.java
  java/core/src/main/java/sleeper/core/deploy/SleeperScheduleRule.java
  java/core/src/main/java/sleeper/core/statestore/AllReferencesToAllFiles.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsScheduleRulesDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsSnapshotsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSnapshotsDriver.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSystemTestDrivers.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SystemTestDrivers.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstances.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/ScheduleRulesDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestDeploymentContext.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestTableFiles.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/NoScheduleRulesDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/NoSnapshotsDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/OptionalFeaturesDisabledST.java
Labels: one-review-required

#3768 Issue 3690 - Deploy compaction job dispatch lambda
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
  java/core/src/main/java/sleeper/core/deploy/LambdaHandler.java
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking, one-review-required

#3800 Issue 3790: Adjustment of Compaction Instance Property to a Table Property
  example/full/instance.properties
  example/full/table.properties
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/creation/CreateCompactionJobs.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/creation/CreateCompactionJobsTest.java
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
  java/core/src/main/java/sleeper/core/properties/table/TableProperty.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#3802 Issue 3796 - Compaction dispatch failures
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/runner/BulkImportJobDriver.java
  java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/BulkImportBucketStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionOnEc2Resources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionOnFargateResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/ConfigBucketStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/CoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/LoggingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/PropertiesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/StateStoreCommitterStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/TableDataStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogSnapshotStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogTransactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/VpcStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/KeepLambdaWarmStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/QueryStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/WebSocketQueryStack.java
  java/cdk/src/main/java/sleeper/cdk/util/AutoDeleteS3Objects.java
  java/cdk/src/main/java/sleeper/cdk/util/Utils.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/AwsCreateCompactionJobs.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/SendAssignJobIdToSqs.java
  java/core/src/main/java/sleeper/core/deploy/LambdaHandler.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestBucketStack.java
  scripts/cli/builder/Dockerfile
Labels: pr-base-for-stacking, one-review-required
