Repository gchq/sleeper, pull requests merged in 2024-12, with the labels that each got.

#3833 Issue 3819 Move compaction creation status update to dispatch lambda
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterTestBase.java
  java/clients/src/test/resources/reports/compaction/job/standard/all/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/multipleInputFiles.txt
  java/clients/src/test/resources/reports/compaction/job/standard/detailed/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/range/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/unfinished/mixedUnfinishedJobs.txt
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJobStatusStore.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/creation/AssignJobIdToFiles.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/creation/CreateCompactionJobs.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcher.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/status/CompactionJobCreatedEvent.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/status/CompactionJobCreatedStatus.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/status/CompactionJobStatus.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/status/CompactionJobStatusType.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobRunTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobStatusFromRecordsTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobStatusFurthestStatusTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobStatusTaskIdAssignedTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobStatusTestData.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/creation/CreateCompactionJobsTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcherTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/testutils/InMemoryCompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/testutils/InMemoryCompactionJobStatusStoreTest.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambda.java
  java/compaction/compaction-job-creation-lambda/src/test/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambdaIT.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/AwsCreateCompactionJobs.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/util/WaitForJobsStatusTest.java
Labels: pr-base-for-stacking, one-review-required

#3841 Issue 3840 - Handle partial batch failures in compaction dispatch
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcher.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcherTest.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambda.java
  java/compaction/compaction-job-creation-lambda/src/test/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambdaIT.java
Labels: one-review-required, pr-stacked-middle

#3820 Issue 3817 Update default values and descriptions for concurrency properties
  example/full/instance.properties
  java/core/src/main/java/sleeper/core/properties/instance/CommonProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/DefaultProperty.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#3845 Issue 3807 - Improvements to transaction deletion logs
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogDeletionTracker.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogDeletionTrackerTest.java
  java/statestore-lambda/src/main/java/sleeper/statestore/lambda/transaction/TransactionLogTransactionDeletionLambda.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoSnapshots.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotCreator.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
Labels: one-review-required

#3846 Issue 3776 - Configure memory overhead when scaling compaction EC2 instances
  example/full/instance.properties
  java/common/common-task/src/main/java/sleeper/task/common/CompactionTaskHostScaler.java
  java/common/common-task/src/test/java/sleeper/task/common/RunCompactionTasksTest.java
  java/core/src/main/java/sleeper/core/properties/SleeperPropertyValues.java
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
  java/core/src/main/java/sleeper/core/properties/validation/SleeperPropertyValueUtils.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#3857 Issue 3854 - Increase wait for forced compaction creation
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
Labels: pr-stacked-middle

#3858 Issue 3855 - Raise timeout waiting for bulk import in performance test
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceST.java
Labels: pr-stacked-top

#3870 Issue 3831 - Rearrange scripts documentation
  docs/02-deployment-guide.md
  docs/04-tables.md
  docs/06-status.md
Labels: pr-base-for-stacking

#3871 Issue 3869 - Link to issue on compaction in LocalStack
  docs/11-deploy-to-localstack.md
Labels: pr-stacked-top

#3872 Issue 3867 - Clear Sleeper instance on first connect in system tests
  .vscode/settings.json
  java/core/src/main/java/sleeper/core/deploy/SqsQueues.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsResetInstanceOnFirstConnect.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperInstanceDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsDrainSqsQueue.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriverDrainCompactionsIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsResetInstanceOnFirstConnectIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriverIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/AwsSendCompactionJobsTestHelper.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSleeperInstanceDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SleeperInstanceDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperInstanceDriver.java
Labels: one-review-required

#3883 Issue 3876 - Stop purging queues after system tests
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/AfterTestPurgeQueues.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/AfterTestPurgeQueuesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/gc/GarbageCollectionTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnEC2ST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrServerlessBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonIngestST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonQueryST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
Labels: one-review-required

#3882 Issue 3875 - Adjust Deletion Lambdas
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogSnapshotStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogTransactionStack.java
  java/core/src/main/java/sleeper/core/properties/instance/TableStateProperty.java
  java/statestore-lambda/src/main/java/sleeper/statestore/lambda/snapshot/TransactionLogSnapshotDeletionLambda.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/SnapshotDeletionTracker.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotDeleter.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotDeleterIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotTestBase.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#3927 Issue 3909 - Configure GC lambda timeout in seconds
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/core/src/main/java/sleeper/core/properties/instance/BatcherProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/GarbageCollectionProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/PartitionSplittingProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/QueryProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/TableStateProperty.java
  java/core/src/main/java/sleeper/core/properties/validation/SleeperPropertyValueUtils.java
  java/core/src/test/java/sleeper/core/properties/instance/InstancePropertiesTest.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking, one-review-required

#3929 Issue 3866 - Add missing descriptions
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogSnapshotStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogTransactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/KeepLambdaWarmStack.java
  java/cdk/src/main/java/sleeper/cdk/util/Utils.java
  java/core/src/main/java/sleeper/core/deploy/SleeperScheduleRule.java
Labels: one-review-required, pr-stacked-top

#3938 Issue 3726 - Enable ingest task creation schedule in system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestTasksDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SystemTestDrivers.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/IngestTasksDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcher.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestByQueue.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/WaitForIngestTasks.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/python/SystemTestPythonIngest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/SystemTestCluster.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/SystemTestDriversBase.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcherTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/WaitForIngestTasksTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/reporting/SystemTestReportingTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestBatcherDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonIngestST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceST.java
Labels: pr-base-for-stacking, one-review-required

#3955 Issue 3954 - Upgrade Rust & sccache in GitHub Actions
  .github/workflows/chunk.yaml
  .github/workflows/rust-audit.yaml
  .github/workflows/rust-cache.yaml
  .github/workflows/rust-lint.yaml
  .github/workflows/rust-tests.yaml
  rust/compaction/src/details.rs
  rust/rust_sketch/src/quantiles.rs
Labels: one-review-required

#3958 Validate sqsqueues includes all queue properties
  java/core/src/test/java/sleeper/core/deploy/SQSQueuesTest.java
Labels: one-review-required

#3959 Issue 3961 - Prepare to add compaction job status store event to compaction commit transaction
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJob.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/commit/CompactionJobCommitter.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/commit/CompactionJobCommitterOrSendToLambda.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcher.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/status/CompactionJobCommittedEvent.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/status/CompactionJobFailedEvent.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/status/CompactionJobFinishedEvent.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/status/CompactionJobStartedEvent.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/CompactionTask.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/StateStoreWaitForFiles.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskCommitTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/testutils/InMemoryCompactionJobStatusStoreTest.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByPeriodIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByTaskIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusUnfinishedIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobExpiryIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobRunIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
  java/core/src/main/java/sleeper/core/statestore/ReplaceFileReferencesRequest.java
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryFileReferenceStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeReplaceFileReferences.approved.txt
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogFileReferenceStoreIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/util/WaitForJobsStatusTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
Labels: one-review-required

#3939 Issue 3724 - Enable compaction task creation schedule in system tests
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStack.java
  java/core/src/main/java/sleeper/core/deploy/SleeperScheduleRule.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestTasksDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/CompactionDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/IngestTasksDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/WaitForTasks.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CreateManyCompactionsTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/ParallelCompactionsTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/gc/GarbageCollectionTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/WaitForIngestTasksTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/reporting/SystemTestReportingTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/util/WaitForTasksTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionDataFusionPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnEC2ST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsST.java
Labels: pr-base-for-stacking, one-review-required

#3940 Issue 3729 - Enable table metrics schedule rule in system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/metrics/AwsTableMetricsDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestTables.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/TableMetricsST.java
Labels: one-review-required, pr-stacked-middle

#3941 Issue 3725 - Enable compaction job creation schedule in system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionTest.MergeFiles.shouldCompactFilesUsingBasicCompactionStrategy.approved.txt
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionTest.MergeFiles.shouldCompactFilesUsingDefaultCompactionStrategy.approved.txt
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionTest.MergePartialFiles.shouldCompactOneFileFromRootIntoExistingFilesOnLeafPartitions.approved.txt
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionTest.MergePartialFiles.shouldCompactOneFileIntoExistingFilesOnLeafPartitions.approved.txt
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionTest.shouldCompactFilesFromMultiplePartitions.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionDataFusionPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnEC2ST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CreateManyCompactionsST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsST.java
  java/system-test/system-test-suite/src/test/resources/compaction/compacted4To2Files.txt
  java/system-test/system-test-suite/src/test/resources/compaction/compactedFileIntoLeafPartitions.txt
  java/system-test/system-test-suite/src/test/resources/compaction/compactedFilesFromMultiplePartitions.txt
Labels: one-review-required, pr-stacked-middle

#3942 Issue 3706 - Enable GC & partition splitting schedules in system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/gc/AwsGarbageCollectionDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/partitioning/AwsPartitionSplittingDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/gc/SystemTestGarbageCollection.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/gc/GarbageCollectionTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnEC2ST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingST.java
Labels: one-review-required, pr-stacked-middle

#3945 Issue 3727 - Enable ingest batcher schedule in system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestBatcherDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/IngestBatcherDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcher.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcherTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestBatcherDriver.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherST.java
Labels: one-review-required, pr-stacked-middle

#3957 Issue 3949 - Deploy system test instances unpaused
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperInstanceDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
Labels: one-review-required, pr-stacked-top

#3973 Issue 3968 - Rename compaction task status store to tracker
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTrackerStack.java
  java/clients/src/main/java/sleeper/clients/admin/AdminClientTrackerFactory.java
  java/clients/src/main/java/sleeper/clients/admin/CompactionStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/IngestBatcherReportScreen.java
  java/clients/src/main/java/sleeper/clients/docker/stack/CompactionDockerStack.java
  java/clients/src/main/java/sleeper/clients/status/report/CompactionTaskStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/StatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/compaction/task/CompactionTaskQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/compaction/task/CompactionTaskStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/compaction/task/JsonCompactionTaskStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/compaction/task/StandardCompactionTaskStatusReporter.java
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientProcessTrackerHolder.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientProcessTrackerHolderTest.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/RunAdminClient.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/task/CompactionTaskStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/task/CompactionTaskStatusReportTestHelper.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskCommitTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/StateStoreWaitForFilesTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/StateStoreWaitForFilesTestHelper.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/CompactionTaskTrackerFactory.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskTracker.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskTrackerCreator.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskTrackerCreatorIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/task/QueryAllCompactionTasksIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/task/QueryCompactionTasksByPeriodIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/task/QueryCompactionTasksInProgressIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/task/StoreCompactionTaskExpiryIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/task/StoreCompactionTaskIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionTaskStatusStoreTestBase.java
  java/core/src/main/java/sleeper/core/tracker/compaction/task/CompactionTaskFinishedStatus.java
  java/core/src/main/java/sleeper/core/tracker/compaction/task/CompactionTaskStartedStatus.java
  java/core/src/main/java/sleeper/core/tracker/compaction/task/CompactionTaskStatus.java
  java/core/src/main/java/sleeper/core/tracker/compaction/task/CompactionTaskStatusesBuilder.java
  java/core/src/main/java/sleeper/core/tracker/compaction/task/CompactionTaskTracker.java
  java/core/src/test/java/sleeper/core/tracker/compaction/task/CompactionTaskStatusInPeriodTest.java
  java/core/src/test/java/sleeper/core/tracker/compaction/task/CompactionTaskStatusTest.java
  java/core/src/test/java/sleeper/core/tracker/compaction/task/CompactionTaskStatusTestData.java
  java/core/src/test/java/sleeper/core/tracker/compaction/task/CompactionTaskStatusesBuilderTest.java
  java/core/src/test/java/sleeper/core/tracker/compaction/task/InMemoryCompactionTaskTracker.java
  java/core/src/test/java/sleeper/core/tracker/compaction/task/InMemoryCompactionTaskTrackerTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionReportsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsWaitForJobs.java
  java/system-test/system-test-dsl/pom.xml
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/reporting/CompactionReportsDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/reporting/SystemTestReporting.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/WaitForJobs.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryReports.java
Labels: pr-base-for-stacking, one-review-required
