Repository gchq/sleeper, pull requests merged in 2024-04, with the labels that each got.

#2180 Issue 2179 - Get serialised records returned from query in QueryWebSocketClient
  java/clients/src/main/java/sleeper/clients/QueryWebSocketClient.java
  java/clients/src/test/java/sleeper/clients/FakeWebSocketClient.java
  java/clients/src/test/java/sleeper/clients/QueryWebSocketClientTest.java
  java/clients/src/test/java/sleeper/clients/QueryWebSocketClientTestHelper.java
  java/clients/src/test/java/sleeper/clients/QueryWebSocketCommandLineClientTest.java
Labels: pr-stacked-middle

#2242 Issue 2160 - Limit tables to show in DashboardStack
  java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java
Labels: one-review-required

#2254 Issue 1932 - System test for compactions on EC2
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/common-task/src/main/java/sleeper/task/common/EC2Scaler.java
  java/common-task/src/main/java/sleeper/task/common/RunCompactionTasks.java
  java/configuration/src/main/java/sleeper/configuration/Requirements.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/CompactionDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnEC2IT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnFargateIT.java
Labels: one-review-required

#2248 Issue 2247 - Extract ExponentialBackoffWithJitter
  java/core/src/main/java/sleeper/core/util/ExponentialBackoffWithJitter.java
  java/core/src/test/java/sleeper/core/util/ExponentialBackoffWithJitterTest.java
  java/core/src/test/java/sleeper/core/util/ExponentialBackoffWithJitterTestHelper.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStoreDataFile.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreDataFileTest.java
Labels: pr-base-for-stacking

#2249 Issue 2198 - Handle failures adding transactions to the log
  java/core/src/main/java/sleeper/core/statestore/transactionlog/DuplicateTransactionNumberException.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
  java/core/src/test/java/sleeper/core/util/ExponentialBackoffWithJitterTestHelper.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
Labels: pr-stacked-middle

#2253 Issue 2251 - Throw StateStoreException reading transactions
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
Labels: pr-stacked-top

#2236 Issue 2197 - Define custom exceptions in QueryWebSocketClient
  java/clients/src/main/java/sleeper/clients/QueryClient.java
  java/clients/src/main/java/sleeper/clients/QueryCommandLineClient.java
  java/clients/src/main/java/sleeper/clients/QueryLambdaClient.java
  java/clients/src/main/java/sleeper/clients/QueryWebSocketClient.java
  java/clients/src/main/java/sleeper/clients/QueryWebSocketCommandLineClient.java
  java/clients/src/main/java/sleeper/clients/exception/MessageMalformedException.java
  java/clients/src/main/java/sleeper/clients/exception/MessageMissingFieldException.java
  java/clients/src/main/java/sleeper/clients/exception/QueryWebSocketClientException.java
  java/clients/src/main/java/sleeper/clients/exception/UnknownMessageTypeException.java
  java/clients/src/main/java/sleeper/clients/exception/WebSocketClosedException.java
  java/clients/src/main/java/sleeper/clients/exception/WebSocketErrorException.java
  java/clients/src/main/java/sleeper/clients/exception/WebSocketException.java
  java/clients/src/test/java/sleeper/clients/FakeWebSocketClient.java
  java/clients/src/test/java/sleeper/clients/QueryWebSocketClientTest.java
  java/clients/src/test/java/sleeper/clients/QueryWebSocketClientTestHelper.java
  java/clients/src/test/java/sleeper/clients/QueryWebSocketCommandLineClientTest.java
Labels: pr-base-for-stacking

#2237 Issue 2186 - Move ConsoleOutput usage from QueryWebSocketClient to QueryWebSocketCommandLineClient
  java/clients/src/main/java/sleeper/clients/QueryWebSocketClient.java
  java/clients/src/main/java/sleeper/clients/QueryWebSocketCommandLineClient.java
  java/clients/src/main/java/sleeper/clients/exception/MessageMissingFieldException.java
  java/clients/src/test/java/sleeper/clients/FakeWebSocketClient.java
  java/clients/src/test/java/sleeper/clients/QueryWebSocketClientTest.java
  java/clients/src/test/java/sleeper/clients/QueryWebSocketCommandLineClientTest.java
Labels: pr-base-for-stacking

#2267 Issue 2250 - Track state store transaction number
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogEntry.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStoreTest.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
Labels: one-review-required

#2269 Issue 2266 - Track transaction update time in DynamoDB
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTestBase.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsTest.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/PartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/StateStoreTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogEntry.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/AddFilesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/AssignJobIdsTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ClearFilesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/DeleteFilesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/InitialisePartitionsTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ReplaceFileReferencesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/SplitFileReferencesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/SplitPartitionTransaction.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/SplitFileReferencesTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeAddFiles.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeAddSplitFile.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeAssignJobIds.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeReplaceFileReferences.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeSplitFileReferences.approved.txt
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorFileWritingStrategyIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrayListIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowRecordWriterAcceptingRecordListIT.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreDynamoSpecificIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreOneTableTestBase.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreS3SpecificIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreOneTableTestBase.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreOneTableTestBase.java
Labels: one-review-required

#2277 Issue 2121 - Deploy transaction log state store in CDK
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogStateStoreStack.java
Labels: one-review-required

#2287 Issue 2284 - Only deploy one NAT
  java/cdk-environment/src/main/java/sleeper/environment/cdk/networking/NetworkingStack.java
Labels: one-review-required

#2318 Issue 2312 - Set expected range in performance tests
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/reporting/JobsFinishedStatistics.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
Labels: one-review-required, pr-stacked-top

#2347 Issue 2272 - Track transaction log snapshots in DynamoDB
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DuplicateSnapshotException.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStoreCreator.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/SnapshotType.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogFilesSnapshotSerDe.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogPartitionsSnapshotSerDe.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshot.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotSerDeIT.java
Labels: pr-base-for-stacking

#2367 Issue 2362 - Regularly refresh instance admin drivers
  java/system-test/system-test-dsl/pom.xml
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/InstanceAdminDriversWithRefresh.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/InstanceAdminDriversWithRefreshTest.java
Labels: one-review-required

#2359 Issue 2370 - FIFO queue to batch garbage collection
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsTriggerLambda.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/GarbageCollectionProperty.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorLambda.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorTriggerLambda.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryGarbageCollectionDriver.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#2373 Issue 2371 - FIFO queue to find partitions to split
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/FindPartitionsToSplit.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/FindPartitionsToSplitTest.java
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/FindPartitionsToSplitLambda.java
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/FindPartitionsToSplitTriggerLambda.java
  java/splitter/splitter-lambda/src/test/java/sleeper/splitter/lambda/FindPartitionsToSplitIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionSplittingDriver.java
  scripts/templates/instanceproperties.template
Labels: pr-stacked-middle

#2375 Issue 2372 - FIFO queue to publish table metrics
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/metrics/src/main/java/sleeper/metrics/TableMetricsLambda.java
  java/metrics/src/main/java/sleeper/metrics/TableMetricsTriggerLambda.java
  scripts/templates/instanceproperties.template
Labels: pr-stacked-top

#2376 Issue 2317 - Remove Base64 methods from SchemaSerDe
  java/core/src/main/java/sleeper/core/schema/SchemaSerDe.java
Labels: one-review-required

#2355 Issue 2271 - Load latest snapshot when first using transaction log state store
  example/full/instance.properties
  example/full/table.properties
  java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogStateStoreStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreFactory.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreFileUtils.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStoreCreator.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogFilesSnapshotSerDe.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshot.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshotSerDe.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogStateStoreCreator.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotSerDeIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreOneTableTestBase.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreTestBase.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#2390 Issue 2389 - Configure system test writers to run multiple ingests
  java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
  java/system-test/system-test-configuration/src/test/java/sleeper/systemtest/configuration/SystemTestPropertiesTest.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateRandomDataFiles.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomData.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java
  scripts/test/deployAll/system-test-instance.properties
Labels: pr-base-for-stacking

#2392 Issue 2324 - Retry compaction job completion
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/TimedOutWaitingForFileAssignmentsException.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesRetryStateStoreTest.java
  java/core/src/main/java/sleeper/core/util/ExponentialBackoffWithJitter.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
Labels: pr-base-for-stacking

#2401 Issue 2400 - Disable transaction log state store snapshots by class name
  example/full/table.properties
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreFactory.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoSnapshots.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreTestBase.java
  scripts/templates/tableproperties.template
Labels: pr-base-for-stacking
