Repository gchq/sleeper, pull requests merged in 2024-08, with the labels that each got.

#3006 Issue 3005 - Add DynamoDB helper for retrying code that throws throttling exception
  java/common/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java
  java/common/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsTest.java
Labels: pr-base-for-stacking

#3003 Issue 2925 - Explain system tests are set up to run on 3 AZs
  docs/13-system-tests.md
Labels: one-review-required

#3009 Issue 3008 - Fix CLI user file ownership
  scripts/cli/builder/Dockerfile
  scripts/cli/environment/Dockerfile
  scripts/cli/runInDocker.sh
  scripts/cli/runner/Dockerfile
Labels: one-review-required

#3007 Issue 2916 - Shut down system test cluster during Maven teardown
  java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
  java/clients/src/main/java/sleeper/clients/teardown/WaitForStackToDelete.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestBucketStack.java
  java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestStandaloneProperties.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownSystemTestDeployment.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownTestInstance.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSystemTestDeploymentDriver.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSystemTestDeploymentDriver.java
Labels: one-review-required

#3016 Issue 2954 - Remove PartitionsBuilder.Splitter, split out PartitionsBuilderSplitsFirst
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/rdd/SingleFileWritingIteratorIT.java
  java/clients/src/test/java/sleeper/clients/admin/FilesStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/PartitionsStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterTestBase.java
  java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionStatusReportTestHelper.java
  java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobTestDataHelper.java
  java/core/src/test/java/sleeper/core/partition/PartitionTest.java
  java/core/src/test/java/sleeper/core/partition/PartitionTreeNearestCommonAncestorTest.java
  java/core/src/test/java/sleeper/core/partition/PartitionTreeTraverseLeavesFirstTest.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilderSplitsFirst.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilderTest.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/FixedPartitionStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/ParallelCompactionsTest.java
Labels: one-review-required

#3023 Issue 3022 - Append arguments to mvn command in build scripts
  scripts/build/build.sh
Labels: one-review-required

#3052 Issue 3051 - Refactor partition splitting
  java/athena/src/test/java/sleeper/athena/metadata/IteratorApplyingMetadataHandlerIT.java
  java/athena/src/test/java/sleeper/athena/metadata/SleeperMetadataHandlerIT.java
  java/clients/src/main/java/sleeper/clients/status/report/DeadLettersStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/partitions/PartitionStatus.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/SplitPartition.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/find/FindPartitionToSplitResult.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/find/FindPartitionsToSplit.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/find/PartitionSplitCheck.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/find/SplitPartitionJobDefinition.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/find/SplitPartitionJobDefinitionSerDe.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/split/FindPartitionSplitPoint.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/split/SplitPartition.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/split/SplitPartitionResult.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/split/SplitPartitionResultFactory.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/find/FindPartitionsToSplitTest.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/find/SplitPartitionJobDefinitionSerDeTest.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/split/SplitPartitionTest.java
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/FindPartitionsToSplitLambda.java
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/SplitPartitionLambda.java
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/SqsSplitPartitionJobSender.java
  java/splitter/splitter-lambda/src/test/java/sleeper/splitter/lambda/FindPartitionsToSplitIT.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/WaitForPartitionSplitting.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionSplittingDriver.java
Labels: one-review-required

#3062 Issue 3061 - Send state store commits in parallel
  java/core/src/main/java/sleeper/core/util/SplitIntoBatches.java
  java/core/src/test/java/sleeper/core/util/SplitIntoBatchesTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriver.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriverIT.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommits.java
Labels: pr-base-for-stacking, one-review-required

#3064 Issue 2927 - Asynchronously commit partition splitting
  example/full/instance.properties
  example/full/table.properties
  java/athena/src/test/java/sleeper/athena/metadata/IteratorApplyingMetadataHandlerIT.java
  java/athena/src/test/java/sleeper/athena/metadata/SleeperMetadataHandlerIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/split/FindPartitionSplitPoint.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/split/SplitPartition.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/split/SplitPartitionTest.java
  java/splitter/splitter-lambda/pom.xml
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/SplitPartitionLambda.java
  java/splitter/splitter-lambda/src/test/java/sleeper/splitter/lambda/SplitPartitionLambdaIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionSplittingDriver.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#3082 Issue 3081 - Commit garbage collection in state store committer
  java/core/src/main/java/sleeper/core/statestore/commit/CommitRequestType.java
  java/core/src/main/java/sleeper/core/statestore/commit/GarbageCollectionCommitRequest.java
  java/core/src/main/java/sleeper/core/statestore/commit/GarbageCollectionCommitRequestSerDe.java
  java/core/src/test/java/sleeper/core/statestore/commit/GarbageCollectionCommitRequestSerDeTest.java
  java/core/src/test/java/sleeper/core/statestore/commit/GarbageCollectionCommitRequestSerDeTest.shouldSerialiseGarbageCollectionCommitRequest.approved.txt
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitRequest.java
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitRequestDeserialiser.java
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitter.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitRequestDeserialiserTest.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java
Labels: one-review-required

#3084 Issue 3083 - Compute requests per second from state store committer logs
  java/clients/src/main/java/sleeper/clients/status/report/statestore/StateStoreCommitSummary.java
  java/clients/src/main/java/sleeper/clients/status/report/statestore/StateStoreCommitterRequestsPerSecond.java
  java/clients/src/main/java/sleeper/clients/status/report/statestore/StateStoreCommitterRun.java
  java/clients/src/main/java/sleeper/clients/status/report/statestore/StateStoreCommitterRuns.java
  java/clients/src/test/java/sleeper/clients/status/report/statestore/StateStoreCommitterRequestsPerSecondTest.java
  java/clients/src/test/java/sleeper/clients/status/report/statestore/StateStoreCommitterRunsByTableTest.java
  java/clients/src/test/java/sleeper/clients/status/report/statestore/StateStoreCommitterRunsFromEntriesTest.java
Labels: one-review-required, pr-stacked-top

#3085 Issue 2901 Asynchronous commit of garbage collection
  example/full/instance.properties
  example/full/table.properties
  java/configuration/src/main/java/sleeper/configuration/properties/instance/GarbageCollectionProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorLambda.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryGarbageCollectionDriver.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#3106 Issue 3099 - Handle singular & negative in LoggedDuration
  java/core/src/main/java/sleeper/core/util/LoggedDuration.java
  java/core/src/test/java/sleeper/core/util/LoggedDurationTest.java
Labels: pr-base-for-stacking, one-review-required

#3072 Issue 3060 - Measure throughput in state store committer
  java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreCommitterStack.java
  java/clients/src/main/java/sleeper/clients/status/report/statestore/StateStoreCommitterRequestsPerSecond.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/StateStoreCommitterLogEntries.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/statestore/StateStoreCommitterLogEntriesTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitMessageFactory.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitterDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitterLogs.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStore.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommits.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/WaitForStateStoreCommitLogs.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommitsThroughputTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryStateStoreCommitter.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
Labels: pr-base-for-stacking, one-review-required

#3107 Issue 2932 - Avoid extra reads in state store committer
  example/full/instance.properties
  example/full/table.properties
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
  java/statestore-lambda/src/main/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambda.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreFactory.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreProvider.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoSnapshots.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotCreatorIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreTestBase.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
  scripts/templates/instanceproperties.template
Labels: one-review-required, pr-stacked-middle

#3113 Issue 2977 - Increase default visibility timeout for a failed compaction
  example/full/instance.properties
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#3112 Issue 3069 - Update status store for every failure committing a compaction
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitter.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java
Labels: one-review-required

#3111 Issue 3026 - Configure async commit
  example/full/instance.properties
  example/full/table.properties
  java/configuration/src/main/java/sleeper/configuration/Utils.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/GarbageCollectionProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyDefaultValue.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/validation/CompressionCodec.java
  java/configuration/src/main/java/sleeper/configuration/properties/validation/DefaultAsyncCommitBehaviour.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/DummyTableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#3127 Issue 3122 - Avoid duplicate test output in nightly test Maven site
  .gitignore
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/fixtures/SystemTestInstanceTest.java
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#3123 Issue 3116 - Combine policies for instance admin role
  java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
Labels: one-review-required

#3139 Issue 3118 - Avoid wait on first retry in state store committer
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
Labels: one-review-required

#3150 Issue 3149 - Track retries instead of polls in PollWithRetries
  java/common/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java
  java/common/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsTest.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/StateStoreWaitForFiles.java
  java/core/src/main/java/sleeper/core/util/PollWithRetries.java
  java/core/src/test/java/sleeper/core/util/PollWithRetriesTest.java
  java/statestore-lambda/src/main/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambda.java
Labels: pr-base-for-stacking, one-review-required

#3141 Issue 3138 - Update from transaction log when state store committer starts
  example/full/instance.properties
  example/full/table.properties
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestHelper.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreSnapshotsTest.java
  java/statestore-commit/src/main/java/sleeper/statestore/committer/CommitRequestValidationException.java
  java/statestore-commit/src/main/java/sleeper/statestore/committer/StateStoreCommitRequest.java
  java/statestore-commit/src/main/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiser.java
  java/statestore-commit/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-commit/src/test/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiserTest.java
  java/statestore-commit/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/statestore-commit/src/test/java/sleeper/statestore/committer/StateStoreCommitterThroughputIT.java
  java/statestore-lambda/pom.xml
  java/statestore-lambda/src/main/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambda.java
  java/statestore-lambda/src/test/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambdaTest.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreFactory.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriverIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryStateStoreCommitter.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking, one-review-required

#3156 Issue 3155 - Move commit request batch processing out of lambda code
  java/configuration/src/test/java/sleeper/configuration/statestore/InMemoryTransactionLogsPerTable.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestHelper.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogs.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreSnapshotsTest.java
  java/core/src/test/java/sleeper/core/util/ExponentialBackoffWithJitterTestHelper.java
  java/statestore-commit/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-commit/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/statestore-lambda/src/main/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambda.java
  java/statestore-lambda/src/test/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambdaTest.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotTestBase.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogTransactionDeleterTest.java
Labels: pr-base-for-stacking, one-review-required

#3164 Issue 3163 - Fix environment CLI permissions
  scripts/cli/environment/.dockerignore
  scripts/cli/environment/Dockerfile
  scripts/cli/environment/scripts/subcommands/adduser.sh
Labels: one-review-required
