Repository gchq/sleeper, pull requests merged in 2024-02, with the labels that each got.

#1746 Issue 1745 - Add files with no references, stop allowing multiple output references for a job
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/core/src/main/java/sleeper/core/statestore/AllReferencesToAFile.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileReference.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceSerDe.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/AllReferencesToAFileTestHelper.java
  java/core/src/test/java/sleeper/core/statestore/FileReferenceSerDeTest.java
  java/core/src/test/java/sleeper/core/statestore/FilesReportTestHelper.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionId.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionIdStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
Labels: pr-base-for-stacking

#1768 Issue 1766 - Add ingest source bucket to existing list in deployAll system tests
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestBucketStack.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
Labels: pr-base-for-stacking

#1747 Issue 1743 - Define specific exceptions for FileReferenceStore failures
  java/core/src/main/java/sleeper/core/statestore/AllReferencesToAFile.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileReference.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/exception/FileAlreadyExistsException.java
  java/core/src/main/java/sleeper/core/statestore/exception/FileHasReferencesException.java
  java/core/src/main/java/sleeper/core/statestore/exception/FileNotFoundException.java
  java/core/src/main/java/sleeper/core/statestore/exception/FileReferenceAlreadyExistsException.java
  java/core/src/main/java/sleeper/core/statestore/exception/FileReferenceAssignedToJobException.java
  java/core/src/main/java/sleeper/core/statestore/exception/FileReferenceNotAssignedToJobException.java
  java/core/src/main/java/sleeper/core/statestore/exception/FileReferenceNotFoundException.java
  java/core/src/main/java/sleeper/core/statestore/exception/NewReferenceSameAsOldReferenceException.java
  java/core/src/test/java/sleeper/core/statestore/AllReferencesToAFileTestHelper.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java
  java/splitter/src/test/java/sleeper/splitter/FindPartitionsToSplitTest.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceFormat.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBSplitRequestsBatch.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/FailedDynamoDBReplaceReferences.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/FailedDynamoDBSplitRequests.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStoreDataFile.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreDataFileTest.java
Labels: pr-base-for-stacking

#1776 Issue 1775 - Use correct Hadoop configuration when deploying to LocalStack
  java/clients/src/main/java/sleeper/clients/docker/DeployDockerInstance.java
  java/parquet/src/main/java/sleeper/io/parquet/utils/HadoopConfigurationProvider.java
Labels: one-review-required

#1780 Issue 1779 - Get and set enum properties
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertyValues.java
  java/configuration/src/main/java/sleeper/configuration/properties/validation/EmrInstanceTypeConfig.java
  java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/validation/EmrInstanceTypeConfigTest.java
  java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/IngestBatcherIngestModesTest.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/IngestBatcherTestBase.java
Labels: pr-base-for-stacking, one-review-required

#1781 Issue 1778 - Fix generating data in system test cluster
  java/system-test/system-test-configuration/src/test/java/sleeper/systemtest/configuration/SystemTestPropertiesTest.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataViaQueue.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java
Labels: one-review-required, pr-stacked-middle

#1800 Issue 1792 - System test to add and compact split file
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestSourceFilesDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/sourcedata/GeneratedIngestSourceFiles.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/sourcedata/GeneratedIngestSourceFilesDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/sourcedata/IngestSourceFilesContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/sourcedata/IngestSourceFilesDriver.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/ingest/IngestSourceFilesDriverTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestDirectEmrServerless.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngestBatcher.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngestByQueue.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngestToStateStore.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/sourcedata/SystemTestCluster.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/sourcedata/SystemTestSourceFiles.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestNoSourceBucketIT.java
Labels: pr-base-for-stacking, one-review-required

#1801 Issue 1791 - System test to split file from root partition
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngestToStateStore.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionIT.java
Labels: one-review-required, pr-stacked-middle

#1814 Issue 1810 - Standardise naming of in memory implementations
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutorTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutorTest.java
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/IngestStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientStatusStoreHolderTest.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/RunAdminClient.java
  java/clients/src/test/java/sleeper/clients/deploy/UploadDockerImagesTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/task/CompactionTaskStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/IngestQueueMessagesTest.java
  java/clients/src/test/java/sleeper/clients/util/InMemoryEcrRepositories.java
  java/common-job/src/test/java/sleeper/job/common/InMemoryQueueMessageCounts.java
  java/common-job/src/test/java/sleeper/job/common/InMemoryQueueMessageCountsTest.java
  java/common-job/src/test/java/sleeper/job/common/QueueMessageCountsSequenceTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionTaskStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionTaskStatusStoreTest.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsTest.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/IngestBatcherTestBase.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/testutil/InMemoryIngestBatcherQueues.java
  java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/testutil/InMemoryIngestBatcherQueuesTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStore.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStoreTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/task/InMemoryIngestTaskStatusStore.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/task/InMemoryIngestTaskStatusStoreTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskTest.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/util/WaitForJobsStatusTest.java
Labels: one-review-required

#1805 Issue 1804 - Split SleeperInstanceContext
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/OptionalStacksDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstance.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceTables.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestDeploymentContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestDeploymentDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestParameters.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EksBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/fixtures/SystemTestInstanceTest.java
Labels: pr-base-for-stacking, one-review-required

#1830 Issue 1825 - Remove SQS dependency from parquet module
  java/cdk/pom.xml
  java/compaction/compaction-job-creation/pom.xml
  java/parquet/pom.xml
  java/query/query-runner/pom.xml
  java/splitter/splitter-lambda/pom.xml
Labels: one-review-required

#1835 Issue 1829 - Add ability to run compactAllFiles.sh for a specific table
  java/clients/src/main/java/sleeper/clients/status/update/CreateJobsClient.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsTest.java
  scripts/utility/compactAllFiles.sh
  scripts/utility/compactFiles.sh
Labels: one-review-required

#1838 Issue 1837 - Upgrade nimbus-jose-jwt
  NOTICES
  java/pom.xml
Labels: one-review-required

#1834 Issue 1832 - Table metrics system test
  java/cdk/src/main/java/sleeper/cdk/jars/LambdaCode.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployExistingInstance.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesTest.java
  java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperScheduleRule.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/core/src/main/java/sleeper/core/util/PollWithRetries.java
  java/core/src/test/java/sleeper/core/util/PollWithRetriesTest.java
  java/metrics/src/main/java/sleeper/metrics/TableMetrics.java
  java/metrics/src/main/java/sleeper/metrics/TableMetricsLambda.java
  java/metrics/src/test/java/sleeper/metrics/TableMetricsTest.java
  java/pom.xml
  java/system-test/system-test-drivers/pom.xml
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/metrics/AwsTableMetricsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SleeperSystemTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/metrics/SystemTestMetrics.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/metrics/TableMetricsDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/SystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SetupInstanceTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperInstanceDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperInstanceTablesDriver.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/TableMetricsIT.java
  scripts/deploy/deployExisting.sh
Labels: one-review-required

#1841 Issue 1839 - Make TablePropertiesStore throw exceptions in load methods
  java/clients/src/main/java/sleeper/clients/admin/properties/AdminClientPropertiesStore.java
  java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesStore.java
  java/configuration/src/test/java/sleeper/configuration/properties/PropertiesReloaderIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/S3TablePropertiesStoreIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderTest.java
  java/query/query-core/src/main/java/sleeper/query/model/QuerySerDe.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateRandomDataFiles.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/metrics/AwsTableMetricsDriver.java
Labels: pr-base-for-stacking, one-review-required

#1833 Issue 1822 - Update default ingest file writing strategy
  example/full/instance.properties
  example/full/table.properties
  java/athena/src/test/java/sleeper/athena/TestUtils.java
  java/athena/src/test/java/sleeper/athena/metadata/AbstractMetadataHandlerIT.java
  java/athena/src/test/java/sleeper/athena/metadata/IteratorApplyingMetadataHandlerIT.java
  java/athena/src/test/java/sleeper/athena/record/AbstractRecordHandlerIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorFileWritingStrategyIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrayListIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorFactory.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorTestHelper.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/ResultVerifier.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/TestIngestType.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#1848 Issue 1847 - Grant access to file reference count table when reading active files
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBStateStoreStack.java
Labels: one-review-required

#1846 Issue 1845 - Add table properties for ingest record batch and file writer types
  example/full/instance.properties
  example/full/table.properties
  java/athena/src/test/java/sleeper/athena/TestUtils.java
  java/clients/src/test/java/sleeper/clients/QueryClientIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactSortedFilesTestBase.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/IngestProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobQueueConsumerTestBase.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java
  java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/query/query-runner/src/test/java/sleeper/query/runner/recordretrieval/QueryExecutorIT.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestType.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SleeperInstanceContext.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemoryTestInstance.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#1850 Issue 1842 - DSL for multiple table system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/DirectQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SQSQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SchemaLoaderFromInstanceContext.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SleeperSystemTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/IngestByQueue.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperTablesForTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestTables.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/SystemTestPartitioning.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/query/QueryAllTablesInParallelDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/query/QueryAllTablesSendAndWaitDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SleeperInstanceTablesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryDirectQueryDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryQueryByQueueDriver.java
Labels: one-review-required, pr-stacked-middle

#1840 Issue 1394 - Parallelise table metrics
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/metrics/pom.xml
  java/metrics/src/main/java/sleeper/metrics/CalculateTableMetricsRequest.java
  java/metrics/src/main/java/sleeper/metrics/CalculateTableMetricsSerDe.java
  java/metrics/src/main/java/sleeper/metrics/TableMetrics.java
  java/metrics/src/main/java/sleeper/metrics/TableMetricsLambda.java
  java/metrics/src/main/java/sleeper/metrics/TableMetricsTriggerLambda.java
  java/metrics/src/test/java/sleeper/metrics/TableMetricsTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/metrics/AwsTableMetricsDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SleeperSystemTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/metrics/SystemTestTableMetrics.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/TableMetricsIT.java
  scripts/templates/instanceproperties.template
Labels: one-review-required, pr-stacked-top

#1867 Issue 1866 - Synchronize sets in InMemoryQueryByQueueDriver
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryQueryByQueueDriver.java
Labels: one-review-required

#1864 Issue 1859 - State store interface to assign job IDs to files for a batch of multiple jobs
  java/core/src/main/java/sleeper/core/statestore/AssignJobIdRequest.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
Labels: pr-base-for-stacking

#1865 Issue 1860 - Assign job IDs to files for a batch of multiple jobs in DynamoDB state store
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
Labels: pr-stacked-middle

#1870 Issue 1869 - Truncate table name in EKS state machine execution name
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutor.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutorTest.java
Labels: one-review-required

#1892 Issue 1875 - Pass table ID as a string to CompactionJobStatusStore
  java/clients/src/main/java/sleeper/clients/status/report/job/query/AllJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/RangeJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/UnfinishedJobsQuery.java
  java/clients/src/test/java/sleeper/clients/status/report/job/query/JobQueryPromptTest.java
  java/clients/src/test/java/sleeper/clients/status/report/job/query/JobQueryTest.java
  java/clients/src/test/java/sleeper/clients/status/report/job/query/JobQueryTestBase.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStoreCreatorIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
Labels: pr-base-for-stacking, one-review-required

#1893 Issue 1876 - Pass table ID as a string to IngestJobStatusStore
  code-style/eclipse-style.xml
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/job/BulkImportJob.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/BulkImportExecutorIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutorTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutorTest.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/AllJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/RangeJobsQuery.java
  java/clients/src/main/java/sleeper/clients/status/report/job/query/UnfinishedJobsQuery.java
  java/clients/src/test/java/sleeper/clients/admin/IngestStatusReportScreenTest.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusStore.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/IngestJobTestData.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStore.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStoreTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskTest.java
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobRunIdIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobValidatedIT.java
  java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/DynamoDBIngestJobStatusStoreTestBase.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestDirectBulkImport.java
Labels: one-review-required

#1889 Issue 1888 - Fix filenames in ingest batcher system test
  java/system-test/system-test-dsl/pom.xml
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcher.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/IngestSourceFilesContext.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/SystemTestSourceFiles.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcherTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestBatcherDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
Labels: pr-base-for-stacking, one-review-required

#1891 Issue 1890 - Fix multiple tables system test finding source files
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/IngestSourceFilesContext.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/sourcedata/SystemTestSourceFilesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryDirectIngestDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesIT.java
Labels: one-review-required, pr-stacked-top

#1894 Issue 1877- Take table ID as a string in properties provider & store
  java/clients/src/main/java/sleeper/clients/status/update/CreateJobsClient.java
  java/clients/src/test/java/sleeper/clients/status/update/AddTableIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesStore.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/InMemoryTablePropertiesStoreTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/S3TablePropertiesStoreIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesITBase.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderIT.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderTest.java
Labels: pr-base-for-stacking, one-review-required

#1909 Issue 1908 - Fix batcher system test driver
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestBatcherDriver.java
Labels: pr-base-for-stacking, one-review-required

#1911 Issue 1910 - Fix source file paths in Python drivers
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/python/PythonBulkImportDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/python/PythonIngestDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/IngestSourceFilesContext.java
Labels: one-review-required, pr-stacked-middle

#1913 Issue 1912 - Fix garbage collection system test
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/WaitForJobs.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionIT.java
Labels: one-review-required, pr-stacked-top

#1916 Issue 1904 - Add VSCode code-snippets file
  .vscode/templates.code-snippets
Labels: one-review-required

#1929 Issue 1926 - Persist system test deployment context between test classes
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestDeploymentContext.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestExtension.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/AwsSleeperSystemTestExtension.java
Labels: pr-base-for-stacking, one-review-required

#1935 Issue 1933 - Batching logic to invoke lambda for tables
  .vscode/settings.json
  java/core/src/main/java/sleeper/core/table/InvokeForTableRequest.java
  java/core/src/main/java/sleeper/core/util/SplitIntoBatches.java
  java/core/src/test/java/sleeper/core/table/InvokeForTableRequestTest.java
  java/core/src/test/java/sleeper/core/util/SplitIntoBatchesTest.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorTriggerLambda.java
  java/metrics/src/main/java/sleeper/metrics/TableMetricsTriggerLambda.java
Labels: one-review-required

#1942 Issue 1941 - Fix Eclipse/VS Code formatting configuration for array literals
  code-style/eclipse-style.xml
  java/splitter/splitter-core/src/test/java/sleeper/splitter/SplitPartitionIT.java
Labels: one-review-required
