Repository gchq/sleeper, pull requests merged in 2024-05, with the labels that each got.

#2414 Issue 2413 - Split ingest policy into direct and by queue
  java/cdk/src/main/java/sleeper/cdk/stack/ConfigBucketStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBIngestStatusStoreResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableDataStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableIndexStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/BulkImportBucketStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
Labels: pr-base-for-stacking, one-review-required

#2463 Issue 2462 - Use CompactionJobCompletion in CompactionTask
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/completion/CompactionJobCompletion.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/completion/CompactionJobCompletionUtils.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesEmptyOutputIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesRetryStateStoreTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
Labels: pr-base-for-stacking

#2470 Issue 2469 - Rename compaction job completion to compaction job committer
  .github/config/chunks.yaml
  .github/workflows/chunk-compaction.yaml
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitRequest.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitRequestSerDe.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitter.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitterUtils.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/TimedOutWaitingForFileAssignmentsException.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitRequestSerDeTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitRequestSerDeTest.shouldSerialiseCompactionJobCommitRequest.approved.txt
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitterTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitterTestBase.java
  java/compaction/compaction-job-committer-lambda/pom.xml
  java/compaction/compaction-job-committer-lambda/src/main/java/sleeper/compaction/completion/lambda/CompactionJobCommitterLambda.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesRetryStateStoreTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/compaction/pom.xml
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
Labels: pr-base-for-stacking

#2468 Issue 2477 - Add property to determine how compaction jobs are committed
  example/full/instance.properties
  example/full/table.properties
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionJobCommitHandler.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskCommitTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTerminateTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTestBase.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#2460 Issue 2445 - Deploy compaction job committer lambda with CDK
  example/full/instance.properties
  example/full/table.properties
  java/cdk/src/main/java/sleeper/cdk/jars/BuiltJar.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/compaction/compaction-job-committer-lambda/src/main/java/sleeper/compaction/committer/lambda/CompactionJobCommitterLambda.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionJobCommitHandler.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskCommitTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/distribution/src/main/assembly/zip.xml
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#2502 Issue 2490 - Restructure compaction job commit
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitter.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitterUtils.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionJobCommitterOrSendToLambda.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesRetryStateStoreTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTestBase.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
Labels: one-review-required

#2496 Issue 2495 - Deploy IAM roles for ingest
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/InstanceRolesStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
Labels: pr-base-for-stacking

#2498 Issue 2467 - Assume ingest roles in system test cluster
  java/clients/src/main/java/sleeper/clients/util/AssumeSleeperRole.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java
  java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
  java/system-test/system-test-data-generation/pom.xml
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataViaBatcher.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataViaQueue.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/InstanceIngestSession.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/RunWriteRandomDataTaskOnECS.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSystemTestResources.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java
Labels: pr-base-for-stacking

#2509 Issue 2508 - Reproduce & fix parallelism in MultipleTablesTest
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperTablesForTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/SystemTestPartitioning.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/WaitForPartitionSplitting.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.shouldCompactAndGCMultipleTables.approved.txt
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.shouldSplitPartitionsOfMultipleTables.approved.txt
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/partitioning/WaitForPartitionSplittingTest.java
Labels: one-review-required

#2522 Issue 2521 - Refactor state store grants
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBStateStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/S3StateStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreGrants.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogStateStoreStack.java
Labels: pr-base-for-stacking

#2513 Issue 2504 - Return batch item failures in snapshot creation & find splits
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/FindPartitionsToSplitLambda.java
  java/statestore-lambda/src/main/java/sleeper/statestore/TransactionLogSnapshotCreationLambda.java
Labels: one-review-required

#2531 Issue 2524 - Remove setting transaction log state in builder
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogSnapshot.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogSnapshotCreator.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogSnapshotUtils.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogSnapshots.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreSnapshotsTest.java
  java/statestore-lambda/src/main/java/sleeper/statestore/TransactionLogSnapshotCreationLambda.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotCreator.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshotCreator.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotCreatorIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
Labels: pr-stacked-top

#2541 Added missing " to runTests.sh
  scripts/test/maven/runTests.sh
Labels: bug

#2538 Issue 2528 - Fix concurrency failure in MultipleTablesIT when forcing compaction job creation
  java/statestore/src/main/java/sleeper/statestore/StateStoreProvider.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/gc/SystemTestGarbageCollection.java
Labels: one-review-required

#2537 Issue 2532 - Do not check snapshot on every update
  .vscode/settings.json
  example/full/instance.properties
  example/full/table.properties
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreSnapshotsTest.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoSnapshots.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreSnapshotsIT.java
  java/statestore/src/test/resources/log4j.properties
  java/trino/src/test/resources/log4j.properties
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#2579 Issue 2565 - Update version number to 0.24.0-SNAPSHOT
  java/athena/pom.xml
  java/build/pom.xml
  java/bulk-import/bulk-import-common/pom.xml
  java/bulk-import/bulk-import-runner/pom.xml
  java/bulk-import/bulk-import-starter/pom.xml
  java/bulk-import/pom.xml
  java/cdk-custom-resources/pom.xml
  java/cdk-environment/pom.xml
  java/cdk/pom.xml
  java/clients/pom.xml
  java/common/common-invoke-tables/pom.xml
  java/common/common-job/pom.xml
  java/common/common-task/pom.xml
  java/common/dynamodb-tools/pom.xml
  java/common/pom.xml
  java/compaction/compaction-core/pom.xml
  java/compaction/compaction-job-committer-lambda/pom.xml
  java/compaction/compaction-job-creation-lambda/pom.xml
  java/compaction/compaction-job-creation/pom.xml
  java/compaction/compaction-job-execution/pom.xml
  java/compaction/compaction-status-store/pom.xml
  java/compaction/compaction-task-creation/pom.xml
  java/compaction/pom.xml
  java/configuration/pom.xml
  java/core/pom.xml
  java/distribution/pom.xml
  java/garbage-collector/pom.xml
  java/ingest/ingest-batcher-core/pom.xml
  java/ingest/ingest-batcher-job-creator/pom.xml
  java/ingest/ingest-batcher-store/pom.xml
  java/ingest/ingest-batcher-submitter/pom.xml
  java/ingest/ingest-core/pom.xml
  java/ingest/ingest-runner/pom.xml
  java/ingest/ingest-starter/pom.xml
  java/ingest/ingest-status-store/pom.xml
  java/ingest/pom.xml
  java/metrics/pom.xml
  java/parquet/pom.xml
  java/pom.xml
  java/query/pom.xml
  java/query/query-core/pom.xml
  java/query/query-lambda/pom.xml
  java/query/query-runner/pom.xml
  java/sketches/pom.xml
  java/splitter/pom.xml
  java/splitter/splitter-core/pom.xml
  java/splitter/splitter-lambda/pom.xml
  java/statestore-lambda/pom.xml
  java/statestore/pom.xml
  java/system-test/pom.xml
  java/system-test/system-test-cdk/pom.xml
  java/system-test/system-test-configuration/pom.xml
  java/system-test/system-test-data-generation/pom.xml
  java/system-test/system-test-drivers/pom.xml
  java/system-test/system-test-dsl/pom.xml
  java/system-test/system-test-suite/pom.xml
  java/trino/pom.xml
  python/setup.py
Labels: one-review-required

#2578 Issue 2572 - Rename DynamoDBTransactionLogSnapshotStoreIT
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotMetadataStoreIT.java
Labels: one-review-required

#2600 Issue 2599 - State store files Arrow format
  java/statestore/pom.xml
  java/statestore/src/main/java/sleeper/statestore/StateStoreFilesArrowFormat.java
  java/statestore/src/test/java/sleeper/statestore/StateStoreFilesArrowFormatTest.java
Labels: one-review-required

#2594 Issue 2451 - Stop truncating resource names in CDK
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ConfigBucketStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/InstanceRolesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/KeepLambdaWarmStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PropertiesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryQueueStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableDataStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TopicStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogSnapshotCreationStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/VpcStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/WebSocketQueryStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/BulkImportBucketStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/cdk/src/test/java/sleeper/cdk/UtilsResourceNameInstanceIdTest.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestPropertiesStack.java
  java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SleeperInstanceTablesTest.java
Labels: pr-base-for-stacking, one-review-required

#2602 Issue 2286 - Rename remaining queues for consistency
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
Labels: one-review-required

#2603 Issue 2601 - State store partitions Arrow format
  java/statestore/src/main/java/sleeper/statestore/ArrowFormatUtils.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreFilesArrowFormat.java
  java/statestore/src/main/java/sleeper/statestore/StateStorePartitionsArrowFormat.java
  java/statestore/src/test/java/sleeper/statestore/StateStorePartitionsArrowFormatTest.java
Labels: one-review-required

#2608 Issue 2411 - Compaction failed status update
  java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterTestBase.java
  java/clients/src/test/resources/reports/compaction/job/json/mixedJobs.json
  java/clients/src/test/resources/reports/compaction/job/standard/all/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/detailed/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/range/mixedJobs.txt
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTestData.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskCommitTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTestBase.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
Labels: one-review-required

#2617 Issue 2615 - Don't purge deleted bulk import job queue in system test
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportIT.java
Labels: one-review-required

#2618 Issue 2616 - Read persistent EMR cluster name from instance properties
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PersistentEmrPlatformExecutor.java
Labels: one-review-required
