Repository gchq/sleeper, pull requests merged in 2024-01, with the labels that each got.

#1638 Issue 1605 - Fix log line to use StateStore interface instead of implementation
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
Labels: one-review-required

#1640 Issue 1639 - Fix script failures when running nightly functional test suite
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#1641 Issue 1601 - Fix JavaDoc in BasicCompactionStrategy and related classes
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/BasicCompactionStrategy.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/BasicLeafStrategy.java
Labels: one-review-required

#1600 Issue 1558 - Report on files that do not have any references
  java/clients/src/main/java/sleeper/clients/status/report/FilesStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/CVSFileStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/FileStatus.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/FileStatusCollector.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/StandardFileStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/StateStoreFilesWithNoReferences.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/StateStoreReadyForGC.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/StateStoreSnapshot.java
  java/clients/src/test/java/sleeper/clients/admin/FilesStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/StandardFileStatusReporterRecordCountTest.java
  java/clients/src/test/resources/reports/filestatus/json/filesWithNoReferencesAboveMaxCount.json
  java/clients/src/test/resources/reports/filestatus/json/filesWithNoReferencesBelowMaxCount.json
  java/clients/src/test/resources/reports/filestatus/json/leafAndMiddleFile.json
  java/clients/src/test/resources/reports/filestatus/json/oneActiveFilePerLeaf.json
  java/clients/src/test/resources/reports/filestatus/json/splitFile.json
  java/clients/src/test/resources/reports/filestatus/standard/filesWithNoReferencesAboveMaxCount.txt
  java/clients/src/test/resources/reports/filestatus/standard/filesWithNoReferencesBelowMaxCount.txt
  java/clients/src/test/resources/reports/filestatus/standard/leafAndMiddleFile.txt
  java/clients/src/test/resources/reports/filestatus/standard/oneActiveFilePerLeaf.txt
  java/clients/src/test/resources/reports/filestatus/standard/splitFile.txt
  java/core/src/main/java/sleeper/core/statestore/AllFileReferences.java
Labels: pr-stacked-middle

#1604 Issue 1559 - Update garbage collector to read file reference counts
  java/core/src/test/java/sleeper/core/statestore/FilesReportTestHelper.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStoreTest.java
  java/garbage-collector/pom.xml
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileInfoStoreIT.java
Labels: pr-stacked-middle

#1625 Issue 1560 - Remove ready for GC table
  java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBStateStoreStack.java
  java/clients/src/main/java/sleeper/clients/docker/stack/TableDockerStack.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesEmptyOutputIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestUtils.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileInfoStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStoreTest.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormat.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStoreCreator.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfo.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormatTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileInfoStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriver.java
Labels: pr-stacked-middle

#1632 Issue 1631 - Remove FileInfo.fileStatus field
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/SparkFileInfoRow.java
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/clients/src/test/resources/reports/filestatus/json/filesWithNoReferencesAboveMaxCount.json
  java/clients/src/test/resources/reports/filestatus/json/filesWithNoReferencesBelowMaxCount.json
  java/clients/src/test/resources/reports/filestatus/json/leafAndMiddleFile.json
  java/clients/src/test/resources/reports/filestatus/json/oneActiveFilePerLeaf.json
  java/clients/src/test/resources/reports/filestatus/json/splitFile.json
  java/clients/src/test/resources/reports/filestatus/standard/filesWithNoReferencesAboveMaxCount.txt
  java/clients/src/test/resources/reports/filestatus/standard/filesWithNoReferencesBelowMaxCount.txt
  java/clients/src/test/resources/reports/filestatus/standard/leafAndMiddleFile.txt
  java/clients/src/test/resources/reports/filestatus/standard/oneActiveFilePerLeaf.txt
  java/clients/src/test/resources/reports/filestatus/standard/splitFile.txt
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/SizeRatioCompactionStrategyTest.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/core/src/main/java/sleeper/core/statestore/FileInfo.java
  java/core/src/main/java/sleeper/core/statestore/FileInfoStore.java
  java/core/src/main/java/sleeper/core/statestore/SplitFileInfo.java
  java/core/src/test/java/sleeper/core/statestore/FileInfoFactory.java
  java/core/src/test/java/sleeper/core/statestore/FileInfoTest.java
  java/core/src/test/java/sleeper/core/statestore/FileInfoTestData.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/StateStoreTestBuilder.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriterUtils.java
  java/splitter/src/test/java/sleeper/splitter/SplitPartitionJobDefinitionSerDeTest.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormat.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormatTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
Labels: pr-stacked-middle

#1634 Issue 1633 - Mark files as ready for GC by using filename and partition ID instead of FileInfo
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileInfoStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStoreTest.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormat.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileInfoStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
Labels: pr-stacked-middle

#1643 Issue 1642 - Avoid checking for running ingest tasks in bulk import system tests
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/WaitForJobsDriver.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestDirectEmrServerless.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngestBatcher.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngestByQueue.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/python/SystemTestPythonBulkImport.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EksBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrServerlessBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherIT.java
Labels: one-review-required

#1650 Issue 1645 - Catch state store exceptions more consistently
  java/core/src/main/java/sleeper/core/statestore/StateStoreException.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionUtils.java
Labels: pr-base-for-stacking

#1651 Issue 1649 - System test for deploying without ingest source bucket set
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestSourceFilesDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestInstanceConfiguration.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/sourcedata/SystemTestCluster.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestNoSourceBucketIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/fixtures/SystemTestInstanceTest.java
Labels: one-review-required

#1660 Issue 1659 - Create references to source files when splitting
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/StandardFileStatusReporterRecordCountTest.java
  java/clients/src/test/resources/reports/filestatus/json/splitFile.json
  java/clients/src/test/resources/reports/filestatus/standard/splitFile.txt
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsTest.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesEmptyOutputIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesReportingIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java
  java/core/src/main/java/sleeper/core/statestore/SplitFileInfo.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/StateStoreTestBuilder.java
Labels: pr-base-for-stacking

#1681 Issue 1679 - Purge queues on test failures in PythonApiIT
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonApiIT.java
Labels: one-review-required

#1675 Issue 1667 - Set new flags explicitly for file references
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/SparkFileInfoRow.java
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/SizeRatioCompactionStrategyTest.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/core/src/main/java/sleeper/core/statestore/FileInfo.java
  java/core/src/main/java/sleeper/core/statestore/SplitFileInfo.java
  java/core/src/test/java/sleeper/core/statestore/FileInfoFactory.java
  java/core/src/test/java/sleeper/core/statestore/FileInfoTest.java
  java/core/src/test/java/sleeper/core/statestore/FileInfoTestData.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/StateStoreTestBuilder.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriterUtils.java
  java/splitter/src/test/java/sleeper/splitter/SplitPartitionJobDefinitionSerDeTest.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormat.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormatTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
Labels: pr-base-for-stacking

#1683 Issue 1665 - Remove code to split a file reference by copying the file
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionOutputFileNameFactory.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionOutputFileNameFactoryTest.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestBase.java
  java/core/src/main/java/sleeper/core/statestore/SplitFileReference.java
  java/core/src/test/java/sleeper/core/statestore/FileReferenceTest.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
Labels: one-review-required, pr-stacked-top

#1658 Issue 1653 - Differentiate between slow and expensive system tests
  code-style/checkstyle.xml
  java/pom.xml
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/PurgeQueueDriver.java
  java/system-test/system-test-suite/pom.xml
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EksBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrServerlessBulkImportIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestNoSourceBucketIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonApiIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/QueryIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/suites/NightlyFunctionalSystemTestSuite.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/suites/NightlyPerformanceSystemTestSuite.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/suites/QuickSystemTestSuite.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/AfterTestPurgeQueues.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/AfterTestPurgeQueuesTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/AfterTestReports.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/AfterTestReportsBase.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/AfterTestReportsTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/Expensive.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/PurgeQueueExtension.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/ReportingExtension.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/SleeperSystemTestExtension.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/Slow.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/SystemTest.java
  scripts/test/maven/buildDeploy.sh
  scripts/test/maven/deploy.sh
  scripts/test/maven/performanceTest.sh
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#1684 Issue 1668 - Check files have the correct jobId assigned to them in compaction job state store update
  example/full/instance.properties
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobs.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesEmptyOutputIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesReportingIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/parquet/src/main/java/sleeper/io/parquet/record/ParquetRecordWriterFactory.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/WaitForJobsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/WaitForJobsStatus.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/util/WaitForJobsStatusTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#1689 Issue 1688 - Realign file store tests
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
Labels: one-review-required, pr-stacked-top

#1690 Issue 1669 - Remove splitting compaction infrastructure
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java
  java/clients/src/main/java/sleeper/clients/deploy/RestartTasks.java
  java/clients/src/main/java/sleeper/clients/status/report/DeadLettersStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/RetryMessages.java
  java/clients/src/main/java/sleeper/clients/status/report/compaction/task/StandardCompactionTaskStatusReporter.java
  java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/task/CompactionTaskStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/task/CompactionTaskStatusReportTestHelper.java
  java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java
  java/clients/src/test/resources/reports/compaction/task/mixedTypes.json
  java/clients/src/test/resources/reports/compaction/task/mixedTypes.txt
  java/clients/src/test/resources/reports/compaction/task/multipleJobRunsOnTasks.json
  java/clients/src/test/resources/reports/compaction/task/multipleJobRunsOnTasks.txt
  java/clients/src/test/resources/reports/compaction/task/singleTaskUnfinished.json
  java/clients/src/test/resources/reports/compaction/task/singleTaskUnfinished.txt
  java/clients/src/test/resources/reports/compaction/task/unfinishedAndFinished.json
  java/clients/src/test/resources/reports/compaction/task/unfinishedAndFinished.txt
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskStatus.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskStatusesBuilder.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskType.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskStatusesBuilderTest.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/SendCompactionJobToSqs.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusFormat.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/task/QueryAllCompactionTasksIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/task/StoreCompactionTaskIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionTaskStatusStoreTestBase.java
  java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/taskcreation/RunTasks.java
  java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/taskcreation/RunTasksLambda.java
  java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/taskcreation/SafeTerminationLambda.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperScheduleRule.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTest.java
  java/core/src/main/java/sleeper/core/ContainerConstants.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/CompactionDriver.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestCompaction.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
Labels: pr-base-for-stacking

#1695 Issue 1693 - Implement splitting file references in S3StateStore
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReference.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreTestBase.java
Labels: pr-base-for-stacking

#1698 Issue 1692 - Implement splitting file references in DynamoDBStateStore
  java/core/src/main/java/sleeper/core/statestore/SplitFileReferenceRequest.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBSplitRequestsBatch.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/SplitRequestsFailedException.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
Labels: pr-base-for-stacking

#1703 Issue 1699 - Extract code for creating splitting compaction jobs and perform splits directly
  java/core/src/main/java/sleeper/core/statestore/SplitFileReferences.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
Labels: pr-base-for-stacking

#1705 Issue 1672 - Run splitting compactions before compaction jobs are created
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobs.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsTest.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestBase.java
  java/core/src/main/java/sleeper/core/statestore/SplitFileReferences.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestCompaction.java
Labels: pr-base-for-stacking

#1717 Issue 1715 - Use correct WaitForJobsDriver implementation in EmrBulkImportPerformanceIT
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/sourcedata/SystemTestCluster.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java
Labels: one-review-required

#1734 Issue 1733 - Adding logging of number of attempts and total sleep time when updating S3 state store
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
Labels: one-review-required

#1736 Issue 1674 - Log filter ranges during compaction
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
Labels: one-review-required

#1740 Issue 1727 - Decouple PartitionTree from Schema
  java/athena/src/main/java/sleeper/athena/metadata/SleeperMetadataHandler.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/dataframe/AddPartitionFunction.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/dataframe/AddPartitionIterator.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/dataframelocalsort/AddPartitionAsIntFunction.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/dataframelocalsort/AddPartitionAsIntIterator.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/rdd/SingleFileWritingIterator.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/rdd/SleeperPartitioner.java
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/rdd/WriteParquetFile.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/dataframe/AddPartitionIteratorTest.java
  java/clients/src/main/java/sleeper/clients/status/report/partitions/PartitionsStatus.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceTestBase.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobTestDataHelper.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsIT.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsTest.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesEmptyOutputIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestData.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
  java/core/src/main/java/sleeper/core/partition/PartitionTree.java
  java/core/src/main/java/sleeper/core/partition/PartitionsFromSplitPoints.java
  java/core/src/test/java/sleeper/core/partition/PartitionTreeNearestCommonAncestorTest.java
  java/core/src/test/java/sleeper/core/partition/PartitionTreeTest.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilderTest.java
  java/core/src/test/java/sleeper/core/statestore/FileReferenceFactory.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/FixedPartitionStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryPartitionStoreTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngestCoordinator.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngesterIntoPartitions.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorLocalStackIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsLocalStackIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/query/src/main/java/sleeper/query/executor/QueryExecutor.java
  java/query/src/test/java/sleeper/query/executor/QueryExecutorTest.java
  java/splitter/src/test/java/sleeper/splitter/FindPartitionsToSplitTest.java
  java/splitter/src/test/java/sleeper/splitter/SplitPartitionIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/DirectQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/QueryCreator.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestPartitioning.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/FileReferenceSystemTestHelper.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/PartitionsTestHelper.java
Labels: one-review-required

#1732 Issue 1731 - Align update time fields in FileReference and AllReferencesToAFile
  java/clients/src/main/java/sleeper/clients/status/report/compaction/job/JsonCompactionJobStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/compaction/task/JsonCompactionTaskStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/JsonFileStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/StandardFileStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/ingest/batcher/JsonIngestBatcherReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/ingest/job/JsonIngestJobStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/ingest/task/JsonIngestTaskStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/query/JsonQueryTrackerReporter.java
  java/clients/src/main/java/sleeper/clients/util/ClientsGsonConfig.java
  java/core/src/main/java/sleeper/core/statestore/AllReferencesToAFile.java
  java/core/src/main/java/sleeper/core/statestore/FileReference.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceSerDe.java
  java/core/src/main/java/sleeper/core/util/GsonConfig.java
  java/core/src/test/java/sleeper/core/statestore/FileReferenceTest.java
  java/core/src/test/java/sleeper/core/statestore/FilesReportTestHelper.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
  java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBAttributes.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/ECSIngestTaskIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceFormat.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/json/TaskStatusJson.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/json/TasksJson.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/json/TasksSummaryJson.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestSummaryTable.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/WaitForJobsStatus.java
Labels: one-review-required

#1719 Issue 1718 - Prevent adding a split file reference to the state store using atomicallyUpdateFilesToReadyForGCAndCreateNewActiveFiles
  java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
Labels: pr-base-for-stacking

#1729 Issue 1720 - Only split files references with no job ID assigned
  java/core/src/main/java/sleeper/core/statestore/SplitFileReferences.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/SplitFileReferencesTest.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
Labels: pr-stacked-middle

#1735 Issue 1730 - Throw exception if S3 state store update fails
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionId.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionIdStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3StateStoreDataFile.java
  java/statestore/src/test/java/sleeper/statestore/s3/InMemoryS3RevisionIdStore.java
  java/statestore/src/test/java/sleeper/statestore/s3/InMemoryS3StateStoreDataFiles.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreDataFileTest.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
Labels: pr-base-for-stacking

#1749 Issue 1748 - Fix compilation in CompactionIT
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionIT.java
Labels: one-review-required
