Repository gchq/sleeper, pull requests merged in 2024-07, with the labels that each got.

#2778 Issue 2777 - Introduce compaction job status update events
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitter.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobFailedEvent.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobFinishedEvent.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStartedEvent.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitterTestBase.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByPeriodIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByTaskIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusUnfinishedIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobExpiryIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/util/WaitForJobsStatusTest.java
Labels: pr-base-for-stacking

#2786 Issue 2766 - Store separate compaction commits in DynamoDB
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobRunIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
Labels: pr-base-for-stacking

#2787 Issue 2785 - Report job run ID to compaction status store
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitRequest.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitter.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitterOrSendToLambda.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/StateStoreWaitForFiles.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/TimedOutWaitingForFileAssignmentsException.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitRequestSerDeTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitRequestSerDeTest.shouldSerialiseCompactionJobCommitRequest.approved.txt
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitterTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitterTestBase.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskAssignFilesTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTerminateTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/StateStoreWaitForFilesTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionJobCommitterOrSendToLambda.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/SqsCompactionQueueHandler.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/StateStoreWaitForFilesTestHelper.java
  java/core/src/main/java/sleeper/core/record/process/ProcessRunTime.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitRequestDeserialiserTest.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java
Labels: pr-stacked-top

#2788 Issue 2767 - Create status updates for compaction commit
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitRequest.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitter.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitterOrSendToLambda.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/statestore-commit/pom.xml
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitter.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java
  java/statestore-lambda/src/main/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambda.java
Labels: pr-base-for-stacking

#2792 Issue 2768 - Report on compaction split commits
  java/clients/src/main/java/sleeper/clients/status/report/compaction/job/StandardCompactionJobStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/job/StandardProcessRunReporter.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterTestBase.java
  java/clients/src/test/resources/reports/compaction/job/json/mixedJobs.json
  java/clients/src/test/resources/reports/compaction/job/json/mixedUnfinishedJobs.json
  java/clients/src/test/resources/reports/compaction/job/standard/all/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/detailed/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/range/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/unfinished/mixedUnfinishedJobs.txt
Labels: pr-stacked-top

#2812 Issue 2811 - Use IngestFactory in coordinator tests
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientTestBase.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/DirectPartitionFileWriterFactory.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/DirectWriteBackedByArrowTestBase.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorFileWritingStrategyIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowRecordWriterAcceptingRecordListIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorFactory.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorTestHelper.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorTestParameters.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/TestIngestType.java
Labels: pr-base-for-stacking

#2813 Issue 2793 - Remove duplication between ingest job and coordinator tests
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
Labels: pr-stacked-top

#2815 Issue 2814 - Report on compactions that fail before they start
  java/core/src/main/java/sleeper/core/record/process/status/ProcessRun.java
  java/core/src/test/java/sleeper/core/record/process/status/ProcessRunsTest.java
  java/core/src/test/java/sleeper/core/record/process/status/ProcessStatusUpdateTestHelper.java
Labels: one-review-required

#2825 Issue 2809 - Build a new Hadoop configuration for each operation
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
Labels: one-review-required

#2841 Issue 2840 - Add commit time to commit status update
  java/clients/src/main/java/sleeper/clients/status/report/compaction/job/StandardCompactionJobStatusReporter.java
  java/clients/src/test/resources/reports/compaction/job/json/mixedJobs.json
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobCommittedEvent.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobCommittedStatus.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTestData.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobRunIdIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
  java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitter.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java
Labels: pr-base-for-stacking

#2854 Issue 2846 - Separate Hadoop config per parallel query
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/DirectQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SQSQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
Labels: one-review-required

#2879 Issue 2878 - Assume roles with built in AWS credentials providers
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/util/AssumeSleeperRole.java
  java/clients/src/main/java/sleeper/clients/util/AssumeSleeperRoleHadoop.java
  java/clients/src/main/java/sleeper/clients/util/AssumeSleeperRoleV1.java
  java/clients/src/main/java/sleeper/clients/util/AssumeSleeperRoleV2.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/InstanceIngestSession.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/InstanceAdminDriversWithRefresh.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/InstanceAdminDriversWithRefreshTest.java
  scripts/functions/systemTestUtils.sh
  scripts/functions/test/testSystemTestUtils.sh
Labels: one-review-required

#2884 Issue 2883 - Remove full Maven build from CLI build
  scripts/cli/buildAll.sh
Labels: one-review-required

#2903 Issue 2899 - Use Bash as the entrypoint for CLI Docker images
  scripts/cli/builder/Dockerfile
  scripts/cli/environment/Dockerfile
Labels: one-review-required

#2911 Issue 2909 - Stop system processes before deleting stacks in TearDownMavenSystemTest
  java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java
Labels: one-review-required

#2866 Issue 2800 - Update NOTICES.md for 0.24.0
  NOTICES
Labels: one-review-required

#2921 Issue 2874 - Apply async commit property in WriteRandomDataDirect
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java
Labels: one-review-required

#2919 Issue 2910 - Report tear down failures in nightly test output
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java
  scripts/test/nightly/runTests.sh
Labels: one-review-required

#2939 Issue 2922 - Close input iterator in IngestJobRunner
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java
Labels: one-review-required

#2945 Issue 2944 - Added splitpoint files to allow system tests with 16384, 32768, 65536…
  scripts/test/splitpoints/string/131072-partitions.txt
  scripts/test/splitpoints/string/16384-partitions.txt
  scripts/test/splitpoints/string/32768-partitions.txt
  scripts/test/splitpoints/string/65536-partitions.txt
Labels: one-review-required

#2955 Issue 2953 - Commit ingest job asynchronously by default
  example/full/instance.properties
  example/full/table.properties
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobQueueConsumerTestBase.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemoryTestInstance.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#2951 Issue 2391 - Limit number of compactions to create in a single lambda invocation
  example/full/instance.properties
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJob.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobFactory.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/strategy/CompactionStrategy.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsTest.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#2973 Issue 2967 - Split ingest job status store update into two requests
  java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
Labels: one-review-required

#2972 Issue 2966 - Do not report on failure waiting for compaction input file assignment
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskAssignFilesTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
Labels: one-review-required

#2943 Issue 2900 - Async commit of compaction file assignment
  example/full/instance.properties
  example/full/table.properties
  java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
  java/clients/src/main/java/sleeper/clients/status/update/CreateCompactionJobsClient.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobIdAssignmentCommitRequest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobIdAssignmentCommitRequestSerDeTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobIdAssignmentCommitRequestTestHelper.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsLambda.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/commit/AssignJobIdToFiles.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsIT.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsTest.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsTestUtils.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitRequestDeserialiserTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemoryTestInstance.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  scripts/templates/instanceproperties.template
Labels: pr-stacked-top

#2976 Issue 2969 - Store add files commit requests in S3 if they are too large
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/commit/AddFilesToStateStore.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/commit/AddFilesToStateStoreIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/InstanceIngestSession.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java
Labels: pr-stacked-top

#2985 Issue 2984 - Grant async commit permission for direct ingest
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreCommitterStack.java
Labels: pr-base-for-stacking, one-review-required

#2986 Issue 2983 - Distinguish system tests from integration tests
  docs/11-dev-guide.md
  docs/13-system-tests.md
  java/pom.xml
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnEC2ST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnFargateST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EksBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrServerlessBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestNoSourceBucketST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonIngestIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonIngestST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonQueryST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/QueryST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/TableMetricsST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/CompactionOnEC2ST.MergeFiles.shouldCompactFilesUsingBasicCompactionStrategy.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/CompactionOnEC2ST.MergeFiles.shouldCompactFilesUsingDefaultCompactionStrategy.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/CompactionOnEC2ST.MergePartialFiles.shouldCompactOneFileFromRootIntoExistingFilesOnLeafPartitions.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/CompactionOnEC2ST.MergePartialFiles.shouldCompactOneFileIntoExistingFilesOnLeafPartitions.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/CompactionOnFargateST.MergeFiles.shouldCompactFilesUsingBasicCompactionStrategy.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/CompactionOnFargateST.MergeFiles.shouldCompactFilesUsingDefaultCompactionStrategy.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/CompactionOnFargateST.MergePartialFiles.shouldCompactOneFileFromRootIntoExistingFilesOnLeafPartitions.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/CompactionOnFargateST.MergePartialFiles.shouldCompactOneFileIntoExistingFilesOnLeafPartitions.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/GarbageCollectionST.shouldGarbageCollectFilesAfterCompaction.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/MultipleTablesST.shouldCompactAndGCMultipleTables.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/MultipleTablesST.shouldSplitPartitionsOfMultipleTables.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/PartitionSplittingST.shouldSplitPartitionsWith100RecordsAndThresholdOf20.approved.txt
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/suites/NightlyFunctionalSystemTestSuite.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/suites/NightlyPerformanceSystemTestSuite.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/SystemTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/SystemTestSuite.java
Labels: pr-base-for-stacking, one-review-required

#2981 2894 update names of metrics
  java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java
  java/core/src/main/java/sleeper/core/metrics/TableMetrics.java
  java/core/src/test/java/sleeper/core/metrics/TableMetricsTest.java
  java/metrics/src/main/java/sleeper/metrics/TableMetricsLambda.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/metrics/AwsTableMetricsDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/metrics/TableMetricsDslTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/TableMetricsST.java
Labels: one-review-required

#2982 Issue 2682 - Compaction performance on EC2
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceST.java
Labels: one-review-required

#2988 Issue 2987 - Use amazoncorretto:11-al2023-headless image
  java/bulk-import/bulk-import-runner/docker/eks-native/Dockerfile
  java/compaction/compaction-job-execution/docker/Dockerfile
  java/ingest/ingest-runner/docker/Dockerfile
  java/system-test/system-test-data-generation/docker/Dockerfile
Labels: pr-base-for-stacking, one-review-required

#2989 Issue 2968 - Wait for commit after system test cluster direct ingest
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/SystemTestCluster.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceST.java
Labels: one-review-required, pr-stacked-top

#2963 Issue 2857 - Only build Sleeper CLI images against develop
  .devcontainer/devcontainer.json
  .github/scripts/planCliBuild.sh
  .github/workflows/docker-cli-image.yaml
  .github/workflows/docker-cli-main.yaml
  docs/01-getting-started.md
  java/cdk-environment/src/main/resources/cloud-init.sh
  scripts/cli/install.sh
  scripts/cli/runInDocker.sh
  scripts/test/nightly/README.md
  scripts/test/nightly/crontab.example
Labels: pr-base-for-stacking, one-review-required

#2994 Issue 652 - Preserve file ownership in CLI
  .devcontainer/devcontainer.json
  scripts/cli/builder/Dockerfile
  scripts/cli/environment/Dockerfile
  scripts/cli/runInDocker.sh
  scripts/cli/runner/Dockerfile
Labels: one-review-required
