Repository gchq/sleeper, pull requests merged in 2024-09, with the labels that each got.

#3178 Issue 3134 - High throughput FIFO queue for state store committer
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreCommitterStack.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSleeperInstanceDriver.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
Labels: one-review-required

#3179 Issue 3175 - Wait for ingest task to start job when invoked
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTerminateTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobMessageHandler.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/task/IngestTask.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestBatcherDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsInvokeIngestTasksDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/IngestBatcherDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/InvokeIngestTasks.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/InvokeIngestTasksDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcher.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestByQueue.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/python/SystemTestPythonIngest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/SystemTestCluster.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/InvokeIngestTasksTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcherTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/reporting/SystemTestReportingTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemoryTestInstance.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryDirectIngestDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestBatcherDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
Labels: pr-base-for-stacking, one-review-required

#3186 Issue 3185 - Fix async commit property
  java/clients/src/main/java/sleeper/clients/admin/InstanceConfigurationScreen.java
  java/clients/src/main/java/sleeper/clients/admin/properties/PropertiesDiff.java
  java/clients/src/main/java/sleeper/clients/admin/properties/PropertyDiff.java
  java/clients/src/main/java/sleeper/clients/admin/properties/UpdatePropertiesRequest.java
  java/clients/src/main/java/sleeper/clients/admin/properties/UpdatePropertiesWithTextEditor.java
  java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
  java/clients/src/main/java/sleeper/clients/util/ComparePropertiesTemplates.java
  java/clients/src/test/java/sleeper/clients/admin/properties/PropertiesDiffTest.java
  java/clients/src/test/java/sleeper/clients/admin/properties/PropertiesDiffTestHelper.java
  java/configuration/src/main/java/sleeper/configuration/properties/PropertyGroup.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertiesInvalidException.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertiesValidationReporter.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertyIndex.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertyValues.java
  java/configuration/src/main/java/sleeper/configuration/properties/format/GeneratePropertiesTemplates.java
  java/configuration/src/main/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinter.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/InstanceProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyComputeValue.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyDefaultValue.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
  java/configuration/src/main/java/sleeper/configuration/properties/validation/DefaultAsyncCommitBehaviour.java
  java/configuration/src/main/java/sleeper/configuration/properties/validation/EmrInstanceTypeConfig.java
  java/configuration/src/test/java/sleeper/configuration/properties/DummySleeperProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/DummyTableProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesAsyncCommitsTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/QuinFunction.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/ResetProperties.java
Labels: one-review-required, pr-stacked-middle

#3168 Issue 2850 - Test Rust compaction from Java
  .github/workflows/chunk-rust.yaml
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionRunnerFactory.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/DefaultCompactionRunnerFactory.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/JavaCompactionRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerEmptyOutputIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestBase.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestData.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestUtils.java
  java/compaction/compaction-rust/pom.xml
  java/compaction/compaction-rust/src/main/java/sleeper/compaction/rust/RustBridge.java
  java/compaction/compaction-rust/src/main/java/sleeper/compaction/rust/RustCompactionRunner.java
  java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerIT.java
  java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerLocalStackIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  rust/compaction/Cargo.toml
  rust/compaction/src/aws_s3.rs
  rust/compaction/src/details.rs
  rust/compaction/src/lib.rs
  rust/compactor/src/bin/main.rs
Labels: pr-base-for-stacking

#3174 Issue 3173 - Assert on sketches in compaction tests
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerEmptyOutputIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestBase.java
  java/compaction/compaction-rust/pom.xml
  java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerIT.java
  java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerLocalStackIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorLocalStackIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsLocalStackIT.java
  java/sketches/src/test/java/sleeper/sketches/SketchSerialiserTest.java
  java/sketches/src/test/java/sleeper/sketches/s3/SketchesSerDeToS3IT.java
  java/sketches/src/test/java/sleeper/sketches/testutils/AssertQuantiles.java
  java/sketches/src/test/java/sleeper/sketches/testutils/ExpectedQuantile.java
  java/sketches/src/test/java/sleeper/sketches/testutils/SketchDeciles.java
  java/sketches/src/test/java/sleeper/sketches/testutils/SketchesDeciles.java
Labels: pr-stacked-top

#3187 Issue 3176 - Retry on throttling when updating committer local state
  java/statestore-commit/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-commit/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/statestore-lambda/src/main/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambda.java
Labels: pr-base-for-stacking, one-review-required

#3194 3193 State Store Committer throughput lower than expected after high throughput queue
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
Labels: one-review-required

#3188 Issue 3089 - Allow setting no optional stacks
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertyValues.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/UserDefinedInstancePropertyImpl.java
  java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
Labels: pr-base-for-stacking, one-review-required

#3189 Issue 3182 - Rename Rust compaction method property value
  example/full/instance.properties
  example/full/table.properties
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/DefaultCompactionRunnerFactory.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/validation/CompactionMethod.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionST.java
  scripts/templates/instanceproperties.template
Labels: one-review-required, pr-stacked-middle

#3196 Issue 2409 - Report counts of compaction jobs with multiple runs
  java/clients/src/main/java/sleeper/clients/status/report/compaction/job/StandardCompactionJobStatusReporter.java
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/resources/reports/compaction/job/standard/all/jobWithMultipleRuns.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/jobsWithLargeAndDecimalStatistics.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/multipleInputFiles.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/noJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/range/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/range/noJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/unfinished/mixedUnfinishedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/unfinished/noJobs.txt
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java
Labels: pr-stacked-middle

#3216 Issue 3197 - Support compaction input files assigned event in status store
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobInputFilesAssignedStatus.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTestData.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
  java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobCreatedIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
  java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
Labels: pr-base-for-stacking, one-review-required

#3218 Issue 3198 - Submit compaction files assigned event
  java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/commit/AssignJobIdToFiles.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsTest.java
  java/statestore-commit/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-commit/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
Labels: one-review-required, pr-stacked-middle

#3233 Issue 3232 - Report compaction file assignment delay statistics
  java/clients/src/main/java/sleeper/clients/status/report/compaction/job/StandardCompactionJobStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/job/DelayStatistics.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterTestBase.java
  java/clients/src/test/java/sleeper/clients/status/report/job/DelayStatisticsTest.java
  java/clients/src/test/resources/reports/compaction/job/json/jobsWithLargeAndDecimalStatistics.json
  java/clients/src/test/resources/reports/compaction/job/standard/all/jobWithMultipleRuns.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/jobsWithLargeAndDecimalStatistics.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/multipleInputFiles.txt
  java/clients/src/test/resources/reports/compaction/job/standard/all/noJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/detailed/jobsWithLargeAndDecimalStatistics.txt
  java/clients/src/test/resources/reports/compaction/job/standard/range/mixedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/range/noJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/unfinished/mixedUnfinishedJobs.txt
  java/clients/src/test/resources/reports/compaction/job/standard/unfinished/noJobs.txt
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusStatisticsTest.java
  java/core/src/main/java/sleeper/core/util/DurationStatistics.java
  java/core/src/test/java/sleeper/core/util/DurationStatisticsTest.java
Labels: pr-stacked-top

#3235 Configure Reserved & Max concurrency for Lambdas scaling across sleeper tables
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/StateStoreCommitterStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogSnapshotStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogTransactionStack.java
  java/configuration/src/main/java/sleeper/configuration/Utils.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertyValues.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/GarbageCollectionProperty.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java
  java/configuration/src/test/java/sleeper/configuration/UtilsTest.java
  java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking, one-review-required

#3248 Issue 3247 - Avoid EMR rate limit in Maven teardown script
  java/clients/src/main/java/sleeper/clients/status/report/ingest/job/PersistentEMRStepCount.java
  java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
  java/clients/src/main/java/sleeper/clients/teardown/TerminateEMRClusters.java
  java/clients/src/main/java/sleeper/clients/util/EmrUtils.java
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/PersistentEMRStepCountIT.java
  java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java
  java/core/src/main/java/sleeper/core/util/RateLimitUtils.java
  java/core/src/main/java/sleeper/core/util/StaticRateLimit.java
  java/core/src/test/java/sleeper/core/util/StaticRateLimitTest.java
Labels: one-review-required

#3250 Issue 3217 - System test throughput of all types of state store commit
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobFactory.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionOutputFileNameFactory.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/strategy/impl/SizeRatioLeafStrategy.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
  java/core/src/main/java/sleeper/core/util/SplitIntoBatches.java
  java/core/src/test/java/sleeper/core/statestore/FilesReportTestHelper.java
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinter.java
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldPrintFilesAssignedToJobs.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.DisplayActiveFilesByPartition.shouldNumberPartialFilesInOrderOfAppearanceWhenLargerFileAppearsLater.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.DisplayActiveFilesByPartition.shouldOrderFilesByPartitionLocationInTree.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.DisplayActiveFilesByPartition.shouldPrintTwoPartialFilesWithSameNumberOfRecordsWhenBothHaveADifferentNumberOfRecordsOnADifferentPartition.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.DisplayActiveFilesByPartition.shouldPrintTwoPartialFilesWithSameNumberOfRecordsWhenOneHasOtherRecordsOnADifferentPartition.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.DisplayActiveFilesByPartition.shouldPrintWholeFileBeforePartialFileWithSameNumberOfRecordsInSamePartition.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.DisplayActiveFilesByPartition.shouldRenamePartitionsByLocation.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.DisplayActiveFilesByPartition.shouldSortFilesByNumberOfRecordsWithinPartition.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.DisplayActiveFilesByPartition.shouldSortPartialFilesByNumberOfRecordsWithinPartition.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.java
  java/core/src/test/java/sleeper/core/util/SplitIntoBatchesTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestTableFiles.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitMessageFactory.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitterDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommits.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryStateStoreCommitter.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
Labels: one-review-required

#3291 Issue 3290 - Load TableProperties and Partition in CompactionTask
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionRunner.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionRunnerFactory.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/DefaultCompactionRunnerFactory.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/JavaCompactionRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestBase.java
  java/compaction/compaction-rust/src/main/java/sleeper/compaction/rust/RustCompactionRunner.java
  java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerIT.java
  java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerLocalStackIT.java
  java/core/src/main/java/sleeper/core/statestore/PartitionStore.java
Labels: pr-base-for-stacking

#3324 Issue 3267 - Upgrade ECR client to SDK v2
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/AdminClient.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployExistingInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/clients/src/main/java/sleeper/clients/teardown/RemoveECRRepositories.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownClients.java
  java/clients/src/main/java/sleeper/clients/util/EcrRepositoryCreator.java
  java/clients/src/test/java/sleeper/clients/testutil/ClientWiremockTestHelper.java
  java/common/common-task/src/test/java/sleeper/task/common/WiremockTestHelper.java
  java/configuration/pom.xml
  java/configuration/src/main/java/sleeper/configuration/utils/AwsV2ClientHelper.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/CleanUpDeletedSleeperInstances.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperInstanceDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSystemTestDeploymentDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
Labels: pr-base-for-stacking

#3325 Issue 3282 - Upgrade CloudWatch Events client to SDK v2
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/status/update/PauseSystem.java
  java/clients/src/main/java/sleeper/clients/status/update/RestartSystem.java
  java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownClients.java
  java/clients/src/test/java/sleeper/clients/testutil/ClientWiremockTestHelper.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsSnapshotsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
Labels: pr-stacked-middle

#3326 Issue 3276 - Upgrade EMR client to SDK v2
  java/bulk-import/bulk-import-starter/pom.xml
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceConfiguration.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceGroups.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutor.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PersistentEmrPlatformExecutor.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PlatformExecutor.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutorTest.java
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/AdminClient.java
  java/clients/src/main/java/sleeper/clients/status/report/IngestJobStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/ingest/job/PersistentEMRStepCount.java
  java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
  java/clients/src/main/java/sleeper/clients/teardown/TearDownClients.java
  java/clients/src/main/java/sleeper/clients/teardown/TerminateEMRClusters.java
  java/clients/src/main/java/sleeper/clients/util/EmrUtils.java
  java/clients/src/test/java/sleeper/clients/testutil/ClientWiremockTestHelper.java
  java/common/common-task/src/test/java/sleeper/task/common/WiremockTestHelper.java
  java/system-test/system-test-drivers/pom.xml
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestReportsDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
Labels: pr-stacked-top

#3317 Issue 3302 - Log partition split checks
  .vscode/settings.json
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/admin/PartitionsStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/status/report/PartitionsStatusReport.java
  java/clients/src/main/java/sleeper/clients/status/report/partitions/PartitionsStatusReporter.java
  java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusReportIT.java
  java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusReportTest.java
  java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusTest.java
  java/core/src/main/java/sleeper/core/partition/PartitionTree.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/find/FindPartitionsToSplit.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/find/PartitionSplitCheck.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/status/PartitionStatus.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/status/PartitionsStatus.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/find/FindPartitionsToSplitTest.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/status/PartitionsStatusTest.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/status/PartitionsStatusTestHelper.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/partitioning/AwsPartitionReportDriver.java
Labels: pr-base-for-stacking

#3354 Issue 3353 - Merge GitHub Actions workflows
  .github/config/chunks.yaml
  .github/workflows/check-status.yaml
  .github/workflows/chunk-athena.yaml
  .github/workflows/chunk-clients-cdk.yaml
  .github/workflows/chunk-clients.yaml
  .github/workflows/chunk-common.yaml
  .github/workflows/chunk-compaction.yaml
  .github/workflows/chunk-data.yaml
  .github/workflows/chunk-ingest-common.yaml
  .github/workflows/chunk-ingest-runner.yaml
  .github/workflows/chunk-ingest.yaml
  .github/workflows/chunk-query.yaml
  .github/workflows/chunk-statestore.yaml
  .github/workflows/chunk-trino.yaml
  .github/workflows/java-status.yaml
  java/pom.xml
Labels: one-review-required

#3367 Issue 3359 - Remove AWS SDK v2 from lambdas
  java/clients/src/main/java/sleeper/clients/AdminClient.java
  java/clients/src/main/java/sleeper/clients/status/report/IngestJobStatusReport.java
  java/clients/src/main/java/sleeper/clients/util/AwsV2ClientHelper.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/AwsV2ClientHelper.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/configuration/pom.xml
Labels: one-review-required

#3372 Issue 3371 - Fix passing empty optional stacks to CDK
  java/clients/src/main/java/sleeper/clients/deploy/UploadDockerImages.java
  java/core/src/main/java/sleeper/core/properties/SleeperProperties.java
  java/core/src/test/java/sleeper/core/properties/SleeperPropertiesTest.java
  java/core/src/test/java/sleeper/core/properties/validation/OptionalStackTest.java
Labels: one-review-required

#3374 Issue 3373 - Fix BulkImportStarterLambda loading instance properties
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
  java/clients/src/main/java/sleeper/clients/deploy/UploadDockerImages.java
  java/core/src/main/java/sleeper/core/properties/SleeperProperties.java
  java/core/src/test/java/sleeper/core/properties/SleeperPropertiesTest.java
  java/core/src/test/java/sleeper/core/properties/validation/OptionalStackTest.java
Labels: one-review-required

#3379 Issue 3378 - Fix teardown scripts
  java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java
Labels: pr-base-for-stacking, one-review-required

#3377 Issue 3376 - Configure Maven system tests from template
  java/pom.xml
  java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
  java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestStandaloneProperties.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSystemTestResources.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestParameters.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/SystemTestParametersTestHelper.java
  scripts/test/deployAll/system-test-instance.properties
  scripts/test/maven/deployTest.sh
  scripts/test/maven/system-test-standalone.properties
Labels: pr-base-for-stacking

#3388 Issue 3387 - Fix reading no instances in EC2InstanceDetails
  java/common/common-task/src/main/java/sleeper/task/common/EC2InstanceDetails.java
  java/common/common-task/src/test/java/sleeper/task/common/EC2InstanceDetailsIT.java
Labels: one-review-required
