Repository gchq/sleeper, pull requests merged in 2024-03, with the labels that each got.

#1949 Issue 1948 - Synchronize InMemorySleeperTablesDriver.addTable
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperTablesDriver.java
Labels: one-review-required

#1944 Issue 1940 - Add in memory test for partition splitting system test DSL
  java/splitter/splitter-core/src/main/java/sleeper/splitter/SplitMultiDimensionalPartitionImpl.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/SplitPartition.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/SplitPartitionIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/partitioning/AwsPartitionSplittingDriver.java
  java/system-test/system-test-dsl/pom.xml
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/SystemTestPartitioning.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/partitioning/PartitionSplittingTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryDirectIngestDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionFileWriter.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionSplittingDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySketchesStore.java
Labels: pr-base-for-stacking, one-review-required

#1943 Issue 1936 - Collect garbage collection failures
  java/garbage-collector/src/main/java/sleeper/garbagecollector/FailedGarbageCollectionException.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorLambda.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/TableFilesDeleted.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryGarbageCollectionDriver.java
Labels: pr-base-for-stacking

#1950 Issue 1385 - Parallelise creation of compaction jobs
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/clients/src/main/java/sleeper/clients/teardown/WaitForS3BucketToEmpty.java
  java/clients/src/test/java/sleeper/clients/teardown/WaitForS3BucketToEmptyIT.java
  java/clients/src/test/java/sleeper/clients/teardown/WaitForStackToDeleteIT.java
  java/common-job/src/main/java/sleeper/job/common/RunECSTasks.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsLambda.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsSQSLambda.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsTriggerLambda.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/core/src/main/java/sleeper/core/util/PollWithRetries.java
  java/core/src/test/java/sleeper/core/util/PollWithRetriesTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/CompactionDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/WaitForCompactionJobCreation.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/IngestSourceFilesContext.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/gc/GarbageCollectionTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/partitioning/PartitionSplittingTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySourceFilesDriver.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
Labels: pr-stacked-top

#1973 Issue 1970 - Fix incorrect class name in RecordsProcessed toString method
  java/core/src/main/java/sleeper/core/record/process/RecordsProcessed.java
Labels: one-review-required

#1991 Issue 1990 - Assert on unreferenced files in system tests
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinter.java
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldOrderFilesByPartitionLocationInTree.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldPrintFilesOnLeaves.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldPrintMultipleFilesInPartition.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldPrintPartialFiles.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldRenamePartitionsByLocation.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.MultipleTables.shouldPrintDifferentFilesForOneTable.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.MultipleTables.shouldPrintFilesOnceWhenTwoTablesAreIdentical.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.MultipleTables.shouldPrintOnlyOneTable.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestTableFiles.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/partitioning/PartitionSplittingTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/PartitionsTestHelper.java
Labels: one-review-required

#1974 Issue 1782 - Create WebSocketQueryStack
  docs/07-data-retrieval.md
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryQueueStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/WebSocketQueryStack.java
  scripts/test/deployAll/system-test-instance.properties
Labels: one-review-required

#1993 Issue 1992 - Give partial files numbers in test assertions
  java/core/src/test/java/sleeper/core/statestore/FilesReportTestHelper.java
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinter.java
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldNumberPartialFilesInOrderOfAppearanceWhenLargerFileAppearsLater.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldPrintMultipleFilesInPartition.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldPrintPartialAndWholeFiles.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldPrintPartialFiles.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldSortFilesByNumberOfRecordsWithinPartition.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.ActiveFiles.shouldSortPartialFilesByNumberOfRecordsWithinPartition.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.AllFiles.shouldPrintFileSplitAcrossPartitions.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.AllFiles.shouldPrintOnlyUnreferencedFiles.approved.txt
  java/core/src/test/java/sleeper/core/testutils/printers/FileReferencePrinterTest.java
Labels: one-review-required

#2002 Issue 1960 - Add properties for table batching lambdas memory & timeout
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#2008 Issue 1937 - Validate indentation and unnecessary semicolons in checkstyle
  code-style/checkstyle-idea/checkstyle.xml
  code-style/checkstyle.xml
  code-style/eclipse-style.xml
  java/build/src/main/java/sleeper/build/maven/dependencydraw/DrawDependencyGraph.java
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactSortedFilesTestData.java
  java/configuration/src/main/java/sleeper/configuration/properties/table/CompressionCodec.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsTestBase.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
  java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/sketches/src/test/java/sleeper/sketches/testutils/AssertQuantiles.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
Labels: one-review-required

#2054 Issue 2053 - Checkstyle checks for existing Javadoc
  .vscode/settings.json
  code-style/checkstyle-idea/checkstyle.xml
  code-style/checkstyle.xml
  code-style/eclipse-style.xml
  java/athena/src/main/java/sleeper/athena/metadata/SleeperMetadataHandler.java
  java/athena/src/main/java/sleeper/athena/record/SleeperRecordHandler.java
  java/athena/src/test/java/sleeper/athena/record/IteratorApplyingRecordHandlerIT.java
  java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/ConfigurationUtils.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PersistentEmrPlatformExecutor.java
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
  java/clients/src/main/java/sleeper/clients/status/report/TrackedQueryProgressReport.java
  java/common-task/src/main/java/sleeper/task/common/EC2Scaler.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJob.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/strategy/impl/BasicCompactionStrategy.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/strategy/impl/BasicLeafStrategy.java
  java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
  java/configuration/src/main/java/sleeper/configuration/properties/instance/SleeperProperty.java
  java/core/src/main/java/sleeper/core/iterator/CloseableIterator.java
  java/core/src/main/java/sleeper/core/iterator/WrappedIterator.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngestCoordinator.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriterUtils.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/RecordBatch.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arraylist/ArrayListRecordBatch.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordWriter.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/RecordIteratorFromArrowStreamReader.java
  java/pom.xml
  java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/QueryExecutor.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperTablesDriver.java
Labels: pr-base-for-stacking

#2081 Issue 2062 - Update location of instance properties in config bucket for Python
  python/src/sleeper/sleeper.py
Labels: pr-base-for-stacking

#2056 Issue 2055 - Checkstyle check for summary fragment
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-idea/checkstyle.xml
  code-style/checkstyle-suppressions.xml
  code-style/checkstyle.xml
Labels: pr-base-for-stacking, one-review-required

#2076 Issue 2068 - Common & clients chunks Javadoc summary fragments
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-suppressions.xml
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/FileStatusCollector.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/JsonFileStatusReporter.java
  java/clients/src/main/java/sleeper/clients/status/report/filestatus/StandardFileStatusReporter.java
  java/common-job/src/main/java/sleeper/job/common/action/ChangeMessageVisibilityTimeoutAction.java
  java/common-job/src/main/java/sleeper/job/common/action/DeleteMessageAction.java
  java/common-job/src/main/java/sleeper/job/common/action/thread/PeriodicActionRunnable.java
  java/common-task/src/main/java/sleeper/task/common/EC2InstanceDetails.java
  java/common-task/src/main/java/sleeper/task/common/EC2Scaler.java
  java/configuration/src/main/java/sleeper/configuration/properties/validation/IngestFileWritingStrategy.java
  java/core/src/main/java/sleeper/core/iterator/ConcatenatingIterator.java
  java/core/src/main/java/sleeper/core/iterator/IteratorException.java
  java/core/src/main/java/sleeper/core/iterator/MergingIterator.java
  java/core/src/main/java/sleeper/core/iterator/SortedRecordIterator.java
  java/core/src/main/java/sleeper/core/iterator/impl/AdditionIterator.java
  java/core/src/main/java/sleeper/core/iterator/impl/AgeOffIterator.java
  java/core/src/main/java/sleeper/core/iterator/impl/SecurityFilteringIterator.java
  java/core/src/main/java/sleeper/core/key/Key.java
  java/core/src/main/java/sleeper/core/partition/PartitionSerDe.java
  java/core/src/main/java/sleeper/core/partition/PartitionTree.java
  java/core/src/main/java/sleeper/core/range/RangeCanonicaliser.java
  java/core/src/main/java/sleeper/core/range/RegionCanonicaliser.java
  java/core/src/main/java/sleeper/core/range/RegionSerDe.java
  java/core/src/main/java/sleeper/core/record/CloneRecord.java
  java/core/src/main/java/sleeper/core/record/RecordComparator.java
  java/core/src/main/java/sleeper/core/record/SingleKeyComparator.java
  java/core/src/main/java/sleeper/core/record/serialiser/Base64RecordListSerialiser.java
  java/core/src/main/java/sleeper/core/record/serialiser/JSONResultsBatchSerialiser.java
  java/core/src/main/java/sleeper/core/record/serialiser/RecordJSONSerDe.java
  java/core/src/main/java/sleeper/core/record/serialiser/RecordSerialiser.java
  java/core/src/main/java/sleeper/core/schema/Field.java
  java/core/src/main/java/sleeper/core/schema/SchemaSerDe.java
  java/core/src/main/java/sleeper/core/schema/type/ListType.java
  java/core/src/main/java/sleeper/core/schema/type/PrimitiveType.java
  java/core/src/main/java/sleeper/core/schema/type/Type.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/PartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/SplitFileReferenceRequest.java
  java/core/src/main/java/sleeper/core/statestore/StateStore.java
  java/core/src/main/java/sleeper/core/statestore/StateStoreException.java
  java/core/src/main/java/sleeper/core/table/InvokeForTableRequest.java
  java/core/src/main/java/sleeper/core/table/InvokeForTableRequestSerDe.java
  java/core/src/test/java/sleeper/core/partition/PartitionFactory.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
  java/parquet/src/main/java/sleeper/io/parquet/record/ParquetReaderIterator.java
  java/parquet/src/main/java/sleeper/io/parquet/record/ParquetRecordReader.java
  java/parquet/src/main/java/sleeper/io/parquet/record/RecordConverter.java
  java/parquet/src/main/java/sleeper/io/parquet/record/RecordWriteSupport.java
  java/parquet/src/main/java/sleeper/io/parquet/record/RecordWriter.java
  java/parquet/src/main/java/sleeper/io/parquet/record/SchemaConverter.java
Labels: one-review-required

#2078 Issue 2070 - Ingest Javadoc summary fragments
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-suppressions.xml
  java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambda.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/task/IngestTask.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestRecords.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestRecordsFromIterator.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngestCoordinator.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngesterIntoPartitions.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/ParquetConfiguration.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/RecordIteratorWithSleeperIteratorApplied.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriter.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/DirectPartitionFileWriter.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriter.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriterUtils.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arraylist/ArrayListRecordBatch.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowIngestSupport.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordBatch.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordWriterAcceptingRecords.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowToRecordConversionUtils.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/RecordIteratorOrderedFromVectorSchemaRoot.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java
Labels: one-review-required

#2080 Issue 2072 - Trino Javadoc summary fragments
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-suppressions.xml
  java/trino/src/main/java/sleeper/trino/SleeperConfig.java
  java/trino/src/main/java/sleeper/trino/SleeperConnector.java
  java/trino/src/main/java/sleeper/trino/SleeperConnectorFactory.java
  java/trino/src/main/java/sleeper/trino/SleeperMetadata.java
  java/trino/src/main/java/sleeper/trino/SleeperNodePartitioningProvider.java
  java/trino/src/main/java/sleeper/trino/SleeperPageSink.java
  java/trino/src/main/java/sleeper/trino/SleeperPageSinkProvider.java
  java/trino/src/main/java/sleeper/trino/SleeperRecordCursor.java
  java/trino/src/main/java/sleeper/trino/SleeperRecordSet.java
  java/trino/src/main/java/sleeper/trino/SleeperRecordSetProvider.java
  java/trino/src/main/java/sleeper/trino/SleeperSplitManager.java
  java/trino/src/main/java/sleeper/trino/SleeperSplitSource.java
  java/trino/src/main/java/sleeper/trino/handle/SleeperColumnHandle.java
  java/trino/src/main/java/sleeper/trino/handle/SleeperPartitionHandle.java
  java/trino/src/main/java/sleeper/trino/handle/SleeperSplit.java
  java/trino/src/main/java/sleeper/trino/handle/SleeperTableHandle.java
  java/trino/src/main/java/sleeper/trino/ingest/ArrowRecordWriterAcceptingPages.java
  java/trino/src/main/java/sleeper/trino/package-info.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/HadoopConfigurationProviderForDeployedS3Instance.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/SleeperConnectionAsTrino.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/SleeperKeyRange.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/SleeperRawAwsConnection.java
  java/trino/src/main/java/sleeper/trino/utils/SleeperPageBlockUtils.java
  java/trino/src/main/java/sleeper/trino/utils/SleeperTypeConversionUtils.java
  java/trino/src/test/java/sleeper/trino/TpchSchemaPartitionedInsertPartitioningDisabledIT.java
  java/trino/src/test/java/sleeper/trino/TpchSchemaPartitionedInsertPartitioningEnabledIT.java
Labels: one-review-required

#2073 Issue 2065 - Athena Javadoc summary fragments
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-suppressions.xml
  java/athena/src/main/java/sleeper/athena/metadata/IteratorApplyingMetadataHandler.java
  java/athena/src/main/java/sleeper/athena/metadata/SimpleMetadataHandler.java
  java/athena/src/main/java/sleeper/athena/metadata/SleeperMetadataHandler.java
  java/athena/src/main/java/sleeper/athena/record/IteratorApplyingRecordHandler.java
  java/athena/src/main/java/sleeper/athena/record/SimpleRecordHandler.java
  java/athena/src/main/java/sleeper/athena/record/SleeperRecordHandler.java
  java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/QueryExecutor.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/SleeperConnectionAsTrino.java
Labels: one-review-required

#2075 Issue 2067 - CDK chunk Javadoc summary fragments
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-suppressions.xml
  java/cdk-environment/src/main/java/sleeper/environment/cdk/SleeperEnvironmentCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/Utils.java
  java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/QueryQueueStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TopicStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrStudioStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestApp.java
  java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperties.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SleeperSystemTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SystemTestContext.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SystemTestDrivers.java
Labels: one-review-required

#2077 Issue 2069 - Data & state store chunk Javadoc summary fragments
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-suppressions.xml
  java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobSerDe.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/strategy/impl/BasicCompactionStrategy.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/strategy/impl/BasicLeafStrategy.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/strategy/impl/SizeRatioCompactionStrategy.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsLambda.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsTriggerLambda.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/FailedCreateCompactionJobsException.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/task/creation/RunCompactionTasksLambda.java
  java/compaction/compaction-task-creation/src/test/java/sleeper/compaction/task/creation/SafeTerminationTest.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/FailedGarbageCollectionException.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorTriggerLambda.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/TableFilesDeleted.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/SplitPartition.java
  java/splitter/splitter-core/src/main/java/sleeper/splitter/SplitPartitionJobDefinitionSerDe.java
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/FindPartitionsToSplitTriggerLambda.java
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/SplitPartitionLambda.java
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/SqsSplitPartitionJobSender.java
  java/statestore/src/main/java/sleeper/statestore/InitialiseStateStore.java
  java/statestore/src/main/java/sleeper/statestore/InitialiseStateStoreFromExportedPartitions.java
  java/statestore/src/main/java/sleeper/statestore/InitialiseStateStoreFromSplitPoints.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStoreCreator.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionIdStore.java
Labels: one-review-required

#2079 Issue 2071 - Query Javadoc summary fragments
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-suppressions.xml
  java/query/query-core/src/main/java/sleeper/query/model/Query.java
  java/query/query-core/src/main/java/sleeper/query/model/QuerySerDe.java
  java/query/query-runner/src/main/java/sleeper/query/runner/output/S3ResultsOutput.java
  java/query/query-runner/src/main/java/sleeper/query/runner/output/SQSResultsOutput.java
  java/query/query-runner/src/main/java/sleeper/query/runner/output/WebSocketResultsOutput.java
  java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/LeafPartitionQueryExecutor.java
  java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/LeafPartitionRecordRetriever.java
  java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/LeafPartitionRecordRetrieverImpl.java
  java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/RetrieveTask.java
  java/query/query-runner/src/main/java/sleeper/query/runner/tracker/DynamoDBQueryTrackerEntry.java
Labels: one-review-required

#2083 Issue 2082 - Add checks for missing Javadoc
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-idea/checkstyle.xml
  code-style/checkstyle-suppressions.xml
  code-style/checkstyle.xml
Labels: one-review-required

#2106 Issue 2105 - Update spotbugs plugin version in configuration module
  java/athena/src/main/java/sleeper/athena/record/IteratorApplyingRecordHandler.java
  java/clients/src/main/java/sleeper/clients/QueryClient.java
  java/clients/src/main/java/sleeper/clients/status/update/CreateCompactionJobsClient.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsLambda.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsIT.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/configuration/pom.xml
  java/configuration/src/main/java/sleeper/configuration/EstimateSplitPoints.java
  java/configuration/src/main/java/sleeper/configuration/jars/ObjectFactory.java
  java/configuration/src/test/java/sleeper/configuration/EstimateSplitPointsTest.java
  java/configuration/src/test/java/sleeper/configuration/jars/ObjectFactoryIT.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
  java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsLeafPartitionQueryProcessor.java
  java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
  java/query/query-runner/src/test/java/sleeper/query/runner/recordretrieval/QueryExecutorIT.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/SleeperRawAwsConnection.java
Labels: pr-base-for-stacking, one-review-required

#2104 Issue 2103 - Update spotbugs plugin version in parquet module
  java/athena/src/main/java/sleeper/athena/record/SimpleRecordHandler.java
  java/athena/src/test/java/sleeper/athena/FilterTranslatorIT.java
  java/athena/src/test/java/sleeper/athena/record/SimpleRecordHandlerIT.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFiles.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactSortedFilesTestData.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arraylist/ArrayListRecordBatch.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/ResultVerifier.java
  java/parquet/pom.xml
  java/parquet/src/main/java/sleeper/io/parquet/record/ParquetReaderIterator.java
  java/parquet/src/main/java/sleeper/io/parquet/record/RecordConverter.java
  java/parquet/src/main/java/sleeper/io/parquet/record/SleeperRecordMaterializer.java
  java/parquet/src/test/java/sleeper/io/parquet/record/ParquetReaderIteratorIT.java
  java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/RetrieveTask.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/ReadRecordsFromS3.java
Labels: one-review-required, pr-stacked-middle

#2108 Issue 2107 - Update spotbugs plugin version in statestore module
  java/statestore/pom.xml
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
Labels: one-review-required, pr-stacked-middle

#2189 Issue 2188 - Test clearing state stores
  java/clients/src/main/java/sleeper/clients/status/update/DeleteTable.java
  java/clients/src/test/java/sleeper/clients/status/update/DeleteTableIT.java
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/PartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/StateStore.java
  java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBPartitionStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/s3/S3PartitionStoreIT.java
Labels: pr-base-for-stacking, one-review-required

#2190 Issue 2187 - Shell for transaction log state store
  java/core/src/main/java/sleeper/core/statestore/transactionlog/StateStoreFiles.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/StateStorePartitions.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/StateStoreTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/AddFilesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/InitialisePartitionsTransaction.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStoreTest.java
Labels: pr-base-for-stacking

#2148 Issue 2120 - Transaction log state store operations
  java/core/src/main/java/sleeper/core/statestore/transactionlog/StateStoreFiles.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/AssignJobIdsTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ClearFilesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/DeleteFilesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ReplaceFileReferencesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/SplitFileReferencesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/SplitPartitionTransaction.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStoreTest.java
Labels: pr-stacked-middle

#2193 Issue 2192 - Serialise state store transactions
  java/core/src/main/java/sleeper/core/statestore/AllReferencesToAFileSerDe.java
  java/core/src/main/java/sleeper/core/statestore/AssignJobIdRequest.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceSerDe.java
  java/core/src/main/java/sleeper/core/statestore/SplitFileReferenceRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/AddFilesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/AssignJobIdsTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ClearFilesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/DeleteFilesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/InitialisePartitionsTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ReplaceFileReferencesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/SplitFileReferencesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/SplitPartitionTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDe.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/TransactionType.java
  java/core/src/main/java/sleeper/core/util/GsonConfig.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeAddFiles.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeAddSplitFile.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeAssignJobIds.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeClearFiles.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeDeleteFiles.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeInitialisePartitions.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeReplaceFileReferences.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeSplitFileReferences.approved.txt
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeSplitPartition.approved.txt
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/WaitForJobsStatus.java
Labels: pr-stacked-middle

#2191 Issue 2171 - State store transaction log DynamoDB implementation
  java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
  java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreFactory.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogStateStoreCreator.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogPartitionStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreMultipleTablesIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreOneTableTestBase.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreTestBase.java
Labels: pr-stacked-top
