Repository gchq/sleeper, pull requests merged in 2025-06, with the labels that each got.

#4979 Issue 4973 - Admin client should list tables when selecting a table
  java/clients/src/main/java/sleeper/clients/admin/AdminClient.java
  java/clients/src/main/java/sleeper/clients/admin/TableSelectHelper.java
  java/clients/src/main/java/sleeper/clients/admin/screen/CompactionStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/screen/FilesStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/screen/IngestStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/screen/InstanceConfigurationScreen.java
  java/clients/src/main/java/sleeper/clients/admin/screen/PartitionsStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/report/TableNamesReport.java
  java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
  java/clients/src/test/java/sleeper/clients/admin/FilesStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/PartitionsStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/TableNamesReportTest.java
  java/clients/src/test/java/sleeper/clients/admin/TableSelectHelperIT.java
  java/clients/src/test/java/sleeper/clients/admin/TableSelectHelperTest.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/ExpectedAdminConsoleValues.java
Labels: one-review-required

#5006 Issue 4997 - Upgrade compaction-rust to use sketchesv2
  .github/workflows/chunk-rust.yaml
  java/compaction/compaction-rust/pom.xml
  java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerIT.java
  java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerLocalStackIT.java
Labels: one-review-required

#5003 Issue 4854 - migrate system test data generation to aws sdk v2
  java/system-test/system-test-data-generation/pom.xml
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/ECSSystemTestTask.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateRandomDataFiles.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataViaBatcher.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataViaQueue.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/InstanceIngestSession.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/MultipleQueries.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/RandomRecordSupplier.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomData.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
  java/system-test/system-test-data-generation/src/test/java/sleeper/systemtest/datageneration/SystemTestTaskIT.java
Labels: one-review-required

#5015 Issue 5014 - Fix web socket client request signing
  java/clients/src/main/java/sleeper/clients/api/role/AssumeSleeperRoleV2.java
  java/clients/src/main/java/sleeper/clients/query/QueryWebSocketClient.java
  java/clients/src/main/java/sleeper/clients/query/QueryWebSocketCommandLineClient.java
  java/clients/src/test/java/sleeper/clients/query/FakeWebSocketClient.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/WebSocketQueryDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
Labels: one-review-required, needs-reviewer

#5012 Issue 4960: Remove AWS SDK v2 duplicates of ingest batcher modules
  .github/config/chunks.yaml
  .github/workflows/chunk-clients-cdk.yaml
  .github/workflows/chunk-ingest.yaml
  java/cdk/pom.xml
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
  java/clients/pom.xml
  java/clients/src/main/java/sleeper/clients/admin/AdminClientTrackerFactory.java
  java/clients/src/main/java/sleeper/clients/report/IngestBatcherReport.java
  java/ingest/ingest-batcher-job-creator/pom.xml
  java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambda.java
  java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaIT.java
  java/ingest/ingest-batcher-store/pom.xml
  java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStore.java
  java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreCreator.java
  java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestRequestFormat.java
  java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/IngestBatcherStoreFactory.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreCreatorIT.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreTestBase.java
  java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreWiremockIT.java
  java/ingest/ingest-batcher-storev2/pom.xml
  java/ingest/ingest-batcher-storev2/src/main/java/sleeper/ingest/batcher/storev2/DynamoDBIngestBatcherStore.java
  java/ingest/ingest-batcher-storev2/src/main/java/sleeper/ingest/batcher/storev2/DynamoDBIngestBatcherStoreCreator.java
  java/ingest/ingest-batcher-storev2/src/main/java/sleeper/ingest/batcher/storev2/DynamoDBIngestRequestFormat.java
  java/ingest/ingest-batcher-storev2/src/main/java/sleeper/ingest/batcher/storev2/IngestBatcherStoreFactory.java
  java/ingest/ingest-batcher-storev2/src/test/java/sleeper/ingest/batcher/storev2/DynamoDBIngestBatcherStoreCreatorIT.java
  java/ingest/ingest-batcher-storev2/src/test/java/sleeper/ingest/batcher/storev2/DynamoDBIngestBatcherStoreIT.java
  java/ingest/ingest-batcher-storev2/src/test/java/sleeper/ingest/batcher/storev2/DynamoDBIngestBatcherStoreTestBase.java
  java/ingest/ingest-batcher-storev2/src/test/java/sleeper/ingest/batcher/storev2/DynamoDBIngestBatcherStoreWiremockIT.java
  java/ingest/ingest-batcher-storev2/src/test/java/sleeper/ingest/batcher/storev2/IngestBatcherStoreFactoryTest.java
  java/ingest/ingest-batcher-submitter/pom.xml
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/FileNotFoundException.java
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitDeadLetterQueue.java
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitter.java
  java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambda.java
  java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaIT.java
  java/ingest/ingest-batcher-submitter/src/test/resources/log4j.properties
  java/ingest/ingest-batcher-submitterv2/pom.xml
  java/ingest/ingest-batcher-submitterv2/src/main/java/sleeper/ingest/batcher/submitterv2/IngestBatcherSubmitDeadLetterQueue.java
  java/ingest/ingest-batcher-submitterv2/src/main/java/sleeper/ingest/batcher/submitterv2/IngestBatcherSubmitter.java
  java/ingest/ingest-batcher-submitterv2/src/main/java/sleeper/ingest/batcher/submitterv2/IngestBatcherSubmitterLambda.java
  java/ingest/ingest-batcher-submitterv2/src/test/java/sleeper/ingest/batcher/submitterv2/IngestBatcherSubmitterLambdaIT.java
  java/ingest/pom.xml
  java/system-test/system-test-drivers/pom.xml
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestBatcherDriver.java
Labels: one-review-required

#5013 4818 Migrate bulk export to AWS SDK V2
  .github/workflows/chunk-compaction.yaml
  java/bulk-export/bulk-export-core/src/main/java/sleeper/bulkexport/core/model/BulkExportLeafPartitionQuery.java
  java/bulk-export/bulk-export-planner/pom.xml
  java/bulk-export/bulk-export-planner/src/main/java/sleeper/bulkexport/planner/SqsBulkExportProcessor.java
  java/bulk-export/bulk-export-planner/src/main/java/sleeper/bulkexport/planner/SqsBulkExportProcessorLambda.java
  java/bulk-export/bulk-export-planner/src/test/java/sleeper/bulkexport/planner/SqsBulkExportProcessorLambdaIT.java
  java/bulk-export/bulk-export-planner/src/test/java/sleeper/bulkexport/planner/SqsBulkExportProcessorLambdaTest.java
  java/bulk-export/bulk-export-task-creator/pom.xml
  java/bulk-export/bulk-export-task-creator/src/main/java/sleeper/bulkexport/taskcreator/RunLeafPartitionBulkExportTasks.java
  java/bulk-export/bulk-export-task-creator/src/main/java/sleeper/bulkexport/taskcreator/SqsTriggeredBulkExportTaskRunnerLambda.java
  java/bulk-export/bulk-export-task-execution/pom.xml
  java/bulk-export/bulk-export-task-execution/src/main/java/sleeper/bulkexport/taskexecution/ECSBulkExportTaskRunner.java
  java/bulk-export/bulk-export-task-execution/src/main/java/sleeper/bulkexport/taskexecution/SqsBulkExportQueueHandler.java
  java/bulk-export/bulk-export-task-execution/src/test/java/sleeper/bulkexport/taskexecution/ECSBulkExportTaskRunnerLocalStackIT.java
Labels: one-review-required

#5030 Issue 5029 - Ban duplicate dependencies in poms
  java/pom.xml
Labels: one-review-required

#5032 Issue 5031 - Fix ingest starter lambda
  java/athena/src/test/java/sleeper/athena/composite/AthenaHandlerTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaHandlerTest.java
  java/bulk-import/bulk-import-starterv2/src/test/java/sleeper/bulkimport/starterv2/BulkImportStarterLambdaHandlerTest.java
  java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/CdkCustomLambdaHandlerTest.java
  java/compaction/compaction-job-creation-lambda/src/test/java/sleeper/compaction/job/creation/lambda/CompactionJobCreationLambdaHandlerTest.java
  java/compaction/compaction-task-creation/src/test/java/sleeper/compaction/task/creation/CompactionTaskCreationLambdaHandlerTest.java
  java/core/src/main/java/sleeper/core/deploy/LambdaHandler.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorLambdaHandlerTest.java
  java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaHandlerTest.java
  java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaHandlerTest.java
  java/ingest/ingest-taskrunner/src/test/java/sleeper/ingest/taskrunner/RunIngestTasksLambdaHandlerTest.java
  java/metrics/src/test/java/sleeper/metrics/TableMetricsLambdaHandlerTest.java
  java/partitions/splitter-lambda/src/test/java/sleeper/splitter/lambda/PartitionSplitterLambdaHandlerTest.java
  java/query/query-lambda/src/test/java/sleeper/query/lambda/QueryLambdaHandlerTest.java
  java/query/query-lambdav2/src/test/java/sleeper/query/lambda/QueryLambdaHandlerTest.java
  java/statestore-lambda/src/test/java/sleeper/statestore/lambda/StateStoreLambdaHandlerTest.java
Labels: one-review-required, needs-reviewer

#5023 5002: Assert Sketches written in bulk import test
  java/bulk-import/bulk-import-runner/pom.xml
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverIT.java
Labels: one-review-required

#5022 Issue 3897 - Upgrade EMR & Hadoop
  NOTICES
  code-style/dependency-check-suppressions.xml
  docs/usage/properties/instance/user/bulk_import.md
  docs/usage/properties/table/bulk_import.md
  example/full/instance.properties
  example/full/table.properties
  java/bulk-import/bulk-import-eks/docker/eks/Dockerfile
  java/bulk-import/bulk-import-runner/docker/emr-serverless/Dockerfile
  java/bulk-import/bulk-import-runner/pom.xml
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/runner/BulkImportJobDriver.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrServerlessPlatformExecutor.java
  java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutor.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaHandlerTest.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrServerlessPlatformExecutorWiremockIT.java
  java/bulk-import/bulk-import-starter/src/test/resources/example/emr-serverless/jobrun-request.json
  java/bulk-import/bulk-import-starter/src/test/resources/example/emr/runjobflow-request.json
  java/bulk-import/bulk-import-starter/src/test/resources/example/step-functions/startexecution-input.json
  java/bulk-import/bulk-import-starterv2/src/main/java/sleeper/bulkimport/starterv2/executor/EmrServerlessPlatformExecutor.java
  java/bulk-import/bulk-import-starterv2/src/main/java/sleeper/bulkimport/starterv2/executor/StateMachinePlatformExecutor.java
  java/bulk-import/bulk-import-starterv2/src/test/java/sleeper/bulkimport/starterv2/BulkImportStarterLambdaHandlerTest.java
  java/bulk-import/bulk-import-starterv2/src/test/java/sleeper/bulkimport/starterv2/executor/EmrServerlessPlatformExecutorWiremockIT.java
  java/bulk-import/bulk-import-starterv2/src/test/resources/example/emr-serverless/jobrun-request.json
  java/bulk-import/bulk-import-starterv2/src/test/resources/example/emr/runjobflow-request.json
  java/bulk-import/bulk-import-starterv2/src/test/resources/example/step-functions/startexecution-input.json
  java/cdk-environment/pom.xml
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
  java/core/src/main/java/sleeper/core/deploy/DockerDeployment.java
  java/core/src/main/java/sleeper/core/deploy/LambdaHandler.java
  java/core/src/main/java/sleeper/core/deploy/LambdaJar.java
  java/core/src/main/java/sleeper/core/properties/instance/NonPersistentEMRProperty.java
  java/distribution/pom.xml
  java/distribution/src/main/assembly/zip.xml
  java/parquet/pom.xml
  java/parquet/src/main/java/sleeper/parquet/utils/HadoopConfigurationProvider.java
  java/pom.xml
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/HadoopConfigurationProviderForDeployedS3Instance.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#5060 Issue 5059 - Use statestorev2 in statestore-committer-core tests
  .github/workflows/chunk-clients-cdk.yaml
  java/statestore-committer-core/pom.xml
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterThroughputIT.java
Labels: one-review-required, pr-stacked-middle, needs-reviewer

#5069 Issue 5067 - Stop query lambda failing when loading jar twice
  java/configuration/src/main/java/sleeper/configuration/jars/S3UserJarsLoader.java
  java/configuration/src/test/java/sleeper/configuration/jars/S3UserJarsLoaderIT.java
  java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
  java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsQueryProcessorLambda.java
Labels: one-review-required, needs-reviewer

#5070 Issue 5068 - Set timeout for QueryWebSocketClient
  java/clients/src/main/java/sleeper/clients/query/QueryWebSocketClient.java
  java/clients/src/main/java/sleeper/clients/query/QueryWebSocketCommandLineClient.java
  java/clients/src/test/java/sleeper/clients/query/FakeWebSocketClient.java
  java/clients/src/test/java/sleeper/clients/query/QueryWebSocketClientTest.java
  java/clients/src/test/java/sleeper/clients/query/QueryWebSocketCommandLineClientTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
Labels: one-review-required, needs-reviewer

#5066 Issue: 4806: Test unexpected network failure looking for files to submit to ingest batcher
  java/ingest/ingest-batcher-submitter/pom.xml
  java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaWireMockIT.java
Labels: one-review-required

#5081 Issue 5080 - Fix web socket query results
  java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/query/query-runner/src/main/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestination.java
  java/query/query-runner/src/test/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestinationIT.java
Labels: one-review-required, needs-reviewer

#5104 Issue 5101 - Python testing setup
  .github/workflows/python-tests.yaml
  python/pyproject.toml
  python/setup.py
  python/src/sleeper/properties/__init__.py
  python/src/sleeper/properties/bucket_property.py
  python/src/sleeper/properties/cdk_defined_properties.py
  python/src/sleeper/properties/dynamo_table_property.py
  python/src/sleeper/properties/instance_properties.py
  python/src/sleeper/properties/queue_property.py
  python/src/sleeper/sleeper.py
  python/tests/__init__.py
  python/tests/sleeper/__init__.py
  python/tests/sleeper/localstack.py
  python/tests/sleeper/properties/__init__.py
  python/tests/sleeper/properties/test_instance_properties.py
  python/tests/sleeper/properties/test_instance_properties_localstack.py
Labels: pr-base-for-stacking, one-review-required

#4959 Issue 4333 - Update permissions for Bulk Export Stack
  java/cdk/src/main/java/sleeper/cdk/stack/bulkexport/BulkExportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkexport/BulkExportTaskResources.java
Labels: one-review-required

#5096 Issue 5094 - Fix table metrics
  NOTICES
  java/core/src/test/java/sleeper/core/statestore/testutils/StateStoreUpdatesWrapper.java
  java/metrics/pom.xml
  java/metrics/src/main/java/sleeper/metrics/TableMetricsLambda.java
  java/metrics/src/test/java/sleeper/metrics/MetricsTestUtils.java
  java/metrics/src/test/java/sleeper/metrics/TableMetricsLambdaTest.java
  java/metrics/src/test/resources/example/one-file.json
  java/pom.xml
Labels: one-review-required

#5132 Issue 5131 - Fix Python build configuration
  python/setup.py
Labels: one-review-required

#5135 Issue 5134 - Fix ingest via Python
  docs/usage/python-api.md
  python/src/sleeper/client.py
  python/src/sleeper/ingest.py
  python/src/sleeper/properties/cdk_defined_properties.py
  python/tests/sleeper/localstack.py
  python/tests/sleeper/properties/instance_properties_helper.py
  python/tests/sleeper/test_bulk_export.py
  python/tests/sleeper/test_ingest.py
Labels: pr-base-for-stacking, one-review-required

#5147 Issue 5144 -Integration test for DataFusion aggregation
  java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerIT.java
Labels: one-review-required

#5165 Issue 5163 - Add Checkstyle checks
  .vscode/settings.json
  code-style/checkstyle-idea/checkstyle.xml
  code-style/checkstyle.xml
  java/athena/src/main/java/sleeper/athena/record/SleeperRecordHandler.java
  java/build/src/main/java/sleeper/build/maven/DependencyReference.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/QueryQueueStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/QueryStack.java
  java/clients/src/main/java/sleeper/clients/api/aws/SleeperClientHadoopProvider.java
  java/clients/src/main/java/sleeper/clients/query/QueryCommandLineClient.java
  java/clients/src/main/java/sleeper/clients/query/QueryLambdaClient.java
  java/clients/src/main/java/sleeper/clients/query/QueryWebSocketClient.java
  java/clients/src/main/java/sleeper/clients/query/exception/QueryWebSocketClientException.java
  java/clients/src/main/java/sleeper/clients/report/ingest/batcher/query/BatcherQueryPrompt.java
  java/clients/src/main/java/sleeper/clients/report/job/query/JobQueryPrompt.java
  java/clients/src/main/java/sleeper/clients/report/query/TrackerQueryPrompt.java
  java/clients/src/main/java/sleeper/clients/table/DeleteTable.java
  java/clients/src/main/java/sleeper/clients/table/ReinitialiseTable.java
  java/clients/src/main/java/sleeper/clients/table/partition/ReinitialiseTableFromExportedPartitions.java
  java/clients/src/main/java/sleeper/clients/table/partition/ReinitialiseTableFromSplitPoints.java
  java/common/common-task/src/main/java/sleeper/common/task/CompactionTaskHostScaler.java
  java/common/common-task/src/main/java/sleeper/common/task/EC2Scaler.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/creation/CreateCompactionJobs.java
  java/compaction/compaction-rust/src/main/java/sleeper/compaction/rust/RustBridge.java
  java/compaction/compaction-rust/src/main/java/sleeper/compaction/rust/RustCompactionRunner.java
  java/core/src/main/java/sleeper/core/deploy/PopulateInstanceProperties.java
  java/core/src/main/java/sleeper/core/properties/SleeperProperties.java
  java/core/src/main/java/sleeper/core/properties/SleeperPropertyValues.java
  java/core/src/main/java/sleeper/core/properties/local/LoadLocalProperties.java
  java/core/src/main/java/sleeper/core/properties/model/SleeperPropertyValueUtils.java
  java/core/src/main/java/sleeper/core/schema/SchemaSerDe.java
  java/core/src/main/java/sleeper/core/statestore/commit/StateStoreCommitRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/log/TransactionBodyStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/log/TransactionLogEntry.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/snapshot/TransactionLogSnapshotCreator.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/state/StateListenerBeforeApply.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/AddFilesTransaction.java
  java/core/src/main/java/sleeper/core/util/PollWithRetries.java
  java/core/src/main/java/sleeper/core/util/StaticRateLimit.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilderSplitsFirst.java
  java/core/src/test/java/sleeper/core/range/RegionTest.java
  java/core/src/test/java/sleeper/core/statestore/FilesReportTestHelper.java
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogs.java
  java/core/src/test/java/sleeper/core/statestore/testutils/OnDiskTransactionLogStore.java
  java/core/src/test/java/sleeper/core/tracker/ingest/job/IngestJobEventTestData.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/core/job/IngestJobMessageHandler.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/core/job/IngestJobStatusFromJobTestData.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/IngestFactory.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/IngestCoordinator.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/partitionfilewriter/AsyncS3PartitionFileWriter.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/partitionfilewriter/DirectPartitionFileWriter.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/recordbatch/arraylist/ArrayListRecordBatch.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/recordbatch/arrow/ArrowRecordBatch.java
  java/statestore/src/main/java/sleeper/statestore/ArrowFormatUtils.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreFilesArrowFormat.java
  java/statestore/src/main/java/sleeper/statestore/StateStorePartitionsArrowFormat.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotCreator.java
  java/trino/src/main/java/sleeper/trino/handle/SleeperSplit.java
Labels: one-review-required

#5176 Issue 5175 - Use jproperties in Python API
  NOTICES
  python/setup.py
  python/src/sleeper/properties/instance_properties.py
  python/tests/sleeper/properties/test_instance_properties.py
Labels: one-review-required

#5179 Issue 5178 - Use test names starting with "should" in Python
  python/pyproject.toml
  python/tests/sleeper/properties/test_config_bucket_localstack.py
  python/tests/sleeper/properties/test_instance_properties.py
  python/tests/sleeper/test_bulk_export.py
  python/tests/sleeper/test_ingest.py
  python/tests/sleeper/test_ingest_batcher.py
Labels: one-review-required

#5187 Issue 5186 - Add extra sort stage to workaround DF breaking sort order
  rust/compaction/src/datafusion.rs
  rust/compaction/src/datafusion/sketch_udf.rs
Labels: rust, priority:high
