Repository gchq/sleeper, pull requests merged in 2025-03, with the labels that each got.

#4373 Issue 4372 - Improve compaction creation throughput system test
  java/common/localstack-test/src/main/java/sleeper/localstack/test/LocalStackTestBase.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsResetInstanceOnFirstConnect.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsDrainSqsQueue.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriverDrainCompactionsIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/compaction/CompactionFakeCommitIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsResetInstanceOnFirstConnectIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSystemTestDrivers.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/util/AwsDrainSqsQueueIT.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionCreationThroughputST.java
Labels: one-review-required

#4380 Issue 4379 - Use offline tables for tests adding fake data
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriverDrainCompactionsIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/compaction/CompactionFakeCommitIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/SetupInstanceLocalIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriverIT.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SleeperSystemTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionFakeCommitTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CreateManyCompactionsTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/ParallelCompactionsTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcherTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SetupInstanceTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SleeperInstanceTablesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/metrics/TableMetricsDslTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/partitioning/PartitionSplittingTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/reporting/SystemTestReportingTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/sourcedata/SystemTestSourceFilesTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommitsTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommitsThroughputTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EksBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrServerlessBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/OptionalFeaturesDisabledST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonBulkImportST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonIngestST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonQueryST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/QueryST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/RedeployOptionalStacksST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
Labels: one-review-required

#4378 Issue 4331 - Improve maven start up message
  scripts/build/build.sh
Labels: one-review-required

#4420 Issue 4419 - Change from GCC to Clang for C/C++ code
  rust/Cross.sccache.toml
  rust/Cross.toml
Labels: bug, build-pipeline, one-review-required, rust

#4397 Issue 3832 - Stop building unused fat jars
  java/compaction/compaction-job-creation/pom.xml
  java/query/query-runner/pom.xml
  java/statestore-committer-core/pom.xml
Labels: one-review-required

#4441 Issue 4440 - Set missing compaction property flags to trigger CDK deployment
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
Labels: one-review-required

#4443 Issue 4442 - Garbage collector unit tests
  java/common/localstack-test/src/main/java/sleeper/localstack/test/LocalStackTestBase.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorTest.java
Labels: one-review-required

#4436 Issue 4418 Table writer markdown table output format
  java/clients/src/main/java/sleeper/clients/util/table/TableStructure.java
  java/clients/src/test/java/sleeper/clients/util/table/TableWriterTest.java
  java/clients/src/test/resources/reports/table/markdown.txt
  java/clients/src/test/resources/reports/table/structure.txt
Labels: one-review-required

#4438 Issue 4325 - Upgrade Kubernetes to v1.32
  NOTICES
  java/cdk/pom.xml
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/pom.xml
Labels: one-review-required

#4455 Issue 4317 - Clear snapshot metadata on Sleeper table deletion
  java/clients/src/main/java/sleeper/clients/status/update/DeleteTable.java
  java/clients/src/test/java/sleeper/clients/status/update/DeleteTableIT.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStore.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStoreIT.java
Labels: one-review-required

#4439 4437 CDK Bulk Export ECS Cluster
  .github/config/chunks.yaml
  .github/workflows/chunk-compaction.yaml
  example/full/instance.properties
  java/bulk-export/bulk-export-planner/pom.xml
  java/bulk-export/bulk-export-planner/src/main/java/sleeper/bulkexport/planner/SqsBulkExportProcessor.java
  java/bulk-export/bulk-export-planner/src/main/java/sleeper/bulkexport/planner/SqsBulkExportProcessorLambda.java
  java/bulk-export/bulk-export-runner/src/main/java/sleeper/bulkexport/runner/BulkExportJobRunner.java
  java/bulk-export/bulk-export-task-creator/pom.xml
  java/bulk-export/bulk-export-task-creator/src/main/java/sleeper/bulkexport/taskcreator/RunLeafPartitionBulkExportTasks.java
  java/bulk-export/bulk-export-task-creator/src/main/java/sleeper/bulkexport/taskcreator/SqsTriggeredBulkExportTaskRunnerLambda.java
  java/bulk-export/pom.xml
  java/cdk/src/main/java/sleeper/cdk/stack/bulkexport/BulkExportOnFargateResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkexport/BulkExportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkexport/BulkExportTaskResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/LoggingStack.java
  java/clients/src/main/java/sleeper/clients/teardown/RemoveECRRepositories.java
  java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
  java/clients/src/test/java/sleeper/clients/deploy/PopulateInstancePropertiesAwsIT.java
  java/configuration/src/main/java/sleeper/configuration/BulkExportTaskRequirements.java
  java/core/src/main/java/sleeper/core/ContainerConstants.java
  java/core/src/main/java/sleeper/core/deploy/GeneratePropertiesTemplates.java
  java/core/src/main/java/sleeper/core/deploy/LambdaHandler.java
  java/core/src/main/java/sleeper/core/deploy/LambdaJar.java
  java/core/src/main/java/sleeper/core/deploy/PopulateInstanceProperties.java
  java/core/src/main/java/sleeper/core/deploy/SleeperScheduleRule.java
  java/core/src/main/java/sleeper/core/properties/instance/BulkExportProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/CdkDefinedInstanceProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/UserDefinedInstanceProperty.java
  java/core/src/test/java/sleeper/core/deploy/PopulateInstancePropertiesTest.java
  java/distribution/src/main/assembly/zip.xml
  scripts/templates/instanceproperties.template
Labels: bulk-export-module

#4482 Issue 4466 - Grant sending batches straight to DLQ from compaction dispatcher
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
Labels: one-review-required

#4517 Issue 4492 - Raise batch size in BucketUtils.deleteObjectsInBucketWithPrefix
  java/clients/src/main/java/sleeper/clients/util/BucketUtils.java
Labels: one-review-required

#4530 Issue 4518: Change query processor cache timeout property
  example/full/instance.properties
  example/full/table.properties
  java/bulk-export/bulk-export-core/src/main/java/sleeper/bulkexport/core/recordretrieval/BulkExportQuerySplitter.java
  java/bulk-export/bulk-export-core/src/test/java/sleeper/bulkexport/core/recordretrieval/BulkExportQuerySplitterTest.java
  java/core/src/main/java/sleeper/core/properties/instance/QueryProperty.java
  java/core/src/main/java/sleeper/core/properties/table/TableProperty.java
  java/query/query-core/src/main/java/sleeper/query/core/recordretrieval/QueryExecutor.java
  java/query/query-core/src/test/java/sleeper/query/core/recordretrieval/QueryExecutorTest.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#4529 Issue 4528 - Link roadmap to new epic
  docs/development/roadmap.md
Labels: one-review-required

#4521 Issue 3856 - Compaction in LocalStack
  docs/usage/deploy-to-localstack.md
  java/clients/src/main/java/sleeper/clients/docker/DeployDockerInstance.java
  java/clients/src/main/java/sleeper/clients/docker/stack/CompactionDockerStack.java
  java/clients/src/main/java/sleeper/clients/docker/stack/TableDockerStack.java
  java/clients/src/main/java/sleeper/clients/status/update/DispatchCompactionJobsClient.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
  java/common/localstack-test/src/main/java/sleeper/localstack/test/SleeperLocalStackContainer.java
  java/compaction/compaction-job-creation-lambda/pom.xml
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambda.java
  java/compaction/compaction-job-creation/pom.xml
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/AwsCompactionJobDispatcher.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/AwsCompactionJobDispatcherIT.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateRandomDataFiles.java
  scripts/deploy/localstack/.gitignore
  scripts/deploy/localstack/createCompactionJobs.sh
  scripts/deploy/localstack/docker-compose.yml
  scripts/deploy/localstack/generateRandomData.sh
  scripts/deploy/localstack/ingestFiles.sh
  scripts/deploy/localstack/runCompactionTask.sh
Labels: one-review-required

#4541 Issue 4538 - Raise timeout waiting for commits in CompactionCommitThroughputST
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionCommitThroughputST.java
Labels: one-review-required

#4540 Issue 4539 - Align WireMock bulk import executor tests
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutorWiremockIT.java
  java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/PersistentEmrPlatformExecutorWiremockIT.java
  java/bulk-import/bulk-import-starter/src/test/resources/example/emr/runjobflow-request.json
Labels: one-review-required
