Repository gchq/sleeper, pull requests merged in 2025-08, with the labels that each got.

#5395 Issue 5394 - Make compaction method property more general
  docs/usage/properties/instance/user/compaction.md
  docs/usage/properties/instance/user/table_property_defaults.md
  docs/usage/properties/table/compaction.md
  docs/usage/properties/table/data_definition.md
  example/full/instance.properties
  example/full/table.properties
  java/compaction/compaction-datafusion/src/main/java/sleeper/compaction/datafusion/DataFusionCompactionRunner.java
  java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerIT.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/DefaultCompactionRunnerFactory.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestBase.java
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/TableDefaultProperty.java
  java/core/src/main/java/sleeper/core/properties/model/DataEngine.java
  java/core/src/main/java/sleeper/core/properties/table/TableProperty.java
  java/core/src/main/java/sleeper/core/util/IteratorFactory.java
  java/core/src/test/java/sleeper/core/util/IteratorFactoryTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionDataFusionPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionST.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#5398 Issue 5396 - Create query data engine selector
  java/clients/src/main/java/sleeper/clients/api/aws/SleeperClientHadoopQueryProvider.java
  java/clients/src/main/java/sleeper/clients/query/QueryClient.java
  java/clients/src/test/java/sleeper/clients/deploy/localstack/DockerInstanceTestBase.java
  java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsLeafPartitionQueryProcessor.java
  java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
  java/query/query-runner/src/main/java/sleeper/query/runner/rowretrieval/LeafPartitionRowRetrieverImpl.java
  java/query/query-runner/src/main/java/sleeper/query/runner/rowretrieval/QueryEngineSelector.java
  java/query/query-runner/src/test/java/sleeper/query/runner/rowretrieval/QueryExecutorIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/DirectQueryDriver.java
  java/trino/src/main/java/sleeper/trino/remotesleeperconnection/SleeperRawAwsConnection.java
Labels: pr-stacked-top

#5419 5393: Ensure files have parquet extension on ingest
  java/configuration/src/main/java/sleeper/configuration/utils/S3ExpandDirectories.java
  java/configuration/src/test/java/sleeper/configuration/utils/S3ExpandDirectoriesIT.java
  java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/task/IngestJobRunnerIT.java
Labels: one-review-required

#5439 Issue 5435: ParquetReader.useColumnIndexFilter setting is not applied consistently
  java/athena/src/test/java/sleeper/athena/record/SimpleRecordHandlerIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/dataframe/FileWritingIteratorIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/dataframe/WriteParquetFilesIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/rdd/SingleFileWritingIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestData.java
  java/parquet/src/main/java/sleeper/parquet/row/ParquetRowReaderFactory.java
  java/query/query-runner/src/test/java/sleeper/query/runner/output/S3ResultsOutputIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/python/PythonQueryDriver.java
Labels: one-review-required

#5445 5436: Update properties read by SleeperCDKApp to redeploy CDK when ch…
  docs/usage/properties/instance/user/common.md
  docs/usage/properties/instance/user/garbage_collector.md
  docs/usage/properties/instance/user/metrics.md
  docs/usage/properties/instance/user/partition_splitting.md
  docs/usage/properties/instance/user/table_state.md
  java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
  java/clients/src/test/java/sleeper/clients/admin/properties/AdminClientPropertiesStoreIT.java
  java/core/src/main/java/sleeper/core/properties/instance/CommonProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/GarbageCollectionProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/MetricsProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/PartitionSplittingProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/TableStateProperty.java
Labels: one-review-required

#5461 5229 stop passing full partition to compaction runner
  java/bulk-export/bulk-export-task-execution/src/main/java/sleeper/bulkexport/taskexecution/ECSBulkExportTaskRunner.java
  java/bulk-export/bulk-export-task-execution/src/test/java/sleeper/bulkexport/taskexecution/ECSBulkExportTaskRunnerLocalStackIT.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionRunner.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
  java/compaction/compaction-datafusion/src/main/java/sleeper/compaction/datafusion/DataFusionCompactionRunner.java
  java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerIT.java
  java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/JavaCompactionRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestBase.java
  java/parquet/src/main/java/sleeper/parquet/utils/RangeQueryUtils.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/InvestigateCompactionChangingNumberOfRows.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/InvestigateDataFusionCompactionOOM.java
Labels: one-review-required

#5490 Issue 5489 - Add package target to Cargo command
  rust/build-in-docker.sh
Labels: rust

#5492 Issue 5491 Tidy PartitionTreeNearestCommonAncestorTest
  java/core/src/test/java/sleeper/core/partition/PartitionTreeNearestCommonAncestorTest.java
Labels: needs-reviewer

#5495 Issue 5494 - Extract EnvironmentUtils
  java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkexport/BulkExportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkexport/BulkExportTaskResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
  java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionOnEc2Resources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/PropertiesStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/StateStoreCommitterStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogSnapshotStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogTransactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/KeepLambdaWarmStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/QueryStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/WebSocketQueryStack.java
  java/cdk/src/main/java/sleeper/cdk/util/AutoDeleteS3Objects.java
  java/cdk/src/main/java/sleeper/cdk/util/Utils.java
  java/core/src/main/java/sleeper/core/util/EnvironmentUtils.java
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java
Labels: pr-base-for-stacking, needs-reviewer

#5524 Issue 5522: DefaultCompactionRunnerFactory doesn't allow java compactions with aggregators specified
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/DefaultCompactionRunnerFactory.java
Labels: one-review-required, needs-reviewer

#5550 Issue 5546 - Refactor compaction runner tests
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestHelper.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/FakeMessageHandle.java
  java/compaction/compaction-datafusion/pom.xml
  java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerIT.java
  java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/pom.xml
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerEmptyOutputIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerIteratorIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestBase.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/main/java/sleeper/core/tracker/compaction/job/query/CompactionJobRun.java
  java/core/src/main/java/sleeper/core/util/ThreadSleep.java
  java/core/src/test/java/sleeper/core/tracker/compaction/job/CompactionJobTrackerTestHelper.java
Labels: pr-stacked-top
