Repository gchq/sleeper, pull requests merged in 2025-07, with the labels that each got.

#5233 Issue 5217 - Check if a file is sorted in a system test
  java/core/src/main/java/sleeper/core/record/KeyComparator.java
  java/core/src/main/java/sleeper/core/record/RecordComparator.java
  java/core/src/main/java/sleeper/core/schema/type/PrimitiveType.java
  java/core/src/test/java/sleeper/core/record/testutils/InMemoryRecordStore.java
  java/core/src/test/java/sleeper/core/record/testutils/SortedRecordsCheck.java
  java/core/src/test/java/sleeper/core/record/testutils/SortedRecordsCheckTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsDataFilesDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsDataFilesDriverIT.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SleeperSystemTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SystemTestDrivers.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DataFilesDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SystemTestTableFilesSortedCheckTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/trino/src/test/java/sleeper/trino/utils/SleeperPageBlockUtilsTest.java
Labels: pr-base-for-stacking

#5184 Issue 5183 - Java compactions and queries should use aggregating iterator
  java/athena/src/main/java/sleeper/athena/record/IteratorApplyingRecordHandler.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/JavaCompactionRunner.java
  java/core/src/main/java/sleeper/core/util/IteratorFactory.java
  java/core/src/test/java/sleeper/core/util/IteratorFactoryTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/RecordIteratorWithSleeperIteratorApplied.java
  java/query/query-core/src/main/java/sleeper/query/core/recordretrieval/LeafPartitionQueryExecutor.java
Labels: one-review-required

#5194 4731: Add code to write docker images to upload to a file
  .github/workflows/java-status.yaml
  docs/deployment-guide.md
  docs/deployment/images-to-upload.md
  docs/developer-guide.md
  java/clients/src/main/java/sleeper/clients/deploy/documentation/GenerateDockerImageDocumentation.java
  java/clients/src/main/java/sleeper/clients/deploy/documentation/GeneratePropertiesDocumentation.java
  java/clients/src/main/java/sleeper/clients/deploy/documentation/GeneratePropertiesTemplates.java
  java/clients/src/test/java/sleeper/clients/documentation/GeneratePropertiesTemplatesTest.java
  java/core/src/main/java/sleeper/core/deploy/LambdaJar.java
  scripts/dev/generateDocumentation.sh
Labels: one-review-required

#5235 Issue 5189 - Assert compaction output is sorted in system tests
  java/core/src/main/java/sleeper/core/metrics/TableMetrics.java
  java/core/src/main/java/sleeper/core/statestore/AllReferencesToAllFiles.java
  java/core/src/test/java/sleeper/core/statestore/AllReferencesToAFileTestHelper.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsDataFilesDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CompactionTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/compaction/CreateManyCompactionsTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/gc/GarbageCollectionTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommitsTest.java
  java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionDataFusionPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionST.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/OptionalFeaturesDisabledST.java
Labels: pr-base-for-stacking

#5241 Issue 5246 - Investigate DataFusion out of memory failure
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJob.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/TransactionType.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/AssignJobIdsTransaction.java
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogs.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/CheckTransactionLogs.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/CheckTransactionLogsTest.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/InvestigateCompactionChangingNumberOfRecords.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/InvestigateDataFusionCompactionOOM.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/TransactionLogEntryHandle.java
Labels: one-review-required

#5239 Issue 372 - Prebuild and publish docker images
  docs/usage/properties/instance/user/common.md
  example/full/instance.properties
  java/clients/src/main/java/sleeper/clients/deploy/container/DockerImageConfiguration.java
  java/clients/src/main/java/sleeper/clients/deploy/container/UploadDockerImagesToRepository.java
  java/clients/src/test/java/sleeper/clients/deploy/container/DockerImagesTestBase.java
  java/clients/src/test/java/sleeper/clients/deploy/container/UploadDockerImagesTest.java
  java/clients/src/test/java/sleeper/clients/deploy/container/UploadDockerImagesTestBase.java
  java/clients/src/test/java/sleeper/clients/deploy/container/UploadDockerImagesToRepositoryTest.java
  java/core/src/main/java/sleeper/core/properties/instance/CommonProperty.java
  scripts/deploy/deployToDockerRepository.sh
  scripts/templates/instanceproperties.template
Labels: needs-reviewer

#5273 Issue 5272 - Resolve dependency check failures
  NOTICES
  code-style/dependency-check-suppressions.xml
  java/core/pom.xml
  java/core/src/test/java/sleeper/core/statestore/transactionlog/transaction/TransactionSerDeTest.java
  java/pom.xml
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/GenerateNumberedValue.java
Labels: one-review-required

#5264 Issue 5262 - Refactor UploadDockerImages
  java/clients/src/main/java/sleeper/clients/admin/AdminClient.java
  java/clients/src/main/java/sleeper/clients/admin/properties/AdminClientPropertiesStore.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployExistingInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
  java/clients/src/main/java/sleeper/clients/deploy/container/UploadDockerImages.java
  java/clients/src/main/java/sleeper/clients/deploy/container/UploadDockerImagesCallbacks.java
  java/clients/src/main/java/sleeper/clients/deploy/container/UploadDockerImagesToEcr.java
  java/clients/src/main/java/sleeper/clients/deploy/container/UploadDockerImagesToEcrCallbacks.java
  java/clients/src/main/java/sleeper/clients/deploy/container/UploadDockerImagesToEcrRequest.java
  java/clients/src/main/java/sleeper/clients/deploy/container/UploadDockerImagesToRepository.java
  java/clients/src/test/java/sleeper/clients/admin/properties/AdminClientPropertiesStoreIT.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
  java/clients/src/test/java/sleeper/clients/deploy/container/DockerImagesTestBase.java
  java/clients/src/test/java/sleeper/clients/deploy/container/UploadDockerImagesToEcrFileIT.java
  java/clients/src/test/java/sleeper/clients/deploy/container/UploadDockerImagesToEcrTest.java
  java/clients/src/test/java/sleeper/clients/deploy/container/UploadDockerImagesToEcrTestBase.java
  java/clients/src/test/java/sleeper/clients/deploy/container/UploadDockerImagesToRepositoryTest.java
  java/clients/src/test/java/sleeper/clients/testutil/RunCommandTestHelper.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSystemTestDeploymentDriver.java
Labels: pr-base-for-stacking, needs-reviewer

#5291 Issue 5286 - Query web socket message serialisation
  java/query/query-core/src/main/java/sleeper/query/core/output/ResultsOutputLocation.java
  java/query/query-runner/pom.xml
  java/query/query-runner/src/main/java/sleeper/query/runner/output/WebSocketResultsOutput.java
  java/query/query-runner/src/main/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestination.java
  java/query/query-runner/src/main/java/sleeper/query/runner/websocket/ApiGatewayWebSocketOutput.java
  java/query/query-runner/src/main/java/sleeper/query/runner/websocket/QueryWebSocketMessage.java
  java/query/query-runner/src/main/java/sleeper/query/runner/websocket/QueryWebSocketMessageException.java
  java/query/query-runner/src/main/java/sleeper/query/runner/websocket/QueryWebSocketMessageSerDe.java
  java/query/query-runner/src/main/java/sleeper/query/runner/websocket/QueryWebSocketMessageType.java
  java/query/query-runner/src/main/java/sleeper/query/runner/websocket/QueryWebSocketRowsException.java
  java/query/query-runner/src/test/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestinationIT.java
  java/query/query-runner/src/test/java/sleeper/query/runner/websocket/QueryWebSocketMessageSerDeTest.Rows.shouldSerDeRows.approved.txt
  java/query/query-runner/src/test/java/sleeper/query/runner/websocket/QueryWebSocketMessageSerDeTest.StatusMessages.shouldSerDeQueryCompleted.approved.json
  java/query/query-runner/src/test/java/sleeper/query/runner/websocket/QueryWebSocketMessageSerDeTest.StatusMessages.shouldSerDeQueryError.approved.json
  java/query/query-runner/src/test/java/sleeper/query/runner/websocket/QueryWebSocketMessageSerDeTest.StatusMessages.shouldSerDeQueryErrorNoOutput.approved.json
  java/query/query-runner/src/test/java/sleeper/query/runner/websocket/QueryWebSocketMessageSerDeTest.StatusMessages.shouldSerDeQueryWasSplitToSubqueries.approved.json
  java/query/query-runner/src/test/java/sleeper/query/runner/websocket/QueryWebSocketMessageSerDeTest.java
Labels: pr-base-for-stacking, needs-reviewer

#5292 Issue 5287 - Use web socket message serialiser in query runner
  java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
  java/query/query-runner/src/main/java/sleeper/query/runner/output/WebSocketResultsOutput.java
  java/query/query-runner/src/main/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestination.java
  java/query/query-runner/src/main/java/sleeper/query/runner/websocket/QueryWebSocketMessageSerDe.java
  java/query/query-runner/src/main/java/sleeper/query/runner/websocket/QueryWebSocketRowsException.java
  java/query/query-runner/src/test/java/sleeper/query/runner/output/WebSocketResultsOutputIT.java
  java/query/query-runner/src/test/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestinationIT.java
Labels: pr-stacked-top

#5310 Issue 5298 - Rename Java packages from Rust to DataFusion
  .github/config/chunks.yaml
  .github/workflows/chunk-clients-cdk.yaml
  .github/workflows/chunk-compaction.yaml
  .github/workflows/chunk-rust.yaml
  java/compaction/compaction-datafusion/pom.xml
  java/compaction/compaction-datafusion/src/main/java/sleeper/compaction/datafusion/DataFusionCompactionRunner.java
  java/compaction/compaction-datafusion/src/main/java/sleeper/compaction/datafusion/DataFusionFunctions.java
  java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerIT.java
  java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerLocalStackIT.java
  java/compaction/compaction-job-execution/pom.xml
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/DefaultCompactionRunnerFactory.java
  java/compaction/pom.xml
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/InvestigateDataFusionCompactionOOM.java
Labels: pr-base-for-stacking

#5313 Issue 5295 - Remove Rust side allocation of objects
  java/compaction/compaction-datafusion/src/main/java/sleeper/compaction/datafusion/DataFusionCompactionRunner.java
  java/compaction/compaction-datafusion/src/main/java/sleeper/compaction/datafusion/DataFusionFunctions.java
  rust/compactor/src/bin/main.rs
  rust/sleeper_df/src/details.rs
  rust/sleeper_df/src/lib.rs
  rust/sleeper_df/tests/compaction_test.rs
Labels: pr-stacked-top

#5336 Issue 5315 - Add Javadoc to PR template
  .github/pull_request_template.md
  docs/development/conventions.md
Labels: needs-reviewer

#5370 5368: Fix issue with ingest when user uses a double slash in the path
  java/configuration/src/main/java/sleeper/configuration/utils/S3Path.java
  java/configuration/src/test/java/sleeper/configuration/utils/S3ExpandDirectoriesIT.java
  java/configuration/src/test/java/sleeper/configuration/utils/S3PathTest.java
Labels: one-review-required
