Repository gchq/sleeper, pull requests merged in 2025-01, with the labels that each got.

#4026 Issue 4025 - Use async_trait for LoggingObjectStore
  rust/Cargo.lock
  rust/compaction/Cargo.toml
  rust/compaction/src/store.rs
Labels: pr-stacked-top

#4030 Issue 3972 - Rename status stores to trackers in documentation
  docs/14-design.md
  docs/designs/transaction-log-state-store.md
  example/full/instance.properties
  java/clients/src/main/java/sleeper/clients/admin/CompactionStatusReportScreen.java
  java/clients/src/main/java/sleeper/clients/admin/IngestStatusReportScreen.java
  java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/IngestStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/admin/testutils/ExpectedAdminConsoleValues.java
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/IngestProperty.java
  scripts/templates/instanceproperties.template
Labels: pr-base-for-stacking

#4042 Issue 3899 - State store method to add a transaction from S3
  java/core/src/main/java/sleeper/core/statestore/transactionlog/AddTransactionRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionBodyPointer.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionBodyStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogEntry.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionBodyStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogs.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
Labels: one-review-required

#4060 Issue 3900 - Ignore invalid compaction commits
  .vscode/settings.json
  java/core/src/main/java/sleeper/core/statestore/FileReference.java
  java/core/src/main/java/sleeper/core/statestore/ReplaceFileReferencesRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/AddTransactionRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/StateListenerBeforeApply.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ReplaceFileReferencesTransaction.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreCompactionCommitByTransactionTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
  java/core/src/test/java/sleeper/core/tracker/compaction/job/CompactionJobEventTestData.java
  java/core/src/test/java/sleeper/core/tracker/compaction/job/CompactionJobStatusTestData.java
  java/core/src/test/java/sleeper/core/tracker/compaction/job/InMemoryCompactionJobTrackerTest.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
Labels: pr-base-for-stacking

#4063 Issue 3901 - State store commit request by transaction in S3
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJob.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/commit/CompactionJobCommitter.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/commit/CompactionJobCommitterOrSendToLambda.java
  java/core/src/main/java/sleeper/core/statestore/ReplaceFileReferencesRequest.java
  java/core/src/main/java/sleeper/core/statestore/commit/StateStoreCommitRequestByTransaction.java
  java/core/src/main/java/sleeper/core/statestore/commit/StateStoreCommitRequestByTransactionSerDe.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/AddTransactionRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionBodyStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionBodyStoreProvider.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ReplaceFileReferencesTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDe.java
  java/core/src/test/java/sleeper/core/statestore/commit/StateStoreCommitRequestByTransactionSerDeTest.java
  java/core/src/test/java/sleeper/core/statestore/commit/StateStoreCommitRequestByTransactionSerDeTest.shouldSerialiseCompactionCommitInS3.approved.json
  java/core/src/test/java/sleeper/core/statestore/commit/StateStoreCommitRequestByTransactionSerDeTest.shouldSerialiseInitialisePartitionsDirectly.approved.json
  java/core/src/test/java/sleeper/core/statestore/commit/StateStoreCommitRequestByTransactionSerDeTest.shouldSerialiseInitialisePartitionsInS3.approved.json
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogsPerTable.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionBodyStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogs.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequest.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiser.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiserTest.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterThroughputIT.java
  java/statestore-lambda/src/main/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambda.java
  java/statestore-lambda/src/test/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambdaTest.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/S3TransactionBodyStore.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperTablesDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryStateStoreCommitter.java
Labels: pr-stacked-top

#4081 Issue 4080 - Convert ingest & bulk import async commits to send transaction
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/runner/BulkImportJobDriver.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverTest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/AddFilesTransaction.java
  java/ingest/ingest-core/pom.xml
  java/ingest/ingest-core/src/main/java/sleeper/ingest/core/job/commit/IngestAddFilesCommitRequest.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/core/job/commit/IngestAddFilesCommitRequestSerDe.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/core/job/commit/IngestAddFilesCommitRequestSerDeTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/core/job/commit/IngestAddFilesCommitRequestSerDeTest.shouldSerialiseIngestJobCommitRequest.approved.txt
  java/ingest/ingest-core/src/test/java/sleeper/ingest/core/job/commit/IngestAddFilesCommitRequestSerDeTest.shouldSerialiseIngestJobCommitRequestWithNoJob.approved.txt
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/commit/AddFilesToStateStore.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/task/IngestJobRunner.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/impl/commit/AddFilesToStateStoreIT.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/task/IngestJobRunnerIT.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequest.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiser.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiserTest.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterThroughputIT.java
  java/statestore-lambda/src/test/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambdaTest.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriverIT.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitMessageFactory.java
Labels: pr-stacked-middle

#4083 Issue 4082 - Convert compaction job assignment async commits to send transaction
  java/clients/src/main/java/sleeper/clients/status/update/CreateCompactionJobsClient.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJobCommitterOrSendToLambda.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/commit/CompactionJobIdAssignmentCommitRequest.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/commit/CompactionJobIdAssignmentCommitRequestSerDe.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/creation/AssignJobIdQueueSender.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/creation/AssignJobIdToFiles.java
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/CompactionTask.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/commit/CompactionJobIdAssignmentCommitRequestSerDeTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/commit/CompactionJobIdAssignmentCommitRequestSerDeTest.shouldSerialiseCompactionJobIdAssignmentCommitRequest.approved.json
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/commit/CompactionJobIdAssignmentCommitRequestTestHelper.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/creation/CreateCompactionJobsTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
  java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsLambda.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/AwsCreateCompactionJobs.java
  java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/SendAssignJobIdToSqs.java
  java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/AwsCreateCompactionJobsIT.java
  java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
  java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
  java/core/src/main/java/sleeper/core/statestore/commit/CommitRequestType.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequest.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiser.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiserTest.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitMessageFactory.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
Labels: pr-stacked-middle

#4088 Issue 4084 - Convert partition splitting async commits to send transaction
  java/core/src/main/java/sleeper/core/statestore/commit/CommitRequestType.java
  java/core/src/main/java/sleeper/core/statestore/commit/SplitPartitionCommitRequest.java
  java/core/src/main/java/sleeper/core/statestore/commit/SplitPartitionCommitRequestSerDe.java
  java/core/src/test/java/sleeper/core/statestore/commit/SplitPartitionCommitRequestSerDeTest.java
  java/core/src/test/java/sleeper/core/statestore/commit/SplitPartitionCommitRequestSerDeTest.shouldSerialiseSplitPartitionRequest.approved.txt
  java/splitter/splitter-core/src/main/java/sleeper/splitter/core/split/SplitPartition.java
  java/splitter/splitter-core/src/test/java/sleeper/splitter/core/split/SplitPartitionTest.java
  java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/SplitPartitionLambda.java
  java/splitter/splitter-lambda/src/test/java/sleeper/splitter/lambda/SplitPartitionLambdaIT.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequest.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiser.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiserTest.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
Labels: pr-stacked-middle

#4094 Issue 4092 - Update functions in SketchUDF Impl
  rust/compaction/src/datafusion/udf.rs
Labels: rust

#4089 Issue 4085 - Convert GC async commits to send transaction
  java/core/src/main/java/sleeper/core/statestore/commit/CommitRequestType.java
  java/core/src/main/java/sleeper/core/statestore/commit/GarbageCollectionCommitRequest.java
  java/core/src/main/java/sleeper/core/statestore/commit/GarbageCollectionCommitRequestSerDe.java
  java/core/src/main/java/sleeper/core/statestore/commit/StateStoreCommitRequestInS3SerDe.java
  java/core/src/test/java/sleeper/core/statestore/commit/GarbageCollectionCommitRequestSerDeTest.java
  java/core/src/test/java/sleeper/core/statestore/commit/GarbageCollectionCommitRequestSerDeTest.shouldSerialiseGarbageCollectionCommitRequest.approved.txt
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
  java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorLambda.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
  java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequest.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiser.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiserTest.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitMessageFactory.java
Labels: pr-base-for-stacking

#4100 Issue 4077 - Upgrade AWS SDK v2
  java/pom.xml
Labels: pr-stacked-top

#4108 Issue 4107 - Add also-make flag in CLI environment build script
  scripts/cli/environment/buildMaven.sh
Labels: one-review-required

#4117 Issue 3878 - Explain ingest record batch types in a single document
  docs/common-problems-and-their-solutions.md
  docs/design/arrow-ingest.md
  docs/design/ingest-record-batch-types.md
Labels: one-review-required

#4118 4116 enhance metric reporting on parquet files during compaction
  rust/compaction/src/datafusion.rs
  rust/compaction/src/datafusion/metrics.rs
Labels: compactions-module, rust

#4122 Issue 3906 - Deploy compaction commit batcher lambda
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/CoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/LoggingStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/StateStoreCommitterStack.java
  java/core/src/main/java/sleeper/core/deploy/LambdaHandler.java
  java/core/src/main/java/sleeper/core/deploy/SqsQueues.java
  java/core/src/main/java/sleeper/core/properties/instance/CdkDefinedInstanceProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#4142 Issue 4132 - Option to disable job tracker update when a compaction job is committed
  example/full/instance.properties
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterThroughputIT.java
  java/statestore-lambda/src/main/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambda.java
  java/statestore-lambda/src/test/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambdaTest.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryStateStoreCommitter.java
  scripts/templates/instanceproperties.template
Labels: one-review-required

#4145 Issue 4135 - Fix bulk import reporting
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverIT.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverTest.java
  java/clients/src/test/java/sleeper/clients/admin/IngestStatusReportScreenTest.java
  java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterTestBase.java
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/IngestJobStatusReporterTestData.java
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporterDetailedQueryTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskCommitTest.java
  java/compaction/compaction-tracker/src/test/java/sleeper/compaction/tracker/job/StoreCompactionJobRunIdIT.java
  java/compaction/compaction-tracker/src/test/java/sleeper/compaction/tracker/testutils/DynamoDBCompactionJobTrackerTestBase.java
  java/core/src/main/java/sleeper/core/tracker/compaction/task/CompactionTaskStatus.java
  java/core/src/main/java/sleeper/core/tracker/ingest/job/query/IngestJobValidatedStatus.java
  java/core/src/main/java/sleeper/core/tracker/ingest/task/IngestTaskStatus.java
  java/core/src/main/java/sleeper/core/tracker/job/run/JobRun.java
  java/core/src/main/java/sleeper/core/tracker/job/run/JobRunsBuilder.java
  java/core/src/main/java/sleeper/core/tracker/job/status/JobRunStartedUpdate.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreCompactionCommitByTransactionTest.java
  java/core/src/test/java/sleeper/core/tracker/compaction/job/CompactionJobStatusFromRecordsTest.java
  java/core/src/test/java/sleeper/core/tracker/compaction/job/CompactionJobStatusTestData.java
  java/core/src/test/java/sleeper/core/tracker/compaction/job/InMemoryCompactionJobTrackerTest.java
  java/core/src/test/java/sleeper/core/tracker/ingest/job/InMemoryIngestJobTrackerTest.java
  java/core/src/test/java/sleeper/core/tracker/ingest/job/IngestJobStatusInPeriodTest.java
  java/core/src/test/java/sleeper/core/tracker/ingest/job/IngestJobStatusTest.java
  java/core/src/test/java/sleeper/core/tracker/ingest/job/IngestJobStatusTestData.java
  java/core/src/test/java/sleeper/core/tracker/job/run/AverageRecordRateTest.java
  java/core/src/test/java/sleeper/core/tracker/job/run/JobRunTestData.java
  java/core/src/test/java/sleeper/core/tracker/job/run/JobRunsTest.java
  java/ingest/ingest-core/src/test/java/sleeper/ingest/core/job/IngestJobStatusFromJobTestData.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/task/IngestJobRunnerIT.java
  java/ingest/ingest-tracker/src/test/java/sleeper/ingest/tracker/job/StoreIngestJobRunIdIT.java
  java/ingest/ingest-tracker/src/test/java/sleeper/ingest/tracker/testutils/DynamoDBIngestJobTrackerTestBase.java
  java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java
Labels: one-review-required

#4152 Issue 4151 - Bulk import reporting tests
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/IngestJobStatusReporterTestData.java
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/JsonIngestJobStatusReporterAllQueryTest.java
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporterAllQueryTest.java
  java/clients/src/test/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporterDetailedQueryTest.java
  java/clients/src/test/resources/reports/ingest/job/json/bulkImport/finishedJob.json
  java/clients/src/test/resources/reports/ingest/job/standard/all/bulkImport/finishedJob.txt
  java/clients/src/test/resources/reports/ingest/job/standard/detailed/bulkImport/finishedJob.txt
  java/core/src/test/java/sleeper/core/tracker/ingest/job/IngestJobStatusTest.java
Labels: one-review-required

#4153 Issue 3606 - Replace queue visibility timeout instance property
  example/full/instance.properties
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/query/QueryStack.java
  java/core/src/main/java/sleeper/core/properties/instance/BatcherProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/CommonProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/IngestProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/QueryProperty.java
  java/core/src/test/java/sleeper/core/properties/instance/InstancePropertiesTest.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/task/IngestJobQueueConsumer.java
  scripts/templates/instanceproperties.template
Labels: one-review-required
