Repository gchq/sleeper, pull requests merged in 2025-04, with the labels that each got.

#4581 Issue 4411 - Improve description of property `sleeper.tags`
  docs/usage/properties/instance/common.md
  java/core/src/main/java/sleeper/core/properties/instance/CommonProperty.java
Labels: one-review-required

#4583 Issue 4357 - Updated deprecated methods with replacement version
  java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTrackerStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/TableIndexStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestTrackerStack.java
Labels: one-review-required

#4606 4519: Change queryExecutorCache in SqsQueryProcessor to use TableId i…
  java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
Labels: one-review-required

#4617 Issue 4616- Bump version of C++ Apache DataSketches library
  rust/rust_sketch/build.rs
Labels: one-review-required

#4685 Issue 4684 - Fix Python snapshot version number
  docs/development/release-process.md
  python/setup.py
Labels: one-review-required

#4636 Issue 4628 - Added metadata versioning for Apache DataSketches
  NOTICES
  rust/Cargo.lock
  rust/Cargo.toml
  rust/rust_sketch/Cargo.toml
  rust/rust_sketch/build.rs
Labels: one-review-required, rust

#4696 Issue 4695 - Don't make assumptions about row key column positions.
  rust/compaction/src/datafusion.rs
  rust/compaction/tests/compaction_test.rs
Labels: one-review-required, rust

#4703 Issue 4664 - New method for doesTableExist
  java/clients/src/main/java/sleeper/clients/api/SleeperClient.java
  java/clients/src/test/java/sleeper/clients/api/SleeperClientTest.java
Labels: one-review-required

#4693 Issue 4692 - DataFusion helper application executable panic on incorrect partition region length
  NOTICES
  rust/Cargo.lock
  rust/Cargo.toml
  rust/compaction/src/details.rs
  rust/compactor/Cargo.toml
  rust/compactor/src/bin/main.rs
  rust/compactor/tests/compactor_cli.rs
Labels: rust

#4719 Issue 4716 - Better DataFusion log messages
  rust/compaction/src/datafusion.rs
  rust/compaction/src/readahead.rs
  rust/compaction/src/s3.rs
  rust/compaction/src/store.rs
Labels: pr-base-for-stacking, on-hold, rust

#4713 Issue 4706: AWS SDK v2 implementation of dynamodb-tools
  .github/config/chunks.yaml
  .github/workflows/chunk-common.yaml
  code-style/checkstyle-idea/checkstyle-suppressions.xml
  code-style/checkstyle-suppressions.xml
  java/common/dynamodb-toolsv2/pom.xml
  java/common/dynamodb-toolsv2/src/main/java/sleeper/dynamodb/toolsv2/DynamoDBAttributes.java
  java/common/dynamodb-toolsv2/src/main/java/sleeper/dynamodb/toolsv2/DynamoDBRecordBuilder.java
  java/common/dynamodb-toolsv2/src/main/java/sleeper/dynamodb/toolsv2/DynamoDBUtils.java
  java/common/dynamodb-toolsv2/src/main/java/sleeper/dynamodb/toolsv2/LoadedItemsWithLimit.java
  java/common/dynamodb-toolsv2/src/test/java/sleeper/dynamodb/toolsv2/DynamoDBAttributesTest.java
  java/common/dynamodb-toolsv2/src/test/java/sleeper/dynamodb/toolsv2/DynamoDBRecordBuilderIT.java
  java/common/dynamodb-toolsv2/src/test/java/sleeper/dynamodb/toolsv2/DynamoDBToolsTestBase.java
  java/common/dynamodb-toolsv2/src/test/java/sleeper/dynamodb/toolsv2/DynamoDBUtilsPagingIT.java
  java/common/dynamodb-toolsv2/src/test/java/sleeper/dynamodb/toolsv2/DynamoDBUtilsPagingLimitIT.java
  java/common/dynamodb-toolsv2/src/test/java/sleeper/dynamodb/toolsv2/DynamoDBUtilsTest.java
  java/common/pom.xml
Labels: on-hold, one-review-required

#4675 Issue 2937 - AWS SDK v2 implementation of instance properties save/load
  .github/config/chunks.yaml
  .github/workflows/chunk-common.yaml
  java/configurationV2/pom.xml
  java/configurationV2/src/main/java/sleeper/configurationv2/properties/S3InstanceProperties.java
  java/configurationV2/src/main/java/sleeper/configurationv2/properties/S3PropertiesReloader.java
  java/configurationV2/src/main/java/sleeper/configurationv2/properties/S3TableProperties.java
  java/configurationV2/src/main/java/sleeper/configurationv2/utils/AwsV2ClientHelper.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/S3InstancePropertiesTestHelper.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/S3PropertiesReloaderIT.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/S3TablePropertiesStoreIT.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/SaveLocalPropertiesS3IT.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/TablePropertiesITBase.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/TablePropertiesProviderIT.java
  java/pom.xml
Labels: one-review-required

#4735 2938 aws sdk v2 implementation of table index
  java/configurationV2/pom.xml
  java/configurationV2/src/main/java/sleeper/configurationv2/properties/S3InstanceProperties.java
  java/configurationV2/src/main/java/sleeper/configurationv2/properties/S3TableProperties.java
  java/configurationV2/src/main/java/sleeper/configurationv2/table/index/DynamoDBTableIdFormat.java
  java/configurationV2/src/main/java/sleeper/configurationv2/table/index/DynamoDBTableIndex.java
  java/configurationV2/src/main/java/sleeper/configurationv2/table/index/DynamoDBTableIndexCreator.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/S3PropertiesReloaderIT.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/SaveLocalPropertiesS3IT.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/TablePropertiesITBase.java
  java/configurationV2/src/test/java/sleeper/configurationv2/properties/TablePropertiesProviderIT.java
  java/configurationV2/src/test/java/sleeper/configurationv2/table/index/DynamoDBTableIndexDynamoSpecificIT.java
  java/configurationV2/src/test/java/sleeper/configurationv2/table/index/DynamoDBTableIndexIT.java
Labels: one-review-required

#4743 Issue 4733 - Drain all jobs in CompactionCreationST
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsResetInstanceOnFirstConnect.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/sqs/AwsDrainSqsQueue.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/sqs/ReceiveMessages.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/sqs/RetriesLimitHitException.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriverIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/compaction/CompactionFakeCommitIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsResetInstanceOnFirstConnectIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSystemTestDrivers.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/util/AwsDrainSqsQueueTest.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/util/sqs/AwsDrainSqsQueueIT.java
  java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/util/sqs/AwsDrainSqsQueueTest.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/CompactionDriver.java
  java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
  java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionCreationST.java
Labels: one-review-required

#4738 Issue 4551 - Ingest design diagrams
  docs/design.md
  docs/design/bulk-import.drawio
  docs/design/bulk-import.png
  docs/design/ingest-batcher.drawio
  docs/design/ingest-batcher.png
  docs/design/standard-ingest.drawio
  docs/design/standard-ingest.png
Labels: pr-base-for-stacking

#4750 Issue 4748 - Deploy system test queue
  java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java
  java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
Labels: one-review-required
