Repository gchq/sleeper, pull requests merged in 2025-02, with the labels that each got.

#4203 Removal of DynamoDB StateStore functionality
  docs/design/postgresql-state-store.md
  docs/usage/tables.md
  example/full/instance.properties
  example/full/table.properties
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverIT.java
  java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/DynamoDBStateStoreStack.java
  java/cdk/src/main/java/sleeper/cdk/stack/core/StateStoreStacks.java
  java/cdk/src/main/java/sleeper/cdk/util/NewInstanceValidator.java
  java/cdk/src/test/java/sleeper/cdk/util/NewInstanceValidatorIT.java
  java/clients/src/main/java/sleeper/clients/docker/stack/TableDockerStack.java
  java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
  java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
  java/core/src/main/java/sleeper/core/properties/instance/CdkDefinedInstanceProperty.java
  java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
  java/core/src/main/java/sleeper/core/properties/table/TableProperties.java
  java/core/src/main/java/sleeper/core/properties/table/TableProperty.java
  java/core/src/test/java/sleeper/core/properties/SleeperPropertiesValidationTest.java
  java/core/src/test/java/sleeper/core/properties/table/TablePropertiesAsyncCommitsTest.java
  java/core/src/test/java/sleeper/core/properties/testutils/InstancePropertiesTestHelper.java
  java/statestore/src/main/java/sleeper/statestore/StateStoreFactory.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceFormat.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionFormat.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStore.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStoreCreator.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/FailedDynamoDBReplaceReferences.java
  java/statestore/src/main/java/sleeper/statestore/dynamodb/FailedDynamoDBSplitRequests.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceFormatTest.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreDynamoSpecificIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBPartitionStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreMultipleTablesIT.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreOneTableTestBase.java
  java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreTestBase.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
  java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsResetInstanceOnFirstConnect.java
  java/trino/src/test/java/sleeper/trino/testutils/PopulatedSleeperExternalResource.java
  scripts/templates/instanceproperties.template
  scripts/templates/tableproperties.template
Labels: one-review-required

#4246 Issue 4245 - Read transactions from log by range
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/log/TransactionLogRange.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/log/TransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStoreTest.java
  java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogTransactionDeleterTest.java
Labels: pr-base-for-stacking, one-review-required

#4225 Issue 4207 - Apply compaction job tracker updates against state from transaction log
  java/core/src/main/java/sleeper/core/statestore/commit/StateStoreCommitRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/AddTransactionRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/state/CompactionJobTrackerStateListener.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/state/IngestJobTrackerStateListener.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/state/StateListenerBeforeApply.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/state/StateListenerBeforeApplyByType.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/TransactionType.java
  java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobEvent.java
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogsPerTable.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreFactory.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreFollowTransactionsTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/state/CompactionJobCommitTransactionTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/state/InMemoryTransactionLogStateStoreCompactionTrackerTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/state/InMemoryTransactionLogStateStoreIngestTrackerTestBase.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/state/IngestJobCommitTransactionTest.java
  java/core/src/test/java/sleeper/core/tracker/ingest/job/IngestJobEventTestData.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore-lambda/src/test/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambdaTest.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogTransactionDeleterTest.java
Labels: one-review-required, pr-stacked-middle

#4257 Issue 4253 - Apply Ingest Job Tracker update against state
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/state/IngestJobTrackerStateListener.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/AddFilesTransaction.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/state/CompactionJobCommitTransactionTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/state/IngestJobCommitTransactionTest.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
Labels: one-review-required, pr-stacked-top

#4283 Issue 4270 - Add Transaction To State Store Interface
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/PartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/StateStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/AddTransactionRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
  java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
  java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotCreatorIT.java
Labels: one-review-required

#4285 Issue 4279 - State store update wrapper for tests
  java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/StateStoreTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/AssignJobIdsTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/InitialisePartitionsTransaction.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/ReplaceFileReferencesTransaction.java
  java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogStateStoreTestBase.java
  java/core/src/test/java/sleeper/core/statestore/testutils/StateStoreUpdatesWrapper.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStoreTest.java
  java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStoreTest.java
Labels: one-review-required

#4322 4282 - Handle sync/asynchronous commit of ingest job tracker updates
  .vscode/settings.json
  java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/runner/BulkImportJobDriver.java
  java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverTest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/AddFilesTransaction.java
  java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobAddedFilesEvent.java
  java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobFailedEvent.java
  java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobFinishedEvent.java
  java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobRunIds.java
  java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobStartedEvent.java
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogs.java
  java/core/src/test/java/sleeper/core/tracker/ingest/job/IngestJobEventTestData.java
  java/ingest/ingest-core/src/main/java/sleeper/ingest/core/job/IngestJob.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/IngestCoordinator.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/commit/AddFilesToStateStore.java
  java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/task/IngestJobRunner.java
  java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/impl/commit/AddFilesToStateStoreTest.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
  java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryDirectIngestDriver.java
  java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
Labels: pr-base-for-stacking

#4324 Issue 4323 - Handle sync/asynchronous commit of compaction job tracker updates
  java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJobCommitterOrSendToLambda.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskCommitTest.java
  java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
  java/core/src/main/java/sleeper/core/statestore/ReplaceFileReferencesRequest.java
  java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/ReplaceFileReferencesTransaction.java
  java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogsPerTable.java
Labels: pr-stacked-top
